# CFA L1 Alternative Investments ~80
TERMS = [
("Alternative Investments", "另類投資", "相對傳統股債以外的資產類別，如私募、對沖基金、房地產、商品等。", "資產配置分散。", "\"Alternative investments can improve diversification if liquidity risk is accepted.\""),
("Traditional Investments", "傳統投資", "通常指公開市場股票、債券與現金。", "對照另類。", "\"We keep 70% in traditional investments and 30% in alternatives.\""),
("Private Equity", "私募股權", "投資非公開發行公司股權的資產類別。", "長期鎖定。", "\"Private equity commitments are drawn down over several years.\""),
("Venture Capital", "創投", "投資早期高成長新創的私募策略。", "高風險高回報。", "\"Venture capital funds target outsized winners to offset failures.\""),
("Growth Equity", "成長股權", "投資已有營收、需資金擴張但仍未成熟的公司。", "中後期私募。", "\"Growth equity sits between venture and buyouts in the life cycle.\""),
("Buyout / Leveraged Buyout", "併購／槓桿收購", "收購成熟公司並常搭配高槓桿的私募策略。", "控制權交易。", "\"The buyout fund took the retailer private with leveraged financing.\""),
("Distressed Investing", "困境投資", "投資財務困境公司的債或股以尋求重整收益。", "特殊情況。", "\"Distressed investing requires legal and restructuring expertise.\""),
("General Partner (GP)", "普通合夥人", "私募／創投基金中負責管理決策、負無限責任的一方（實務上常為管理公司）。", "基金治理。", "\"The GP decides which portfolio companies to exit this year.\""),
("Limited Partner (LP)", "有限合夥人", "出資並承擔有限責任、通常不參與日常管理的投資人。", "機構配置。", "\"As an LP, the pension plan commits capital but doesn't run the deals.\""),
("Limited Partnership", "有限合夥", "私募基金最常見法律結構，含 GP 與 LP。", "基金設立。", "\"Most buyout funds are organized as limited partnerships.\""),
("Commitment", "承諾出資額", "LP 承諾可被 GP 召繳的總金額。", "配置規劃。", "\"Our commitment to the fund is $50 million over the investment period.\""),
("Capital Call / Drawdown", "資金召繳", "GP 依交易需要向 LP 請求繳付承諾資金。", "流動性管理。", "\"A capital call arrived for the new platform acquisition.\""),
("Distribution", "分配", "基金將變現收益或本金返還 LP。", "回收。", "\"The exit generated a large distribution to limited partners.\""),
("J-Curve", "J曲線", "私募早期費用與未實現虧損使淨績效先下行再上升的型態。", "績效預期。", "\"Don't judge a young fund in year two—the J-curve is still in effect.\""),
("Carried Interest", "附帶權益／績效分成", "GP 在超過門檻後分享的利潤比例，常見約 20%。", "激勵。", "\"Carried interest aligns the GP with upside after returning capital.\""),
("Management Fee", "管理費", "按承諾或投入資本收取的固定管理費用。", "成本拖累。", "\"A 2% management fee on committed capital is costly in early years.\""),
("Hurdle Rate / Preferred Return", "門檻報酬／優先報酬", "GP 收取附帶權益前，LP 須先達到的報酬率。", "瀑布分配。", "\"The fund has an 8% hurdle rate before catch-up and carry.\""),
("Catch-Up Provision", "追補條款", "達到門檻後，分配暫時偏向 GP 直到達成約定分成比。", "瀑布細節。", "\"After the hurdle, the catch-up provision directs profits to the GP temporarily.\""),
("Waterfall", "分配瀑布", "規定現金如何在 LP／GP 間依序分配的機制。", "條款談判。", "\"American versus European waterfall affects when carry is paid.\""),
("Clawback", "追回條款", "若 GP 前期多領附帶權益，結束時須退還的條款。", "保護LP。", "\"The clawback protects LPs if early winners are offset by later losers.\""),
("Vintage Year", "成立年份", "基金開始投資的年份，用以同儕比較。", "績效基準。", "\"Compare 2018 vintage year funds against the same cohort.\""),
("Investment Period", "投資期", "基金積極部署新投資的期間。", "召繳高峰。", "\"Capital calls are heaviest during the investment period.\""),
("Harvest Period", "收穫期", "著重退出與分配、較少新投資的後期。", "現金回流。", "\"During the harvest period, distributions should exceed capital calls.\""),
("Dry Powder", "待投資金", "已承諾尚未投放的資金。", "市場競爭。", "\"Industry dry powder remains high, pressuring entry valuations.\""),
("Committed Capital vs Invested Capital", "承諾 vs 已投資本", "承諾是上限；已投資是實際投入組合的金額。", "費用基礎。", "\"Fees sometimes switch from committed capital to invested capital later.\""),
("Paid-In Capital", "實繳資本", "LP 已實際繳付的資本。", "績效分母。", "\"TVPI uses paid-in capital in the denominator.\""),
("Residual Value", "剩餘價值", "基金持有未退出投資的估計淨值。", "NAV。", "\"Residual value plus distributions equals total value for TVPI.\""),
("TVPI", "總價值對實繳比", "（分配＋剩餘價值）／實繳資本。", "倍數績效。", "\"A TVPI of 1.8× means total value is 1.8 times paid-in capital.\""),
("DPI", "分配對實繳比", "累計分配／實繳資本，衡量已實現回收。", "現金回收。", "\"DPI above 1.0× means LPs have received more cash than they paid in.\""),
("RVPI", "剩餘價值對實繳比", "剩餘價值／實繳資本。", "未實現部分。", "\"High RVPI with low DPI means value is still mostly unrealized.\""),
("IRR (Private Equity)", "內部報酬率（私募）", "考量現金流時間的年化報酬；對召繳／分配時點敏感。", "績效呈報。", "\"Gross IRR ignores fees; quote net IRR to LPs.\""),
("PME (Public Market Equivalent)", "公開市場等值", "將私募現金流與公開市場指數比較的方法。", "相對績效。", "\"PME analysis asks whether PE beat a listed equity benchmark.\""),
("Co-Investment", "共同投資", "LP 在基金之外直接參與單一交易，通常費用較低。", "降低費用。", "\"We secured a co-investment alongside the flagship fund.\""),
("Secondary Market (PE)", "私募二級市場", "買賣既有LP權益或基金組合的市場。", "流動性。", "\"Selling our stake in the secondary market crystallized the NAV discount.\""),
("Hedge Fund", "對沖基金／避險基金", "靈活運用多空、槓桿、衍生性商品等策略的私募投資工具。", "絕對報酬。", "\"The hedge fund targets absolute returns with low market beta.\""),
("Lockup Period", "閉鎖期", "投資人不可贖回的期間。", "流動性條款。", "\"A one-year lockup period limits early redemptions.\""),
("Gate Provision", "閘門條款", "限制單期可贖回比例，保護剩餘投資人。", "流動性壓力。", "\"The fund imposed a gate provision amid redemption requests.\""),
("Side Pocket", "獨立帳戶／側袋", "將流動性差資產隔離、限制其贖回的安排。", "公平對待。", "\"Illiquid positions were moved into a side pocket.\""),
("High-Water Mark", "高水位機制", "績效費僅在淨值創新高後才收取，避免重複收費。", "費用條款。", "\"Below the high-water mark, no performance fee is charged.\""),
("2 and 20", "二二十費率", "約 2% 管理費加 20% 績效費的傳統費率結構。", "成本。", "\"Investors pushed back on classic 2 and 20 fee terms.\""),
("Long/Short Equity", "多空股票", "做多看好、放空看壞股票的對沖策略。", "股票避險。", "\"The long/short equity book is market-neutral by design.\""),
("Market Neutral", "市場中性", "多空曝險平衡、目標低淨市場曝險。", "低beta。", "\"A market neutral strategy seeks alpha with near-zero beta.\""),
("Event-Driven", "事件驅動", "圍繞併購、重整、分拆等公司事件的策略。", "特殊情況。", "\"Event-driven funds thrived during the merger wave.\""),
("Merger Arbitrage", "併購套利", "買目標、放空收購方等，賺取成交價差的策略。", "交易風險。", "\"Merger arbitrage spreads widened when antitrust risk rose.\""),
("Distressed Debt Strategy", "困境債策略", "買賣困境債務並可能參與重整的對沖策略。", "信用事件。", "\"The distressed debt strategy took a blocking stake in the bonds.\""),
("Global Macro", "全球總體", "依總經判斷交易貨幣、利率、商品與股指的策略。", "大方向。", "\"Global macro profits from policy divergence across regions.\""),
("Managed Futures / CTA", "管理期貨", "在期貨市場依系統或判斷交易的策略。", "趨勢跟隨。", "\"Managed futures often trend-follow across asset classes.\""),
("Relative Value", "相對價值", "賺取相關資產定價偏差、壓低方向性曝險的策略。", "價差。", "\"Relative value trades the cheap bond versus the rich bond.\""),
("Convertible Arbitrage", "可轉債套利", "買可轉債並放空股票等對沖的策略。", "波動與信用。", "\"Convertible arbitrage is sensitive to implied volatility and credit spreads.\""),
("Fixed-Income Arbitrage", "固定收益套利", "利用利率或信用曲線相對定價偏差的策略。", "槓桿利差。", "\"Fixed-income arbitrage often uses high leverage on small spreads.\""),
("Fund of Funds", "組合基金", "投資一籃子對沖基金或其他基金的基金。", "分散與篩選。", "\"A fund of funds adds a fee layer but helps with manager selection.\""),
("Prime Broker", "主要經紀商", "為對沖基金提供融資、借券、結算等服務的機構。", "營運基建。", "\"The prime broker financed the long/short book.\""),
("Real Assets", "實物資產", "具實體形態的資產，如房地產、基礎建設、自然資源、商品。", "通膨保護。", "\"Real assets can hedge unexpected inflation better than nominal bonds.\""),
("Real Estate", "房地產", "住宅、辦公、零售、工業等不動產投資。", "收益與增值。", "\"Core real estate offers stable income with moderate leverage.\""),
("REIT", "不動產投資信託", "持有或融資不動產並常高比例配息的公司／信託。", "流動性房地產。", "\"Equity REITs provide listed exposure to property portfolios.\""),
("Core Real Estate", "核心型房地產", "優質地段、高出租率、低槓桿的穩健策略。", "保守配置。", "\"Core real estate targets income over opportunistic appreciation.\""),
("Value-Add Real Estate", "增值型房地產", "透過整修、重新出租等提升價值的策略。", "中等風險。", "\"Value-add real estate needs CapEx to lift occupancy and rents.\""),
("Opportunistic Real Estate", "機會型房地產", "開發、重整等高風險高報酬房地產策略。", "循環底部。", "\"Opportunistic real estate resembles private equity in risk profile.\""),
("Infrastructure", "基礎建設", "交通、能源、公用等長天期實物資產投資。", "穩定現金流。", "\"Infrastructure assets often have regulated or contracted cash flows.\""),
("Brownfield vs Greenfield", "棕地 vs 綠地", "已營運資產 vs 新建開發專案。", "風險差異。", "\"Brownfield assets are lower risk than greenfield construction.\""),
("Commodities", "商品", "能源、金屬、農產品等大宗商品曝險。", "通膨與周期。", "\"Commodities can diversify a portfolio when inflation surprises.\""),
("Contango", "正價差／遠期升水", "期貨價格高於即期、遠月高於近月的曲線型態。", "展期成本。", "\"In contango, rolling long futures tends to lose roll yield.\""),
("Backwardation", "逆價差／遠期貼水", "期貨低於即期、近月高於遠月的型態。", "展期收益。", "\"Backwardation can produce positive roll yield for long commodity positions.\""),
("Roll Yield", "展期收益", "因期貨曲線型態，在換月時產生的收益或成本。", "商品總報酬。", "\"Total commodity return equals spot change plus roll yield plus collateral yield.\""),
("Collateral Yield", "抵押收益", "商品期貨部位抵押現金所賺取的利息。", "總報酬。", "\"Rising policy rates increased collateral yield on futures positions.\""),
("Farmland / Timberland", "農地／林地", "以農林業經營為基礎的實物資產投資。", "實物配置。", "\"Timberland returns include biological growth plus land price changes.\""),
("Digital Assets", "數位資產", "以區塊鏈記帳的加密貨幣、代幣等資產。", "新興另類。", "\"Digital assets remain highly volatile versus traditional alternatives.\""),
("Distributed Ledger Technology (DLT)", "分散式帳本技術", "多節點共享、同步帳本的技術，區塊鏈為其一種。", "結算創新。", "\"DLT could streamline settlement in private markets.\""),
("Blockchain", "區塊鏈", "以加密鏈結區塊記錄交易的分散式帳本形式。", "基礎設施。", "\"Blockchain underpins many cryptocurrency networks.\""),
("Cryptocurrency", "加密貨幣", "以密碼學與分散網路運行的數位貨幣。", "投機與支付。", "\"Cryptocurrency prices are extremely sensitive to liquidity and sentiment.\""),
("Tokenization", "代幣化", "將實物或金融資產權利以代幣形式表示於帳本上。", "流動性創新。", "\"Tokenization may fractionalize ownership of real estate.\""),
("Smart Contract", "智慧合約", "在區塊鏈上自動執行條款的程式。", "DeFi。", "\"A smart contract can automate escrow without a traditional intermediary.\""),
("Liquidity Risk (Alternatives)", "流動性風險（另類）", "難以按合理價格迅速變現的風險，另類尤其顯著。", "配置上限。", "\"Liquidity risk in alternatives means gates and lockups can delay cash.\""),
("Valuation Risk", "評價風險", "非流動資產公允價值估計不確定的風險。", "NAV品質。", "\"Stale marks create valuation risk in private portfolios.\""),
("Disposition Fee", "處分費", "部分基金在資產出售時收取的費用。", "條款審查。", "\"Watch for disposition fees that stack on top of carry.\""),
("Key Person Risk", "關鍵人風險", "核心投資專業人士離開導致策略受損的風險。", "盡職調查。", "\"Key person risk is high in a star-manager hedge fund.\""),
("Style Drift", "風格漂移", "管理人偏離宣稱策略的行為。", "監控。", "\"Style drift into illiquid credit surprised the fund-of-funds allocator.\""),
("Due Diligence (Alternatives)", "另類盡職調查", "對策略、營運、評價、合規與條款的深入查核。", "管理人遴選。", "\"Operational due diligence is as important as investment due diligence.\""),
("Side Letter", "附函協議", "與特定LP另訂的優惠或特殊條款。", "最惠國。", "\"The side letter granted us improved fee terms and reporting.\""),
("Most Favored Nation (MFN)", "最惠國條款", "確保某LP獲得不亞於其他LP優惠條款的權利。", "談判。", "\"Our MFN clause lets us match better terms given to later LPs.\""),
]