# CFA L1 Corporate Issuers ~120
TERMS = [
("Corporate Governance", "公司治理", "指導與控制公司的制度、流程與關係，平衡各方權益。", "董事會、股東權益。", "\"Strong corporate governance reduces agency conflicts with management.\""),
("Shareholder Theory", "股東理論", "主張公司首要目標是極大化股東價值。", "治理哲學。", "\"Under shareholder theory, social projects need a value rationale.\""),
("Stakeholder Theory", "利害關係人理論", "主張應兼顧員工、客戶、債權人、社區等利害關係人。", "ESG討論。", "\"Stakeholder theory argues employees and customers also deserve consideration.\""),
("Principal-Agent Problem", "委託－代理問題", "代理人（經理人）目標與委託人（股東）不一致產生的衝突。", "誘因設計。", "\"Stock options try to mitigate the principal-agent problem.\""),
("Agency Cost", "代理成本", "因代理衝突產生的監控、約束與剩餘損失等成本。", "治理效益。", "\"High agency costs show up as perquisite consumption and poor capex.\""),
("Board of Directors", "董事會", "代表股東監督管理階層的治理機關。", "戰略與風險監督。", "\"The board of directors approved the CEO succession plan.\""),
("Independent Director", "獨立董事", "與公司無重大關係、較能客觀監督的董事。", "委員會組成。", "\"A majority of independent directors strengthens board oversight.\""),
("Audit Committee", "審計委員會", "監督財務報導、內控與外部審計的董事會委員會。", "財報品質。", "\"The audit committee meets the external auditors without management present.\""),
("Compensation Committee", "薪酬委員會", "負責高階薪酬政策與計畫的委員會。", "誘因對齊。", "\"The compensation committee redesigned bonuses to emphasize ROIC.\""),
("Nomination Committee", "提名委員會", "負責董事提名與董事會組成的委員會。", "董事會更新。", "\"The nomination committee seeks directors with cybersecurity expertise.\""),
("Say-on-Pay", "薪酬投票", "股東對高階薪酬方案表達意見的機制（常為諮詢性）。", "股東行動。", "\"Investors voted against the package in a say-on-pay referendum.\""),
("Proxy Contest", "委託書爭奪", "挑戰者爭取股東委託書以改選董事或通過提案。", "激進投資。", "\"The activist launched a proxy contest to replace three directors.\""),
("Cumulative Voting", "累積投票制", "股東可將選票集中投給少數董事候選人，利於小股東。", "董事會選舉。", "\"Cumulative voting helped minority shareholders elect one director.\""),
("Straight Voting", "直接投票制", "每一董事席次分開投票，多數股東較易掌控全數席次。", "與累積比較。", "\"Under straight voting, a 51% owner can elect the entire board.\""),
("Dual-Class Shares", "雙層股權", "不同類股份投票權不同的結構。", "創辦人控制。", "\"Dual-class shares let founders retain control with less economic ownership.\""),
("Related-Party Transaction", "關係人交易", "與關係企業或關係人進行的交易，需防利益輸送。", "治理風險。", "\"Investors scrutinized the related-party transaction with the chair's firm.\""),
("Tunneling", "利益輸送／掏空", "控制股東將公司資源轉移圖利自身的行為。", "少數股東保護。", "\"Tunneling through transfer pricing harms minority shareholders.\""),
("ESG", "環境、社會與治理", "評估永續與治理因素的架構。", "責任投資。", "\"ESG integration affects our cost of capital assumptions.\""),
("Capital Budgeting", "資本預算", "評估長期投資專案是否創造價值的決策過程。", "專案取捨。", "\"Capital budgeting ranked the plant expansion above the buyback.\""),
("Net Present Value (NPV)", "淨現值", "未來現金流現值減初始投資；>0 表示創造價值。", "主要決策法則。", "\"Accept the project—the NPV is clearly positive.\""),
("Internal Rate of Return (IRR)", "內部報酬率", "使 NPV=0 的折現率；常與資金成本比較。", "報酬率溝通。", "\"The project's IRR exceeds our 9% hurdle rate.\""),
("Hurdle Rate", "門檻報酬率", "專案須達到的最低可接受報酬率。", "決策門檻。", "\"We set the hurdle rate above WACC for riskier ventures.\""),
("Payback Period", "回收期", "收回初始投資所需年數；忽略貨幣時間價值（簡單版）。", "流動性快速篩。", "\"Management likes the three-year payback period despite modest NPV.\""),
("Discounted Payback", "折現回收期", "以折現現金流計算的回收年數。", "較優於簡單回收。", "\"Discounted payback is longer than raw payback after discounting.\""),
("Profitability Index", "獲利能力指數", "未來現金流現值／初始投資，利於資本配額。", "預算受限。", "\"Choose the mix with the highest profitability index under the capex ceiling.\""),
("Mutually Exclusive Projects", "互斥專案", "只能擇一進行的專案。", "NPV vs IRR 衝突。", "\"For mutually exclusive projects, prefer the higher NPV, not IRR.\""),
("Independent Projects", "獨立專案", "可同時接受、互不排斥的專案。", "組合投資。", "\"All independent projects with positive NPV should be funded if capital allows.\""),
("Sunk Cost", "沉沒成本", "已發生且不可回收的成本，決策時應忽略。", "避免沉沒成本謬誤。", "\"Ignore the sunk cost of the failed pilot—decide on forward cash flows.\""),
("Opportunity Cost (Project)", "機會成本（專案）", "因專案而放棄的次佳用途價值，應計入現金流。", "閒置土地。", "\"Using owned land has an opportunity cost equal to its after-tax sale value.\""),
("Externality", "外部性", "專案對其他業務現金流的外溢影響（正或負）。", "蠶食效應。", "\"Cannibalization is a negative externality on existing product sales.\""),
("Cannibalization", "蠶食效應", "新產品排擠公司既有產品銷售。", "產品線。", "\"Subtract cannibalization when forecasting incremental revenue.\""),
("Incremental Cash Flow", "增量現金流", "因專案而多出的現金流，為資本預算核心。", "專案評估。", "\"Value only incremental cash flows attributable to the project.\""),
("Conventional Cash Flow Pattern", "傳統現金流型態", "期初流出、之後流入的型態；IRR 通常唯一。", "IRR適用。", "\"A conventional cash flow pattern supports a unique IRR.\""),
("Nonconventional Cash Flow", "非傳統現金流", "符號多次改變的現金流，可能有多個 IRR。", "改用NPV。", "\"With nonconventional cash flows, rely on NPV instead of IRR.\""),
("Crossover Rate", "交叉折現率", "兩互斥專案 NPV 相等的折現率。", "NPV剖面。", "\"Below the crossover rate, Project A has the higher NPV.\""),
("Cost of Capital", "資金成本", "投資人要求的報酬率，亦是專案折現率基礎。", "評價與預算。", "\"If ROIC stays above the cost of capital, value is created.\""),
("Weighted Average Cost of Capital (WACC)", "加權平均資金成本", "股權與債權成本依目標權重加權，稅盾調整後。", "折現率。", "\"We discount unlevered free cash flow at WACC.\""),
("Cost of Equity", "股權資金成本", "普通股投資人要求報酬率。", "CAPM、DDM。", "\"Using CAPM, the cost of equity is 11%.\""),
("Cost of Debt", "債務資金成本", "債權人要求報酬；稅後成本為 rd(1−t)。", "WACC輸入。", "\"The after-tax cost of debt fell after the upgrade.\""),
("Cost of Preferred Stock", "特別股資金成本", "特別股股利／淨發行價格。", "混合資本。", "\"The cost of preferred stock is Dp divided by net proceeds.\""),
("Target Capital Structure", "目標資本結構", "公司長期追求的負債與權益權重。", "WACC權重。", "\"Use target capital structure weights, not today's market blip.\""),
("Marginal Cost of Capital", "邊際資金成本", "再籌措下一單位資金的成本，可能隨融資額上升。", "IOS/MCC。", "\"The break point raises the marginal cost of capital schedule.\""),
("Investment Opportunity Schedule", "投資機會表", "依報酬率排序的可投資專案曲線。", "最適預算。", "\"Intersect the investment opportunity schedule with MCC to set the budget.\""),
("Break Point", "融資轉折點", "某資金來源用盡、須改用較貴來源時的融資總額。", "MCC階梯。", "\"Retained earnings run out at the break point, then we issue equity.\""),
("Flotation Cost", "發行成本", "發行新證券的承銷與行政成本。", "淨籌資額。", "\"Adjust for flotation costs when issuing new equity.\""),
("Modigliani-Miller Proposition I (no taxes)", "MM命題I（無稅）", "無稅無摩擦下，資本結構不影響企業價值。", "理論基準。", "\"MM Proposition I says leverage doesn't change firm value without taxes.\""),
("Modigliani-Miller Proposition II (no taxes)", "MM命題II（無稅）", "槓桿上升使股權成本上升，剛好抵消便宜債務。", "WACC不變。", "\"MM II shows the cost of equity rises linearly with the debt-equity ratio.\""),
("MM with Taxes", "有稅的MM", "利息稅盾使負債提高企業價值：VL=VU+tD。", "稅盾。", "\"With corporate taxes, MM implies value rises with debt due to the tax shield.\""),
("Financial Distress Costs", "財務困境成本", "高槓桿導致破產相關直接與間接成本。", "最適負債。", "\"Financial distress costs offset tax benefits at high leverage.\""),
("Trade-Off Theory", "權衡理論", "權衡稅盾利益與財務困境成本以決定負債水準。", "最適結構。", "\"Trade-off theory predicts an interior optimal debt ratio.\""),
("Pecking Order Theory", "融資順位理論", "因資訊不對稱，偏好內部資金→負債→新股。", "融資行為。", "\"Pecking order theory explains why firms avoid equity issues when possible.\""),
("Agency Cost of Debt", "債務代理成本", "股東－債權人衝突（如資產替代）造成的成本。", "債權契約。", "\"Tight covenants reduce the agency cost of debt.\""),
("Agency Cost of Equity", "股權代理成本", "經理人－股東衝突造成的成本；負債可有紀律效果。", "自由現金流。", "\"Debt can cut the agency cost of equity by limiting free cash flow waste.\""),
("Free Cash Flow Hypothesis", "自由現金流假說", "主張高自由現金流公司易過度投資，負債可約束。", "槓桿紀律。", "\"The free cash flow hypothesis supports leverage in mature cash cows.\""),
("Operating Leverage", "營運槓桿", "固定營運成本比重高使 EBIT 對銷售更敏感。", "業務風險。", "\"High operating leverage amplifies earnings swings when sales fall.\""),
("Financial Leverage", "財務槓桿", "固定財務成本（利息）使 EPS 對 EBIT 更敏感。", "資本結構風險。", "\"Financial leverage boosts EPS in good times but risks losses in downturns.\""),
("Degree of Operating Leverage (DOL)", "營運槓桿度", "%ΔEBIT / %ΔSales。", "敏感度。", "\"A DOL of 2 means a 1% sales drop cuts EBIT by about 2%.\""),
("Degree of Financial Leverage (DFL)", "財務槓桿度", "%ΔEPS / %ΔEBIT。", "利息負擔。", "\"Higher DFL reflects a heavier interest burden.\""),
("Degree of Total Leverage (DTL)", "總槓桿度", "DOL×DFL，銷售到 EPS 的總敏感度。", "綜合風險。", "\"DTL shows how sales shocks flow through to EPS.\""),
("Business Risk", "營業風險", "營業收入不確定性，受需求與營運槓桿影響。", "產業特性。", "\"Airlines have high business risk due to demand swings and fixed costs.\""),
("Financial Risk", "財務風險", "因負債融資導致的股東報酬額外不確定性。", "槓桿決策。", "\"Adding debt increases financial risk for equity holders.\""),
("Net Working Capital", "淨營運資金", "流動資產減流動負債，營運流動性需求。", "現金流預估。", "\"Growth will tie up more net working capital.\""),
("Cash Conversion Cycle", "現金轉換循環", "存貨期＋應收期−應付期，衡量資金綁住天數。", "營運效率。", "\"Shortening the cash conversion cycle frees cash for debt reduction.\""),
("Inventory Period", "存貨週轉天數", "存貨平均持有天數。", "供應鏈。", "\"Just-in-time cut the inventory period sharply.\""),
("Receivables Period", "應收帳款天數", "收回應收帳款平均天數。", "信用政策。", "\"Tighter credit terms reduced the receivables period.\""),
("Payables Period", "應付帳款天數", "支付供應商平均天數。", "供應商融資。", "\"Stretching the payables period must not damage supplier relations.\""),
("Working Capital Management", "營運資金管理", "管理流動資產與流動負債以平衡流動性與獲利。", "短債、現金。", "\"Working capital management targets enough liquidity without idle cash.\""),
("Liquidity Ratio", "流動性比率", "如流動比率、速動比率，衡量短期償債能力。", "信用分析。", "\"Banks watch liquidity ratios before extending the revolver.\""),
("Current Ratio", "流動比率", "流動資產／流動負債。", "流動性。", "\"A current ratio below 1 flags short-term liquidity stress.\""),
("Quick Ratio", "速動比率", "（現金＋有價證券＋應收）／流動負債，不含存貨。", "較嚴格流動性。", "\"The quick ratio fell after receivables deteriorated.\""),
("Cash Ratio", "現金比率", "（現金＋約當現金）／流動負債。", "極端流動性。", "\"The cash ratio shows how far cash alone covers current liabilities.\""),
("Line of Credit", "信用額度", "銀行承諾可動用的短期借款上限。", "流動性備援。", "\"We drew on the line of credit to fund seasonal inventory.\""),
("Commercial Paper", "商業本票", "高信用公司發行的短期無擔保票據。", "短融。", "\"The firm rolled commercial paper to fund working capital.\""),
("Trade Credit", "商業信用", "供應商提供的應付帳款融資。", "自發性融資。", "\"Trade credit is a cheap spontaneous source of short-term funds.\""),
("Secured Lending", "擔保放款", "以應收、存貨等作押的融資。", "短債結構。", "\"Inventory-secured lending increased after the downgrade.\""),
("Dividend Policy", "股利政策", "決定盈餘發放與留存的政策。", "股東報酬。", "\"Dividend policy signals confidence but reduces retained cash.\""),
("Payout Ratio", "股利發放率", "股利／盈餘。", "配息水準。", "\"A 40% payout ratio leaves room for reinvestment.\""),
("Retention Ratio", "盈餘保留率", "1−發放率，盈餘再投資比例。", "成長模型。", "\"Sustainable growth depends on the retention ratio and ROE.\""),
("Stable Dividend Policy", "穩定股利政策", "維持穩定或穩定成長的每股股利。", "投資人偏好。", "\"A stable dividend policy appeals to income-oriented shareholders.\""),
("Residual Dividend Model", "剩餘股利模型", "先滿足權益融資需求，剩餘才發股利。", "波動配息。", "\"Under a residual dividend model, payouts swing with the capex cycle.\""),
("Dividend Smoothness", "股利平滑", "公司傾向平滑股利、避免劇烈變動。", "訊號。", "\"Managers value dividend smoothness to avoid negative signals.\""),
("Share Repurchase", "庫藏股／買回", "公司買回自家股票回饋現金。", "彈性分配。", "\"A share repurchase can be more tax-efficient for some investors.\""),
("Dividend Coverage", "股利覆蓋", "盈餘或自由現金流對股利的覆蓋倍數。", "配息永續。", "\"Weak dividend coverage raises cut risk.\""),
("Stock Dividend", "股票股利", "以額外股份形式發放的股利，非現金。", "資本化盈餘。", "\"A stock dividend increases shares outstanding without cash leaving the firm.\""),
("Stock Split", "股票分割", "增加股數、降低每股價格，權益總額不變。", "流動性、訊號。", "\"The 2-for-1 stock split made the shares more affordable to retail buyers.\""),
("Reverse Stock Split", "反向分割", "合併股數以提高每股價格。", "維持上市資格。", "\"A reverse stock split lifted the price above the exchange minimum.\""),
("Declaration Date", "宣告日", "董事會宣告將發股利的日期。", "負債確認。", "\"On the declaration date, the firm records a dividend payable.\""),
("Ex-Dividend Date", "除息日", "在此日或之後買進者無權取得該次股利。", "股價調整。", "\"The stock typically drops by about the dividend on the ex-dividend date.\""),
("Holder-of-Record Date", "基準日／登記日", "股東名冊認定有權領息的日期。", "股務。", "\"You must be on the books by the holder-of-record date to receive the dividend.\""),
("Payment Date", "發放日", "實際支付股利的日期。", "現金流出。", "\"Cash leaves the firm on the payment date.\""),
("Bird-in-the-Hand Theory", "一鳥在手理論", "主張投資人偏好確定股利勝過不確定資本利得。", "高配息溢價。", "\"Bird-in-the-hand theory argues dividends are valued more than risky growth.\""),
("Tax Preference Theory", "稅賦偏好理論", "若資本利得稅較優，投資人可能偏好低股利。", "客戶效應。", "\"Tax preference theory supports lower payouts when cap gains are favored.\""),
("Dividend Clientele Effect", "股利客戶效應", "不同稅負／偏好的投資人群聚於特定股利政策公司。", "政策改變衝擊。", "\"A sudden payout cut may upset the dividend clientele.\""),
("Dividend Signaling", "股利訊號", "股利增減向市場傳遞管理階層對前景的訊息。", "宣告效果。", "\"A surprise raise can be dividend signaling of stronger earnings.\""),
("Sustainable Growth Rate", "永續成長率", "不改變資本結構、不發新股下可達成長率：g=b×ROE。", "規劃。", "\"Sales growth above the sustainable growth rate needs external finance.\""),
("Internal Growth Rate", "內部成長率", "不對外融資（含不舉新債）下可達成長率。", "保守成長。", "\"The internal growth rate is lower than the sustainable growth rate.\""),
("External Financing Needed (EFN)", "外部融資需求", "成長導致資產增加超過自發融資與留存時的缺口。", "財務規劃。", "\"EFN turns positive when growth outpaces retained earnings capacity.\""),
("Pro Forma Financial Statements", "預估財務報表", "依假設推估的未來資產負債表與損益表。", "規劃模型。", "\"Build pro forma financial statements under the base and downside cases.\""),
("Percent-of-Sales Method", "銷售百分比法", "假設若干項目隨銷售固定比例變動的規劃法。", "快速預估。", "\"Using the percent-of-sales method, inventory is set at 15% of sales.\""),
("Spontaneous Liabilities", "自發性負債", "隨銷售自動增加的負債，如應付款。", "EFN。", "\"Spontaneous liabilities finance part of the asset growth automatically.\""),
("Levered Free Cash Flow", "槓桿自由現金流", "扣除利息等債權現金流後屬股東的自由現金流概念（定義依语境）。", "股權評價。", "\"Discount levered free cash flow at the cost of equity in an equity model.\""),
("Unlevered Free Cash Flow", "未槓桿自由現金流", "對全部資本提供者的自由現金流（FCFF）。", "企業評價。", "\"Unlevered free cash flow is discounted at WACC in an enterprise DCF.\""),
("FCFF", "公司自由現金流", "支付債權人與股東之前、對公司整體的自由現金流。", "DCF。", "\"FCFF equals EBIT(1−t)+D&A−capex−ΔNWC, with adjustments as needed.\""),
("FCFE", "股權自由現金流", "支付債權義務後屬於股東的自由現金流。", "股權DCF。", "\"FCFE is the cash available for dividends and buybacks.\""),
("ROIC", "投入資本報酬率", "稅後營業利潤相對投入資本的報酬。", "價值創造。", "\"ROIC above WACC indicates economic value creation.\""),
("ROE", "股東權益報酬率", "淨利／權益，衡量股東報酬。", "杜邦分析。", "\"Leverage boosted ROE but also financial risk.\""),
("ROA", "資產報酬率", "淨利／資產，衡量資產運用效率。", "獲利能力。", "\"ROA declined as the asset base grew faster than earnings.\""),
("DuPont Analysis", "杜邦分析", "將 ROE 拆成利潤率、週轉與槓桿等因子。", "績效診斷。", "\"DuPont analysis shows the ROE drop came from margin compression.\""),
("Interest Coverage Ratio", "利息保障倍數", "EBIT／利息，衡量付息能力。", "信用風險。", "\"Interest coverage below 2× worries creditors.\""),
("Debt-to-Equity", "負債權益比", "負債相對股東權益的槓桿比率。", "資本結構。", "\"Debt-to-equity rose after the leveraged acquisition.\""),
("Debt-to-Capital", "負債資本比", "負債／（負債＋權益）。", "槓桿。", "\"Target debt-to-capital is 30% for the WACC weights.\""),
("Net Debt", "淨負債", "有息負債減現金及約當現金。", "企業價值。", "\"Enterprise value uses net debt, not gross debt alone.\""),
("Credit Rating", "信用評等", "評等機構對發行人／債務信用風險的意見。", "資金成本。", "\"A downgrade raised the company's credit spread overnight.\""),
("Covenant", "財務限制條款", "借款合約中限制借款人行為或要求維持財務比率的條款。", "債券、貸款。", "\"Breaching the leverage covenant could accelerate the loan.\""),
("Affirmative Covenant", "積極條款", "要求借款人必須做的事項，如按時報表、投保。", "貸款合約。", "\"An affirmative covenant requires quarterly financial reporting.\""),
("Negative Covenant", "消極條款", "限制借款人不得做的事項，如限制加貸、股利。", "債權保護。", "\"The negative covenant caps additional secured debt.\""),
("Merger", "合併", "兩家公司依法合併為一家。", "策略成長。", "\"The merger aims to cut overlapping costs in distribution.\""),
("Acquisition", "收購", "一家公司取得另一家控制權。", "M&A。", "\"The acquisition was financed with a mix of cash and stock.\""),
("Horizontal Merger", "水平合併", "同業競爭者之間的合併。", "市占。", "\"The horizontal merger increased concentration in the industry.\""),
("Vertical Merger", "垂直合併", "供應鏈上下游之間的合併。", "整合。", "\"The vertical merger secured raw-material supply.\""),
("Conglomerate Merger", "多角化合併", "不同產業公司的合併。", "多角化。", "\"Investors questioned the logic of the conglomerate merger.\""),
("Synergy", "綜效", "合併後價值大於分開價值的增益。", "交易論述。", "\"Cost synergy estimates drove most of the bid premium.\""),
("Hostile Takeover", "敵意併購", "未獲目標公司董事會支持的收購。", "防禦策略。", "\"Poison pills are designed to deter a hostile takeover.\""),
("Poison Pill", "毒丸", "使敵意收購成本大增的股東權益計畫。", "接管防禦。", "\"The board adopted a poison pill after the stake disclosure.\""),
("Leveraged Buyout (LBO)", "槓桿收購", "主要以負債融資收購公司的交易。", "私募股權。", "\"The LBO loaded the balance sheet with new debt.\""),
("Management Buyout (MBO)", "管理層收購", "現有管理階層參與收購自家公司。", "私有化。", "\"In the MBO, managers rolled equity into the new holding company.\""),
("Spin-Off", "分割上市／分拆", "將子公司股份分配給母公司股東使其獨立。", "專注本業。", "\"The spin-off unlocked value in the noncore division.\""),
("Divestiture", "資產出售／處分", "出售業務或資產。", "重組。", "\"The divestiture proceeds will deleverage the parent.\""),
]