# CFA L1 Derivatives ~150

TERMS = [
    ("derivative", "衍生性金融商品", "價值取決於標的資產、利率或指數表現的金融契約。", "用於避險、投機、套利或調整投資組合曝險。", "A derivative derives its value from an underlying asset."),
    ("underlying", "標的資產", "決定衍生性商品價值的資產、利率、指數或其他變數。", "分析契約風險時，先確認標的及其價格行為。", "The stock index is the underlying of the futures contract."),
    ("long position", "多頭部位", "因標的價格上漲而通常受益的契約部位。", "預期價格上升時可建立多頭部位。", "The investor takes a long position in gold futures."),
    ("short position", "空頭部位", "因標的價格下跌而通常受益的契約部位。", "預期價格下降或欲避險時可建立空頭部位。", "The producer takes a short position to hedge falling prices."),
    ("forward contract", "遠期契約", "雙方約定於未來日期以預定價格交易標的的場外契約。", "適合依交易雙方需求客製數量、日期與標的。", "The firm enters a forward contract to buy euros in three months."),
    ("forward price", "遠期價格", "使遠期契約初始價值為零的未來交割價格。", "以現貨價格、持有成本及收益估算公平遠期價格。", "The forward price is set so the contract initially has zero value."),
    ("delivery price", "交割價格", "遠期契約中雙方約定於到期時支付的固定價格。", "契約成立後交割價格固定，但契約價值會隨市場變動。", "The delivery price remains fixed throughout the contract."),
    ("forward commitment", "遠期承諾", "雙方皆負有在未來履約義務的衍生性契約。", "遠期、期貨與交換均屬遠期承諾。", "Both parties must perform under a forward commitment."),
    ("futures contract", "期貨契約", "在集中市場交易且條款標準化的遠期承諾。", "可用於以高流動性方式管理市場價格風險。", "The portfolio manager sells index futures on an exchange."),
    ("futures price", "期貨價格", "市場對標準化期貨契約未來交割價格的報價。", "每日結算使期貨價格與部位損益持續更新。", "The futures price changes as market expectations change."),
    ("standardization", "契約標準化", "交易所統一規定契約規模、品質、到期月與交割方式。", "標準化可提升期貨與選擇權的流動性。", "Standardization makes exchange-traded contracts easier to trade."),
    ("contract size", "契約規模", "每一口衍生性契約代表的標的數量或名目本金。", "將報價變動乘以契約規模可計算損益。", "Each futures contract represents one thousand barrels."),
    ("expiration date", "到期日", "衍生性契約權利或義務終止或結算的日期。", "評價時需考量距到期日的剩餘期間。", "The option expires on the third Friday of June."),
    ("settlement date", "結算日", "契約雙方交換現金或標的以完成履約的日期。", "遠期的結算日通常與到期日一致或緊接其後。", "Cash is exchanged on the settlement date."),
    ("physical settlement", "實物交割", "到期時實際交付標的並收取約定價款的結算方式。", "商品及部分金融契約可採實物交割。", "The bond futures contract permits physical settlement."),
    ("cash settlement", "現金結算", "到期時僅支付契約價格與結算價格差額的方式。", "無法實際交付的指數契約通常採現金結算。", "The index option is settled in cash."),
    ("over-the-counter market", "店頭市場", "交易雙方直接或透過交易商協商契約的市場。", "適合客製化交易，但須管理交易對手風險。", "The customized swap trades in the over-the-counter market."),
    ("exchange-traded derivative", "交易所交易衍生品", "透過集中交易所買賣並由結算機構處理的標準化契約。", "通常具有透明報價、保證金制度及較低交易對手風險。", "Exchange-traded derivatives have standardized terms."),
    ("clearinghouse", "結算所", "介於買賣雙方之間並保證契約履行的機構。", "透過中央結算降低雙邊違約曝險。", "The clearinghouse becomes the counterparty to every trade."),
    ("central counterparty", "中央交易對手", "承接每筆集中結算交易買方與賣方對手角色的機構。", "以淨額結算、保證金及違約基金控制風險。", "A central counterparty reduces bilateral credit exposure."),
    ("counterparty risk", "交易對手風險", "契約另一方無法履行付款或交割義務的可能性。", "店頭契約評價與風險管理須納入此風險。", "Counterparty risk is greater in an uncleared forward."),
    ("credit risk", "信用風險", "因交易對手信用惡化或違約而遭受損失的風險。", "可透過擔保品、淨額結算與信用衍生品管理。", "Collateral can reduce credit risk in a swap."),
    ("netting", "淨額結算", "將同一交易對手間多筆應收與應付合併為單一淨額。", "可降低結算金額及交易對手曝險。", "Netting reduces the amount exchanged between counterparties."),
    ("collateral", "擔保品", "為確保契約履行而提供的現金或合格資產。", "店頭衍生品可依市值變動追加或退還擔保品。", "The dealer posts collateral when the swap loses value."),
    ("initial margin", "原始保證金", "建立期貨部位時須存入保證金帳戶的初始金額。", "用於吸收每日結算期間可能發生的損失。", "The trader deposits initial margin before opening the position."),
    ("maintenance margin", "維持保證金", "保證金帳戶必須維持的最低餘額。", "餘額低於此水準時會觸發追繳通知。", "The account falls below the maintenance margin level."),
    ("variation margin", "變動保證金", "依每日市價變動收付以恢復保證金水準的款項。", "反映期貨部位逐日結算產生的損益。", "Variation margin is paid after an adverse price move."),
    ("margin call", "保證金追繳", "保證金餘額不足時要求交易人補足資金的通知。", "未及時補繳可能導致部位被強制平倉。", "The broker issues a margin call after a large loss."),
    ("mark-to-market", "逐日盯市", "按當日結算價格重新計算契約價值與損益的程序。", "期貨通常每日將損益計入保證金帳戶。", "Futures positions are marked to market every day."),
    ("settlement price", "結算價格", "交易所用來計算每日損益與保證金的官方價格。", "不一定等於當日最後一筆成交價。", "The exchange publishes the daily settlement price."),
    ("price limit", "價格限制", "交易所規定契約單日可上漲或下跌的最大幅度。", "市場觸及限制時可能暫停或限制交易。", "Trading stops when the futures contract reaches its price limit."),
    ("open interest", "未平倉量", "尚未平倉、交割或到期的契約總數。", "可用來觀察市場參與程度與流動性。", "Open interest rises when new positions are created."),
    ("trading volume", "成交量", "特定期間內完成交易的契約口數。", "成交量高通常代表市場交易較活躍。", "Trading volume surged before the contract expired."),
    ("basis", "基差", "現貨價格與期貨價格之間的差額，常定義為現貨減期貨。", "避險成效取決於基差於避險期間的變動。", "The basis narrows as the futures contract approaches expiration."),
    ("basis risk", "基差風險", "現貨與避險工具價格未按預期同步變動的風險。", "交叉避險或到期日不匹配時尤其重要。", "Basis risk remains because the hedge is not perfect."),
    ("convergence", "價格收斂", "期貨價格在到期時趨近現貨價格的關係。", "無套利機制促使兩者於交割時一致。", "Futures and spot prices converge at expiration."),
    ("contango", "正價差市場", "期貨價格高於現貨價格，且較遠期契約通常更昂貴的市場狀態。", "常見於持有成本較高或便利收益較低的商品。", "Oil futures are in contango when later contracts cost more."),
    ("backwardation", "逆價差市場", "期貨價格低於現貨價格，或較遠期契約價格較低的市場狀態。", "可能反映高便利收益或短期供給緊張。", "The commodity market is in backwardation."),
    ("cost of carry", "持有成本", "持有標的至未來日期所產生的融資、儲存及其他淨成本。", "無套利遠期價格通常由現貨價格加淨持有成本決定。", "Storage and financing are components of cost of carry."),
    ("storage cost", "儲存成本", "持有實體商品期間發生的倉儲、保險及相關費用。", "儲存成本提高通常會提高商品遠期價格。", "Higher storage costs increase the fair forward price."),
    ("convenience yield", "便利收益", "實際持有商品存貨所帶來、但契約持有人無法取得的非現金利益。", "便利收益提高會降低商品的理論遠期價格。", "A supply shortage can increase the convenience yield."),
    ("income yield", "收益率", "標的資產於持有期間提供的股利或其他收入占價格的比率。", "收益率會降低持有標的的淨成本及公平遠期價格。", "A higher income yield lowers the equity forward price."),
    ("cash-and-carry arbitrage", "現貨持有套利", "當遠期價格過高時買進現貨並放空遠期以鎖定利潤。", "用來恢復遠期價格與持有成本間的無套利關係。", "The trader buys the asset and sells an overpriced forward."),
    ("reverse cash-and-carry arbitrage", "反向現貨持有套利", "當遠期價格過低時放空現貨並買進遠期的套利策略。", "前提是標的可借券且交易成本不抵銷利潤。", "The arbitrageur shorts the asset and buys the underpriced forward."),
    ("no-arbitrage principle", "無套利原則", "相同未來現金流的投資組合應具有相同當前價值。", "為衍生性商品定價的核心基礎。", "No-arbitrage pricing equates portfolios with identical payoffs."),
    ("law of one price", "一價法則", "相同資產或現金流在有效市場中應有相同價格。", "價格差異會吸引套利交易直至差距消失。", "The law of one price rules out persistent price differences."),
    ("replication", "複製策略", "以其他資產組合建立與目標衍生品相同的未來現金流。", "複製組合成本可用來推導衍生品公平價值。", "A stock and bond portfolio can replicate an option payoff."),
    ("arbitrage", "套利", "不需淨投入且無損失風險，卻可獲得正收益的交易。", "定價模型假設可辨識並消除套利機會。", "The price discrepancy creates an arbitrage opportunity."),
    ("risk-free rate", "無風險利率", "理論上沒有違約風險之借貸工具的報酬率。", "用於遠期定價、選擇權評價與現金流折現。", "The model discounts the payoff at the risk-free rate."),
    ("present value", "現值", "將未來現金流依適當折現率換算至今日的價值。", "遠期交割價格及交換固定給付均需折現。", "The present value of the payment is less than its face amount."),
    ("forward value", "遠期契約價值", "既有遠期契約在評價日對持有人的淨經濟價值。", "比較原交割價格與目前公平遠期價格後折現計算。", "The forward gains value after the market forward price rises."),
    ("long forward payoff", "遠期多頭損益", "到期標的價格減去契約交割價格的結果。", "標的到期價格高於交割價格時多頭獲利。", "The long forward payoff equals spot price minus delivery price."),
    ("short forward payoff", "遠期空頭損益", "契約交割價格減去到期標的價格的結果。", "標的到期價格低於交割價格時空頭獲利。", "The short forward benefits when the asset price falls."),
    ("hedging", "避險", "建立抵銷部位以降低既有或預期曝險的策略。", "企業可用衍生品穩定成本、收入或投資組合價值。", "The airline uses futures for hedging fuel costs."),
    ("speculation", "投機", "承擔市場風險以期從預期價格變動獲利。", "衍生品槓桿可放大投機收益與損失。", "The trader buys calls as a speculation on higher prices."),
    ("cross hedge", "交叉避險", "使用與曝險資產不同但高度相關的契約進行避險。", "標的無適合契約時可採用，但會產生基差風險。", "The firm uses heating oil futures as a cross hedge."),
    ("hedge ratio", "避險比率", "避險部位規模相對於被避險曝險規模的比例。", "選擇適當比率可降低組合價值波動。", "The manager adjusts the hedge ratio to reduce risk."),
    ("short hedge", "空頭避險", "以放空期貨或遠期抵銷未來出售資產的價格下跌風險。", "生產者或資產持有人常採用此策略。", "A farmer uses a short hedge before selling the crop."),
    ("long hedge", "多頭避險", "以買進期貨或遠期抵銷未來購買資產的價格上漲風險。", "預計需要原料或外幣的企業可採用。", "A manufacturer uses a long hedge for future copper purchases."),
    ("rollover risk", "轉倉風險", "短期契約到期後轉入新契約時條件不利的風險。", "長期曝險以連續短期契約避險時須考量。", "Rollover risk arises when the hedge must be renewed."),
    ("swap", "交換契約", "雙方於一段期間交換一系列現金流的場外契約。", "常用於管理利率、貨幣、股權或商品曝險。", "The companies enter a swap to exchange cash flows."),
    ("swap rate", "交換固定利率", "使交換契約初始價值為零的固定端利率。", "由相應到期日的折現因子與浮動利率預期推導。", "The swap rate makes the contract value zero at inception."),
    ("notional principal", "名目本金", "計算交換或其他衍生品現金流所依據的參考金額。", "多數利率交換不實際交換名目本金。", "Interest payments are based on the notional principal."),
    ("interest rate swap", "利率交換", "雙方依同一貨幣名目本金交換固定與浮動利息的契約。", "可將固定利率負債轉換為浮動利率曝險，反之亦然。", "The borrower pays fixed and receives floating in the swap."),
    ("fixed-rate payer", "固定利率支付方", "在利率交換中支付固定利息並收取浮動利息的一方。", "通常受益於市場利率上升。", "The fixed-rate payer gains when floating rates rise."),
    ("floating-rate payer", "浮動利率支付方", "在利率交換中支付浮動利息並收取固定利息的一方。", "通常受益於市場利率下降。", "The floating-rate payer prefers lower reference rates."),
    ("reference rate", "參考利率", "用來重設浮動端現金流的市場利率指標。", "每個重設日依參考利率決定下一期付款。", "The floating payment is linked to a reference rate."),
    ("reset date", "利率重設日", "決定下一計息期間浮動利率的日期。", "重設通常發生於付款期初。", "The coupon rate is determined on the reset date."),
    ("payment date", "付款日", "交換或其他契約現金流實際支付的日期。", "評價時將各付款日淨現金流折現。", "The net swap payment occurs on each payment date."),
    ("swap tenor", "交換期限", "交換契約從生效日至最終到期日的總期間。", "期限會影響固定交換利率及利率敏感度。", "The swap has a five-year tenor."),
    ("plain vanilla swap", "標準型交換", "結構單純且條款慣例化的固定對浮動利率交換。", "常作為理解交換定價與評價的基本形式。", "A plain vanilla swap exchanges fixed and floating payments."),
    ("currency swap", "貨幣交換", "雙方以不同貨幣交換本金及利息現金流的契約。", "可管理長期外匯與跨國融資風險。", "The firms exchange dollar payments for euro payments."),
    ("equity swap", "股權交換", "一方支付股票或指數報酬，另一方支付固定或浮動利率的交換。", "可在不直接持有股票下取得或轉移股權曝險。", "The fund receives the equity index return through a swap."),
    ("commodity swap", "商品交換", "以商品價格相關現金流交換固定或其他付款的契約。", "生產者與消費者可用來穩定商品收入或成本。", "The airline pays a fixed fuel price through a commodity swap."),
    ("total return swap", "總報酬交換", "一方支付參考資產的利息、價格變動等總報酬，換取融資型付款。", "可移轉資產經濟曝險而不移轉法律所有權。", "The receiver gains exposure through a total return swap."),
    ("swap valuation", "交換評價", "計算交換剩餘收取端與支付端現值之差。", "既有交換價值會隨利率、匯率或標的價格變動。", "Swap valuation compares the present values of both legs."),
    ("swap leg", "交換端", "交換契約中一系列同類型支付現金流的一側。", "分別評價固定端與浮動端後求其差額。", "The fixed leg is valued as a series of bond-like payments."),
    ("forward rate agreement", "遠期利率協議", "雙方約定未來期間適用利率並以現金差額結算的契約。", "借款人可鎖定未來借款利率。", "The borrower uses an FRA to lock in a future rate."),
    ("FRA buyer", "遠期利率協議買方", "在遠期利率協議中支付固定利率並收取浮動利率的一方。", "預期利率上升或欲避險未來借款成本者可買入。", "The FRA buyer benefits when the reference rate exceeds the contract rate."),
    ("FRA seller", "遠期利率協議賣方", "在遠期利率協議中收取固定利率並支付浮動利率的一方。", "預期利率下降或欲避險未來投資收益者可賣出。", "The FRA seller benefits when market rates decline."),
    ("option", "選擇權", "賦予買方在期限內按履約價買入或賣出標的之權利的契約。", "買方具有權利而非義務，賣方承擔履約義務。", "An option gives its owner a right without an obligation."),
    ("contingent claim", "或有請求權", "僅在特定事件或狀態發生時產生給付的衍生性商品。", "選擇權與信用衍生品均可具有或有給付。", "The payoff of a contingent claim depends on a future event."),
    ("call option", "買權", "賦予持有人按履約價買入標的的權利。", "預期標的上漲或欲限制買入成本時使用。", "The investor buys a call on the stock."),
    ("put option", "賣權", "賦予持有人按履約價賣出標的的權利。", "可用來從價格下跌獲利或保護持有部位。", "The shareholder buys a put for downside protection."),
    ("option buyer", "選擇權買方", "支付權利金以取得選擇權權利的一方。", "最大損失通常限於已支付權利金。", "The option buyer pays the premium upfront."),
    ("option writer", "選擇權賣方", "收取權利金並於買方行權時負有履約義務的一方。", "可能承擔重大損失，通常須繳納保證金。", "The option writer must perform if the option is exercised."),
    ("strike price", "履約價格", "選擇權持有人買入或賣出標的的約定價格。", "用來判斷選擇權價內程度及到期損益。", "The call has a strike price of fifty dollars."),
    ("option premium", "選擇權權利金", "買方為取得選擇權而支付給賣方的價格。", "由內含價值與時間價值構成。", "The buyer pays an option premium of three dollars."),
    ("exercise", "行使選擇權", "持有人要求依契約履約價格進行交易的行為。", "是否行權取決於行權價值及選擇權類型。", "The holder exercises the call before it expires."),
    ("assignment", "履約指派", "選擇權賣方被指定必須履行買方行權要求的程序。", "被指派的買權賣方通常須交付標的。", "The call writer receives an assignment notice."),
    ("American option", "美式選擇權", "可於到期日或之前任何允許日期行使的選擇權。", "提前行權彈性使其價值不低於相同條件歐式選擇權。", "An American option may be exercised before expiration."),
    ("European option", "歐式選擇權", "僅可於到期日行使的選擇權。", "基本定價關係常以歐式選擇權為前提。", "A European option can be exercised only at expiration."),
    ("Bermudan option", "百慕達式選擇權", "僅可在契約指定的若干日期行使的選擇權。", "其行權彈性介於美式與歐式之間。", "A Bermudan option is exercisable on specified dates."),
    ("intrinsic value", "內含價值", "選擇權立即行使可取得的價值，最低為零。", "買權為現價減履約價的正值部分，賣權則相反。", "The in-the-money call has positive intrinsic value."),
    ("time value", "時間價值", "選擇權價格超過其內含價值的部分。", "剩餘期間越長與波動率越高通常使時間價值增加。", "The option premium includes substantial time value."),
    ("moneyness", "價內外程度", "描述標的價格相對於履約價格的位置。", "分為價內、價平及價外。", "Moneyness compares the spot price with the strike price."),
    ("in-the-money", "價內", "立即行使具有正內含價值的選擇權狀態。", "買權在現價高於履約價時為價內。", "The call is in the money because the stock exceeds the strike."),
    ("at-the-money", "價平", "標的價格約等於履約價格的選擇權狀態。", "價平選擇權通常對波動率與時間變化較敏感。", "The option is at the money when spot equals strike."),
    ("out-of-the-money", "價外", "立即行使不具正內含價值的選擇權狀態。", "價外選擇權的價格完全來自時間價值。", "The put is out of the money because spot exceeds strike."),
    ("call payoff", "買權到期給付", "到期標的價格減履約價格的正值部分。", "買權持有人只在標的高於履約價時行權。", "The call payoff is the greater of zero and spot minus strike."),
    ("put payoff", "賣權到期給付", "履約價格減到期標的價格的正值部分。", "賣權持有人只在標的低於履約價時行權。", "The put payoff is the greater of zero and strike minus spot."),
    ("breakeven price", "損益兩平價格", "選擇權策略到期總損益為零時的標的價格。", "買入買權的損益兩平點通常為履約價加權利金。", "The call buyer breaks even above the strike by the premium."),
    ("maximum loss", "最大損失", "某衍生品部位在最不利情境下可能承受的最高損失。", "買入選擇權的最大損失通常為權利金。", "The maximum loss for a long call is the premium paid."),
    ("covered call", "掩護性買權", "持有標的同時賣出該標的買權的策略。", "可增加權利金收入，但限制標的上漲利益。", "The investor writes a covered call against owned shares."),
    ("protective put", "保護性賣權", "持有標的同時買入賣權以限制下檔損失的策略。", "類似為股票部位購買價格保險。", "A protective put establishes a floor for the stock value."),
    ("fiduciary call", "受託買權組合", "歐式買權加上到期值等於履約價的無風險債券。", "與同履約價及到期日的保護性賣權具有相同到期給付。", "A fiduciary call combines a call with a risk-free bond."),
    ("put-call parity", "買賣權平價", "相同標的、履約價與到期日之歐式買權、賣權、股票及債券間的無套利關係。", "可用來推導選擇權價格或辨識套利機會。", "Put-call parity links calls, puts, stock, and a risk-free bond."),
    ("synthetic long stock", "合成股票多頭", "以買入買權、賣出賣權及適當債券部位複製股票多頭。", "用於理解買賣權平價與建立替代曝險。", "A long call and short put can create synthetic long stock exposure."),
    ("synthetic call", "合成買權", "以股票、賣權及借貸部位複製買權給付的組合。", "當實際買權定價偏離時可用於套利比較。", "The portfolio replicates a call without buying one."),
    ("synthetic put", "合成賣權", "以買權、債券及股票空頭複製賣權給付的組合。", "可由買賣權平價重新排列推導。", "A synthetic put has the same payoff as an actual put."),
    ("lower bound for a call", "買權價格下限", "買權價格不得低於零及現貨減履約價現值兩者中的較大者。", "若價格低於下限便可能產生套利。", "The call price cannot fall below its no-arbitrage lower bound."),
    ("lower bound for a put", "賣權價格下限", "歐式賣權價格不得低於零及履約價現值減現貨兩者中的較大者。", "用來檢查市場報價是否符合無套利條件。", "The European put must respect its lower price bound."),
    ("upper bound for a call", "買權價格上限", "買權價格通常不得超過標的現貨價格。", "超過上限時直接買進標的會優於買權。", "A call cannot be worth more than the underlying stock."),
    ("upper bound for a put", "賣權價格上限", "歐式賣權價格不得超過履約價格的現值。", "此限制來自賣權最大到期給付。", "A European put cannot exceed the present value of its strike."),
    ("binomial model", "二項樹模型", "假設每期標的價格只上漲或下跌並逐期評價選擇權的模型。", "可透過複製組合或風險中立機率計算價值。", "The binomial model values the option over discrete time steps."),
    ("up factor", "上漲因子", "二項樹中標的價格於一期間上漲的乘數。", "與下跌因子共同建立未來價格節點。", "The up factor determines the higher stock price node."),
    ("down factor", "下跌因子", "二項樹中標的價格於一期間下跌的乘數。", "用於計算下方節點及選擇權給付。", "The down factor determines the lower stock price node."),
    ("risk-neutral probability", "風險中立機率", "使標的期望報酬等於無風險利率的定價機率。", "它是評價工具，不一定代表真實事件機率。", "Risk-neutral probability is used to price the option."),
    ("risk-neutral valuation", "風險中立評價", "以風險中立機率求期望給付並按無風險利率折現的方法。", "可簡化衍生品無套利定價。", "Risk-neutral valuation discounts the expected payoff."),
    ("delta", "德爾塔", "衍生品價值對標的價格小幅變動的敏感度。", "可用來估計價格變化或建立德爾塔避險。", "A call with a delta of 0.6 gains about 0.6 per unit rise."),
    ("delta hedge", "德爾塔避險", "以標的資產部位抵銷選擇權德爾塔曝險的策略。", "因德爾塔會變動，通常需要動態再平衡。", "The dealer rebalances the delta hedge after the stock moves."),
    ("gamma", "伽瑪", "選擇權德爾塔對標的價格變動的敏感度。", "伽瑪高表示德爾塔避險需要更頻繁調整。", "Gamma measures how quickly delta changes."),
    ("vega", "維加", "選擇權價值對隱含波動率變動的敏感度。", "多數買入選擇權部位具有正維加。", "The option rises in value when volatility increases because vega is positive."),
    ("theta", "西塔", "選擇權價值對時間流逝的敏感度，其他條件不變。", "選擇權買方通常承受負時間耗損。", "Theta captures the option value lost as time passes."),
    ("rho", "柔", "選擇權價值對無風險利率變動的敏感度。", "長天期選擇權的利率敏感度通常較高。", "Rho measures sensitivity to a change in interest rates."),
    ("volatility", "波動率", "標的報酬變動程度的統計衡量。", "較高波動率通常提高買權與賣權價值。", "Higher volatility increases the value of both calls and puts."),
    ("historical volatility", "歷史波動率", "依標的過去報酬資料估計的波動程度。", "可作為風險分析或選擇權模型輸入的參考。", "Historical volatility is estimated from past returns."),
    ("implied volatility", "隱含波動率", "由市場選擇權價格反推的波動率。", "反映市場對未來波動及供需的綜合定價。", "Implied volatility is backed out from the market option price."),
    ("volatility smile", "波動率微笑", "不同履約價選擇權的隱含波動率呈曲線差異的現象。", "顯示市場價格不完全符合固定波動率假設。", "The volatility smile shows different implied volatilities across strikes."),
    ("time to expiration", "距到期時間", "從評價日至選擇權到期日的剩餘期間。", "期間越長通常使美式選擇權與多數歐式選擇權更有價值。", "More time to expiration generally increases option value."),
    ("early exercise", "提前行權", "在到期日前行使美式或其他可提前行權選擇權。", "須比較立即行權價值與保留選擇權的價值。", "Early exercise may be optimal for a deep in-the-money put."),
    ("dividend effect", "股利效果", "預期股利對股票價格及股票選擇權價值造成的影響。", "股利通常降低買權價值並提高賣權價值。", "A larger expected dividend tends to reduce call value."),
    ("Black-Scholes-Merton model", "布萊克－休斯－墨頓模型", "在特定假設下評價歐式選擇權的連續時間模型。", "以現價、履約價、期限、利率、波動率及收益率估值。", "The Black-Scholes-Merton model prices a European call."),
    ("credit derivative", "信用衍生性商品", "價值或給付取決於信用事件、信用利差或債務人信用狀況的契約。", "用於移轉或取得信用風險曝險。", "A credit derivative transfers default risk between parties."),
    ("credit default swap", "信用違約交換", "保護買方支付定期費用，保護賣方在信用事件發生時提供補償的契約。", "債券持有人可用其避險發行人違約風險。", "The bondholder buys a credit default swap for protection."),
    ("protection buyer", "信用保護買方", "支付信用違約交換權利金並於信用事件發生時獲得補償的一方。", "其經濟效果類似為信用曝險購買保險。", "The protection buyer pays a periodic CDS premium."),
    ("protection seller", "信用保護賣方", "收取信用違約交換費用並承擔信用事件損失的一方。", "取得信用風險曝險並可能須支付重大補償。", "The protection seller compensates the buyer after default."),
    ("CDS spread", "信用違約交換利差", "保護買方依名目本金定期支付的年化費率。", "利差上升通常表示市場認為信用風險增加。", "The CDS spread widens as the issuer becomes riskier."),
    ("credit event", "信用事件", "觸發信用衍生品給付的契約所定事件。", "可能包括破產、未付款或債務重整。", "Failure to pay is a common credit event."),
    ("reference entity", "參考實體", "信用違約交換所連結之債務人或發行人。", "其信用事件決定保護賣方是否須付款。", "The corporation is the reference entity in the CDS."),
    ("reference obligation", "參考債務", "用來界定信用事件或結算信用衍生品的特定債務工具。", "實物結算時可能交付符合條件的債券。", "The bond serves as the reference obligation."),
    ("recovery rate", "回收率", "違約後債權人可回收之價值占債權面額的比例。", "回收率越低，信用保護的潛在給付越高。", "A lower recovery rate increases loss given default."),
    ("loss given default", "違約損失率", "違約曝險中無法回收的比例，通常為一減回收率。", "用於估計信用違約交換的預期損失。", "Loss given default equals one minus the recovery rate."),
    ("cash settlement of CDS", "信用違約交換現金結算", "信用事件後由保護賣方支付面額與回收價值間差額。", "不需由買方實際交付債券。", "The CDS is cash settled after the credit event."),
    ("physical settlement of CDS", "信用違約交換實物結算", "保護買方交付合格債務，保護賣方支付其面額。", "給付實質上補償債務價值下降。", "The buyer delivers the defaulted bond in physical settlement."),
    ("default probability", "違約機率", "債務人在特定期間內發生違約的可能性。", "與回收率及折現因子共同影響信用保護價值。", "A higher default probability increases the CDS premium."),
    ("forward rate", "遠期利率", "由即期利率曲線推導、適用於未來期間的隱含利率。", "可用於遠期利率協議與利率交換定價。", "The forward rate is implied by current spot rates."),
    ("spot rate", "即期利率", "今日至特定到期日之零息現金流的年化利率。", "用來折現單筆未來現金流及推導遠期利率。", "The two-year spot rate discounts a payment in two years."),
    ("discount factor", "折現因子", "將特定未來日期一單位現金流換算為現值的乘數。", "交換評價需對每期現金流套用相應折現因子。", "The discount factor converts the future payment to present value."),
    ("zero-coupon bond", "零息債券", "期間內不付息並於到期支付面額的債券。", "常用來建立折現因子與複製選擇權現金流。", "A zero-coupon bond pays its face value at maturity."),
]
