# CFA L1 Economics ~120
TERMS = [
("Gross Domestic Product (GDP)", "國內生產毛額", "一定期間內一國境內生產的最終商品與服務市場價值總和。", "景氣與成長衡量。", "\"Real GDP growth slowed to 1.2% in the second quarter.\""),
("Nominal GDP", "名目GDP", "以當期價格計算的 GDP，含通膨影響。", "與實質比較。", "\"Nominal GDP rose, but much of that was inflation, not real output.\""),
("Real GDP", "實質GDP", "剔除物價變動後的 GDP，反映實際產量。", "成長分析。", "\"Real GDP is the better gauge of living-standards growth.\""),
("GDP Deflator", "GDP平減指數", "名目 GDP 相對實質 GDP 的物價指數。", "廣義通膨。", "\"The GDP deflator covers a broader basket than the CPI.\""),
("Gross National Product (GNP)", "國民生產毛額", "一國國民所擁有生產要素產出的總價值，含海外淨要素所得。", "與GDP差異。", "\"GNP exceeds GDP when citizens earn substantial income abroad.\""),
("National Income", "國民所得", "生產要素報酬加總等國民帳戶概念。", "所得面分析。", "\"National income accounts help reconcile output and income approaches.\""),
("Personal Income", "個人所得", "家計單位收到的所得。", "消費能力。", "\"Personal income growth supports consumer spending forecasts.\""),
("Disposable Income", "可支配所得", "稅後個人所得，可消費或儲蓄。", "消費函數。", "\"Higher taxes reduced disposable income this quarter.\""),
("Household Final Consumption", "家計最終消費", "家計對商品與服務的消費支出。", "需求組成。", "\"Household final consumption is the largest share of GDP in this economy.\""),
("Gross Capital Formation", "資本形成毛額", "投資於固定資本與存貨的支出。", "投資需求。", "\"Gross capital formation plunged when credit conditions tightened.\""),
("Government Spending", "政府支出", "政府對商品與服務的購買（轉移支付通常另計）。", "財政刺激。", "\"Government spending rose with the infrastructure package.\""),
("Net Exports", "淨出口", "出口減進口。", "外部需求。", "\"Net exports subtracted from GDP as imports surged.\""),
("Business Cycle", "景氣循環", "經濟活動圍繞長期趨勢的擴張與收縮波動。", "資產配置時點。", "\"Equity valuations often peak late in the business cycle.\""),
("Expansion", "擴張期", "產出、就業等上升的景氣階段。", "循環定位。", "\"During expansion, cyclical stocks usually outperform defensives.\""),
("Peak", "高峰", "擴張轉為收縮前的頂點。", "過熱警訊。", "\"Capacity utilization near the peak often precedes tighter policy.\""),
("Contraction / Recession", "收縮／衰退", "經濟活動顯著下降的階段；衰退常指持續收縮。", "風險資產。", "\"In a recession, credit spreads typically widen.\""),
("Trough", "谷底", "收縮結束、即將復甦的低點。", "逆向布局。", "\"Some investors accumulate equities near the trough.\""),
("Recovery", "復甦", "自谷底回升但仍可能低於潛在產出的階段。", "早期循環。", "\"Credit-sensitive sectors often lead in recovery.\""),
("Leading Indicator", "領先指標", "傾向先於整體經濟轉向的指標。", "預測轉折。", "\"The yield curve is a classic leading indicator of recession risk.\""),
("Coincident Indicator", "同時指標", "與經濟現況大致同步的指標。", "確認現況。", "\"Industrial production is a coincident indicator of activity.\""),
("Lagging Indicator", "落後指標", "傾向落後於經濟轉折的指標。", "確認循環。", "\"Unemployment is often a lagging indicator.\""),
("Potential GDP", "潛在GDP", "在充分就業、資源正常利用下可達的產出水準。", "產出缺口。", "\"Inflation pressure rises when actual GDP exceeds potential GDP.\""),
("Output Gap", "產出缺口", "實際產出與潛在產出之差。", "政策立場。", "\"A negative output gap supports easier monetary policy.\""),
("Unemployment Rate", "失業率", "失業人口佔勞動力的比例。", "勞動市場。", "\"The unemployment rate fell to 3.8%.\""),
("Labor Force", "勞動力", "就業加失業（正在求職）人口。", "參與率。", "\"The labor force shrank as participation declined.\""),
("Labor Force Participation Rate", "勞動參與率", "勞動力佔工作年齡人口比例。", "結構性勞動。", "\"Aging demographics are lowering the labor force participation rate.\""),
("Frictional Unemployment", "摩擦性失業", "轉換工作過程中的短暫失業。", "自然失業組成。", "\"Some frictional unemployment is normal in a healthy labor market.\""),
("Structural Unemployment", "結構性失業", "技能或地區錯配造成的較持久失業。", "再培訓政策。", "\"Automation can raise structural unemployment without reskilling.\""),
("Cyclical Unemployment", "循環性失業", "因景氣衰退導致的失業。", "穩定政策。", "\"Stimulus aims to reduce cyclical unemployment in a downturn.\""),
("Natural Rate of Unemployment", "自然失業率", "充分就業下仍存在的摩擦性與結構性失業水準。", "政策中性。", "\"Inflation may accelerate if unemployment falls far below its natural rate.\""),
("Underemployment", "低度就業", "工時不足或技能未充分運用的就業狀態。", "勞動寬鬆。", "\"Underemployment shows more slack than the headline jobless rate.\""),
("Inflation", "通膨", "一般物價水準持續上漲、貨幣購買力下降。", "實質報酬。", "\"Inflation eroded the real value of fixed coupon payments.\""),
("Deflation", "通縮", "一般物價水準持續下跌。", "債務實質負擔。", "\"Deflation increases the real burden of nominal debt.\""),
("Disinflation", "通膨減速", "通膨率下降但仍為正。", "政策成功。", "\"Disinflation allowed the central bank to pause rate hikes.\""),
("Hyperinflation", "惡性通膨", "極高且失控的通膨。", "貨幣崩潰。", "\"Hyperinflation destroys confidence in the local currency.\""),
("Stagflation", "停滯性通膨", "高通膨與經濟停滯／高失業並存。", "政策兩難。", "\"Stagflation leaves policymakers with painful trade-offs.\""),
("Consumer Price Index (CPI)", "消費者物價指數", "代表性消費籃物價變動的指數。", "通膨指標。", "\"Core CPI excludes food and energy to show underlying inflation.\""),
("Producer Price Index (PPI)", "生產者物價指數", "生產者出廠價格變動指數，常領先消費物價。", "成本推動。", "\"Rising PPI may feed into consumer inflation with a lag.\""),
("Core Inflation", "核心通膨", "剔除波動較大項目（如食品能源）的通膨。", "政策關注。", "\"The central bank emphasizes core inflation in its reaction function.\""),
("Demand-Pull Inflation", "需求拉動通膨", "總需求過旺推升物價。", "過熱經濟。", "\"Demand-pull inflation often appears late in expansions.\""),
("Cost-Push Inflation", "成本推動通膨", "生產成本上升推動物價。", "供給衝擊。", "\"Oil shocks can create cost-push inflation.\""),
("Money Supply", "貨幣供給", "經濟中可動用的貨幣總量，有 M1、M2 等層級。", "貨幣政策傳導。", "\"Rapid money supply growth can eventually pressure prices.\""),
("Monetary Policy", "貨幣政策", "央行透過利率、流動性等影響經濟的政策。", "利率路徑。", "\"Markets are pricing a shift in monetary policy next year.\""),
("Fiscal Policy", "財政政策", "政府透過支出與稅收影響經濟的政策。", "赤字、刺激。", "\"Expansionary fiscal policy widened the budget deficit.\""),
("Policy Rate", "政策利率", "央行設定、作為利率走廊核心的基準利率。", "資金成本。", "\"The policy rate hike immediately lifted money-market yields.\""),
("Open Market Operations", "公開市場操作", "央行買賣證券以調節銀行準備與利率。", "流動性管理。", "\"Open market operations drained excess reserves this week.\""),
("Reserve Requirement", "存款準備率", "銀行須對存款提列準備的比率。", "信用創造。", "\"Cutting the reserve requirement frees banks to lend more.\""),
("Discount Rate / Refinancing Rate", "貼現／再融資利率", "銀行向央行借貸的利率工具之一。", "最後貸款。", "\"Banks borrow at the discount rate when interbank markets seize up.\""),
("Quantitative Easing (QE)", "量化寬鬆", "央行大量購買資產以壓低長利率、提供流動性。", "零利率下限。", "\"Quantitative easing flattened the long end of the curve.\""),
("Quantitative Tightening (QT)", "量化緊縮", "縮減央行資產負債表、反向於 QE 的操作。", "流動性回收。", "\"Quantitative tightening removes duration from private balance sheets.\""),
("Neutral Rate of Interest", "中性利率", "既不刺激也不緊縮經濟的實質政策利率概念。", "政策鬆緊判斷。", "\"If the policy rate is above the neutral rate, policy is restrictive.\""),
("Taylor Rule", "泰勒法則", "依通膨缺口與產出缺口指引政策利率的經驗法則。", "政策基準。", "\"The Taylor rule suggested rates should be higher than the current setting.\""),
("Transmission Mechanism", "傳導機制", "政策利率變化影響支出、通膨的管道。", "政策滯後。", "\"The credit channel is part of the monetary transmission mechanism.\""),
("Liquidity Trap", "流動性陷阱", "利率已極低，貨幣寬鬆難以刺激需求的情況。", "政策失效。", "\"In a liquidity trap, QE may be used when rate cuts no longer work.\""),
("Crowding Out", "排擠效果", "政府借款推高利率、排擠私人投資的現象。", "財政擴張爭議。", "\"Large deficits may cause crowding out of private capex.\""),
("Automatic Stabilizer", "自動穩定機制", "無需新立法即隨景氣反向調節的財政機制，如失業給付。", "緩和循環。", "\"Unemployment benefits act as an automatic stabilizer in recessions.\""),
("Budget Deficit", "預算赤字", "政府支出大於收入。", "公債供給。", "\"A wider budget deficit increases government bond issuance.\""),
("Public Debt", "公共債務", "政府累積尚未償還的負債。", "永續性。", "\"Rising public debt raised concerns about long-run fiscal sustainability.\""),
("Supply-Side Policy", "供給面政策", "著重提升生產力與潛在產出的政策，如稅改、管制鬆綁。", "長期成長。", "\"Supply-side policy aims to raise potential GDP, not just demand.\""),
("Aggregate Demand (AD)", "總需求", "各物價水準下計劃總支出。", "AD-AS 分析。", "\"A rate cut shifts aggregate demand to the right.\""),
("Aggregate Supply (AS)", "總供給", "各物價水準下計劃總產出。", "供給衝擊。", "\"A negative supply shock shifts short-run aggregate supply left.\""),
("Short-Run Aggregate Supply", "短期總供給", "投入價格尚未完全調整時的供給曲線。", "短期波動。", "\"Sticky wages shape the slope of short-run aggregate supply.\""),
("Long-Run Aggregate Supply", "長期總供給", "對應潛在產出、垂直於產出軸的供給。", "長期成長。", "\"Long-run aggregate supply shifts with productivity and labor supply.\""),
("Keynesian View", "凱因斯觀點", "強調短期需求不足、價格僵固與財政／貨幣穩定政策角色。", "衰退應對。", "\"The Keynesian view supports stimulus when demand is deficient.\""),
("Classical / Neoclassical View", "古典／新古典觀點", "強調市場自我調整與長期供給面決定產出。", "政策無效論。", "\"A neoclassical view expects wages to adjust and restore full employment.\""),
("Monetarism", "貨幣主義", "強調貨幣供給對名目需求與通膨的關鍵角色。", "貨幣規則。", "\"Monetarism focuses on steady money growth to stabilize inflation.\""),
("Utility Theory", "效用理論", "以效用函數描述偏好與選擇的理論。", "消費決策。", "\"Under utility theory, consumers choose the affordable bundle that maximizes utility.\""),
("Indifference Curve", "無異曲線", "帶來相同效用的商品組合軌跡。", "偏好圖示。", "\"Higher indifference curves represent preferred bundles.\""),
("Budget Constraint", "預算限制", "在所得與價格下可負擔組合的邊界。", "相對價格。", "\"A price cut pivots the budget constraint outward for that good.\""),
("Income Effect", "所得效果", "價格變動透過實質所得變化影響需求量。", "需求分解。", "\"For normal goods, the income effect reinforces the substitution effect.\""),
("Substitution Effect", "替代效果", "相對價格變化導致以較便宜商品替代的效果。", "需求法則。", "\"The substitution effect always raises quantity demanded when own price falls.\""),
("Normal Good", "正常財", "所得上升需求增加的財貨。", "所得彈性。", "\"Restaurant meals are typically a normal good.\""),
("Inferior Good", "劣等財", "所得上升需求減少的財貨。", "消費升級。", "\"Instant noodles may be an inferior good as incomes rise.\""),
("Giffen Good", "季芬財", "所得效果強烈到使需求曲線向上斜的劣等財特例。", "理論特例。", "\"A Giffen good is rare; price rises can raise quantity demanded.\""),
("Price Elasticity of Demand", "需求價格彈性", "需求量對價格變動的敏感度。", "定價、稅負歸宿。", "\"High price elasticity of demand limits a firm's pricing power.\""),
("Income Elasticity of Demand", "需求所得彈性", "需求量對所得變動的敏感度。", "產業周期。", "\"Luxury goods have high income elasticity of demand.\""),
("Cross-Price Elasticity", "交叉價格彈性", "一物需求對另一物價格變動的敏感度。", "替代／互補。", "\"Positive cross-price elasticity indicates substitutes.\""),
("Accounting Profit", "會計利潤", "收入減會計成本（通常不含全部機會成本）。", "財報。", "\"Accounting profit ignores the opportunity cost of owner capital.\""),
("Economic Profit", "經濟利潤", "收入減顯性與隱性（機會）成本後的利潤。", "進退場。", "\"Zero economic profit means resources earn a normal return.\""),
("Normal Profit", "正常利潤", "剛好覆蓋機會成本、經濟利潤為零的報酬。", "長期均衡。", "\"In perfect competition, firms earn only normal profit in the long run.\""),
("Opportunity Cost", "機會成本", "為某選擇所放棄的次佳方案價值。", "資本預算。", "\"The opportunity cost of the project is the return on the next-best investment.\""),
("Marginal Cost", "邊際成本", "多生產一單位的額外成本。", "產量決策。", "\"Produce while price exceeds marginal cost in the short run if covering variable costs.\""),
("Marginal Revenue", "邊際收入", "多賣一單位的額外收入。", "定價。", "\"A monopolist sets output where marginal revenue equals marginal cost.\""),
("Economies of Scale", "規模經濟", "長期平均成本隨產量上升而下降。", "產業結構。", "\"Economies of scale favor larger plants in this industry.\""),
("Diseconomies of Scale", "規模不經濟", "長期平均成本隨產量過大而上升。", "組織過大。", "\"Diseconomies of scale appeared after the megamerger.\""),
("Perfect Competition", "完全競爭", "眾多小廠、同質產品、自由進出、價格接受者的市場。", "基準模型。", "\"In perfect competition, firms are price takers.\""),
("Monopolistic Competition", "獨占性競爭", "多數廠商、差異化產品、自由進出的市場。", "品牌競爭。", "\"Restaurants often operate under monopolistic competition.\""),
("Oligopoly", "寡占", "少數大廠相互依賴的市場。", "博弈、勾結。", "\"In an oligopoly, one firm's price cut can trigger retaliation.\""),
("Monopoly", "獨占", "單一賣方、高進入障礙的市場。", "定價力。", "\"A monopoly restricts output to raise price above marginal cost.\""),
("Nash Equilibrium", "納許均衡", "在他人策略既定下，無人想單獨改變策略的狀態。", "寡占賽局。", "\"Price wars can be a Nash equilibrium even if cooperation is better.\""),
("Prisoner's Dilemma", "囚犯困境", "個人理性導致集體較差結果的賽局結構。", "卡特爾穩定。", "\"OPEC faces a prisoner's dilemma when members consider cheating on quotas.\""),
("Price Discrimination", "差別取價", "對不同顧客收取不同價格以擷取剩餘。", "航空票價。", "\"Airlines use price discrimination based on booking flexibility.\""),
("Consumer Surplus", "消費者剩餘", "願付價格與實付價格之差的總和。", "福利分析。", "\"A tax wedge reduces consumer surplus.\""),
("Producer Surplus", "生產者剩餘", "實收價格與願售最低價格之差的總和。", "福利分析。", "\"Subsidies can increase producer surplus in the short run.\""),
("Deadweight Loss", "無謂損失", "因無效率配置導致的總剩餘損失。", "稅、獨占。", "\"The tariff created a deadweight loss in the domestic market.\""),
("Exchange Rate", "匯率", "一國貨幣以另一國貨幣表示的價格。", "外匯、換算。", "\"The exchange rate moved to 32 pesos per US dollar.\""),
("Nominal Exchange Rate", "名目匯率", "未調整物價差異的雙邊貨幣價格。", "市場報價。", "\"The nominal exchange rate appreciated after the rate hike.\""),
("Real Exchange Rate", "實質匯率", "調整相對物價後的匯率，衡量競爭力。", "貿易餘額。", "\"The real exchange rate appreciation hurt exporters' competitiveness.\""),
("Spot Exchange Rate", "即期匯率", "立即（或標準即期交割）兌換的匯率。", "即期外匯。", "\"We converted the dividend at today's spot exchange rate.\""),
("Forward Exchange Rate", "遠期匯率", "約定未來某日兌換的匯率。", "避險。", "\"Lock in the forward exchange rate to hedge next quarter's receivable.\""),
("Currency Appreciation", "貨幣升值", "一單位本幣可換得更多外幣。", "進口變便宜。", "\"Currency appreciation made imported equipment cheaper.\""),
("Currency Depreciation", "貨幣貶值", "一單位本幣可換得更少外幣。", "出口競爭力。", "\"Currency depreciation boosted tourism inflows.\""),
("Purchasing Power Parity (PPP)", "購買力平價", "匯率應使相同商品籃在兩國購買力趨於一致的理論。", "長期匯率。", "\"According to purchasing power parity, high-inflation currencies depreciate.\""),
("Absolute PPP", "絕對購買力平價", "匯率等於兩國物價水準之比。", "理論基準。", "\"Absolute PPP rarely holds exactly because of trade barriers and nontradables.\""),
("Relative PPP", "相對購買力平價", "匯率變動反映兩國通膨差異。", "通膨差額。", "\"Relative PPP links expected depreciation to the inflation differential.\""),
("Interest Rate Parity", "利率平價", "利差與遠期／預期即期匯率關係，防套利。", "外匯遠期定價。", "\"Interest rate parity explains why high-yield currencies trade at a forward discount.\""),
("Covered Interest Rate Parity", "拋補利率平價", "以遠期合約拋補匯率風險後，利差與遠期點數一致。", "外匯換匯。", "\"Covered interest rate parity prices the forward points off the interest differential.\""),
("Uncovered Interest Rate Parity", "未拋補利率平價", "利差應被預期匯率變動抵消（無遠期拋補）。", "利差交易。", "\"Uncovered interest rate parity is often violated—that's the carry trade puzzle.\""),
("Carry Trade", "利差交易", "借入低息貨幣、投資高息貨幣以賺利差的策略。", "外匯策略。", "\"The carry trade unwound sharply when volatility spiked.\""),
("Balance of Payments", "國際收支", "一國與外國經濟交易的系統紀錄。", "外部均衡。", "\"The balance of payments must balance in an accounting sense.\""),
("Current Account", "經常帳", "商品服務貿易、收益與單方移轉等。", "貿易失衡。", "\"A current account deficit means the country is a net borrower.\""),
("Capital / Financial Account", "資本／金融帳", "跨國資本流動與金融資產交易相關帳戶。", "資金流入。", "\"FDI inflows appear in the financial account.\""),
("Official Reserve Account", "官方準備帳", "央行外匯準備變動相關項目。", "干預。", "\"Intervention to defend the peg shows up via official reserves.\""),
("Fixed Exchange Rate", "固定匯率", "本幣釘住他幣或籃、由當局維持的制度。", "貨幣局、釘住。", "\"Under a fixed exchange rate, the central bank must defend the peg.\""),
("Floating Exchange Rate", "浮動匯率", "主要由市場供需決定的匯率制度。", "獨立貨幣政策。", "\"A floating exchange rate absorbs external shocks via the currency.\""),
("Managed Float", "管理浮動", "原則浮動但央行偶而干預的制度。", "中間制度。", "\"In a managed float, authorities lean against disorderly moves.\""),
("Currency Board", "貨幣局制度", "本幣發行須有外匯準備完全支持、匯率嚴格釘住。", "公信力安排。", "\"A currency board limits discretionary monetary policy.\""),
("Dollarization", "美元化", "正式採用外幣（常為美元）作為法償貨幣。", "主權貨幣放棄。", "\"Dollarization imports US monetary policy but removes seigniorage.\""),
("Impossible Trinity", "不可能三角", "無法同時擁有固定匯率、資本自由流動與獨立貨幣政策。", "政策選擇。", "\"The impossible trinity forced them to choose between the peg and rate autonomy.\""),
("Tariff", "關稅", "對進口課徵的稅。", "貿易政策。", "\"The new tariff raised domestic prices of steel.\""),
("Quota", "配額", "限制進口數量的措施。", "非關稅障礙。", "\"An import quota creates scarcity rents for license holders.\""),
("Export Subsidy", "出口補貼", "政府對出口提供的財務支持。", "貿易爭端。", "\"An export subsidy can trigger countervailing duties abroad.\""),
("Trading Bloc", "貿易區塊", "成員間降低貿易障礙的國家集團。", "區域整合。", "\"Joining the trading bloc boosted intra-regional supply chains.\""),
("Free Trade Area", "自由貿易區", "成員互免關稅但對外仍各自設障的安排。", "FTA。", "\"Rules of origin matter in a free trade area.\""),
("Customs Union", "關稅同盟", "自由貿易區加共同對外關稅。", "更深整合。", "\"A customs union requires a common external tariff.\""),
("Common Market", "共同市場", "關稅同盟加生產要素較自由流動。", "區域經濟。", "\"A common market allows freer movement of labor and capital.\""),
("Economic Union", "經濟同盟", "共同市場加協調／統一經濟政策。", "深度一體化。", "\"An economic union may eventually share a currency and fiscal rules.\""),
("Foreign Direct Investment (FDI)", "直接投資", "取得實質經營控制的跨國投資。", "長期資本。", "\"FDI in factories is stickier than portfolio inflows.\""),
("Portfolio Investment", "證券投資", "跨國買賣股票債券等、通常無經營控制。", "熱錢。", "\"Portfolio investment can reverse quickly in a risk-off episode.\""),
]