# CFA L1 Equity ~200

TERMS = [
    ("Equity security", "權益證券", "代表對企業淨資產與剩餘現金流之所有權請求權的證券。", "用於分析股東權利、風險與預期報酬。", "An equity security gives investors a residual claim on the company."),
    ("Common share", "普通股", "通常具有表決權並可按董事會決議收取股利的基本權益證券。", "用於評估一般股東的所有權與收益來源。", "Common shares usually carry voting rights."),
    ("Preference share", "特別股", "在股利與清算分配上通常優先於普通股的權益證券。", "用於比較固定收益特徵與權益特徵。", "Preference shares rank ahead of common shares for dividends."),
    ("Cumulative preference share", "累積特別股", "未支付的特別股股利會累積並須於普通股股利前補付。", "用於評估股利延遲支付對投資人的保障。", "Unpaid cumulative dividends must be paid before common dividends."),
    ("Non-cumulative preference share", "非累積特別股", "當期未宣告的股利不會累積至未來期間的特別股。", "用於辨識較弱的股利保障。", "A skipped non-cumulative dividend is not owed later."),
    ("Participating preference share", "參與特別股", "除固定股利外，還可依條款參與額外盈餘分配的特別股。", "用於分析上檔收益分享機制。", "Participating preference shares may receive an additional dividend."),
    ("Convertible preference share", "可轉換特別股", "可依約定比例轉換為普通股的特別股。", "用於評估轉換選擇權與股權稀釋。", "The investor converted the preference shares into common shares."),
    ("Callable preference share", "可贖回特別股", "發行公司可依條款在指定日期與價格買回的特別股。", "用於衡量投資人面臨的再投資風險。", "The issuer called the preference shares at par."),
    ("Putable preference share", "可回售特別股", "持有人可依條款要求發行公司以指定價格買回的特別股。", "用於評估持有人下檔保障。", "The put feature protects the preference shareholder."),
    ("Depository receipt", "存託憑證", "由存託銀行發行並代表外國公司股份的可交易憑證。", "用於跨境投資並降低直接交易障礙。", "A depository receipt allows local trading of foreign equity."),
    ("Sponsored depository receipt", "參與型存託憑證", "由外國公司配合存託銀行建立並通常承擔部分合規責任的存託憑證。", "用於區分發行人是否參與存託安排。", "The company sponsored the depository receipt program."),
    ("Unsponsored depository receipt", "非參與型存託憑證", "未由標的公司正式參與而由存託機構建立的存託憑證。", "用於評估資訊取得與投資人關係差異。", "An unsponsored receipt may offer less issuer communication."),
    ("American depository receipt", "美國存託憑證", "在美國市場交易並代表非美國公司股份的存託憑證。", "用於分析美國投資人持有海外股票的方式。", "The ADR trades in US dollars."),
    ("Global depository receipt", "全球存託憑證", "可在一個以上國際市場發行或交易的存託憑證。", "用於企業跨市場籌資與提高國際能見度。", "The GDR was listed in two international markets."),
    ("Public equity", "公開權益", "可在公開市場由廣泛投資人交易的公司權益。", "用於比較流動性、揭露與估值透明度。", "Public equity is traded on an organized market."),
    ("Private equity", "私募股權", "未在公開市場交易且通常由專業基金或少數投資人持有的權益。", "用於分析較低流動性與較長投資期間。", "Private equity investors often have a long investment horizon."),
    ("Venture capital", "創業投資", "對早期或成長初期企業提供資本的私募股權投資。", "用於評估高成長潛力與高失敗風險。", "Venture capital financed the startup's expansion."),
    ("Leveraged buyout", "槓桿收購", "以大量債務融資取得公司控制權的私募股權交易。", "用於分析財務槓桿、現金流與退出策略。", "The fund completed a leveraged buyout of the company."),
    ("Management buyout", "管理層收購", "由現任管理團隊主導收購企業控制權的交易。", "用於評估管理誘因與融資安排。", "The executives led a management buyout."),
    ("Growth capital", "成長資本", "向已建立營運模式的企業提供擴張資金之少數或控制性投資。", "用於支持產能、通路或市場擴張。", "Growth capital funded the company's new factories."),
    ("Initial public offering", "首次公開發行", "公司首次向公眾發售股份並通常申請上市的過程。", "用於分析發行定價、稀釋與上市成本。", "The company raised capital through an initial public offering."),
    ("Seasoned offering", "現金增資發行", "已上市公司再次向市場發行新股以籌集資本。", "用於評估新增供給與每股權益稀釋。", "The seasoned offering increased the number of shares outstanding."),
    ("Rights offering", "現金增資認股", "按持股比例給予既有股東優先認購新股權利的發行方式。", "用於維持原股東相對持股比例。", "Existing shareholders received rights to buy new shares."),
    ("Private placement", "私募", "向有限且合格的投資人非公開出售證券的籌資方式。", "用於比較較低發行成本與較低流動性。", "The issuer sold shares through a private placement."),
    ("Secondary market", "次級市場", "投資人彼此交易既有證券且發行人通常不取得資金的市場。", "用於分析價格發現與流動性。", "Investors trade outstanding shares in the secondary market."),
    ("Primary market", "初級市場", "發行人向投資人出售新證券以取得資金的市場。", "用於分析企業籌資與承銷流程。", "New shares are sold in the primary market."),
    ("Organized exchange", "集中交易所", "依正式規則提供上市、交易與監督服務的實體或電子市場。", "用於評估透明度與交易制度。", "The stock trades on an organized exchange."),
    ("Over-the-counter market", "櫃檯市場", "由交易商網路直接撮合而非集中於單一交易所的市場。", "用於分析分散交易與交易商報價。", "The security trades in the over-the-counter market."),
    ("Quote-driven market", "報價驅動市場", "由交易商提出買賣報價並以自有庫存提供流動性的市場。", "用於理解交易商作為交易對手的角色。", "Dealers supply liquidity in a quote-driven market."),
    ("Order-driven market", "委託驅動市場", "依投資人買賣委託的價格與時間優先順序撮合交易的市場。", "用於分析公開委託簿與價格形成。", "Orders interact directly in an order-driven market."),
    ("Brokered market", "經紀市場", "經紀人搜尋合適交易對手並協助大型或特殊交易的市場。", "用於缺乏標準化與流動性的資產交易。", "A broker found a buyer for the large block."),
    ("Hybrid market", "混合市場", "同時結合報價驅動、委託驅動或經紀機制的市場。", "用於描述多種流動性供應方式並存。", "The exchange operates as a hybrid market."),
    ("Market maker", "造市商", "持續提供買價與賣價並願意以自有帳戶交易的交易商。", "用於支持市場流動性與報價連續性。", "The market maker posted both bid and ask prices."),
    ("Dealer", "交易商", "以自有資金與庫存買賣證券並承擔部位風險的市場參與者。", "用於區分自營交易與代理交易。", "The dealer sold shares from its inventory."),
    ("Broker", "經紀人", "代表客戶尋找交易對手並執行交易以賺取佣金的代理人。", "用於分析代理成本與執行品質。", "The broker executed the client's order."),
    ("Bid price", "買價", "市場參與者願意買進證券的最高報價。", "用於估計立即賣出可取得的價格。", "The investor sold the shares at the bid price."),
    ("Ask price", "賣價", "市場參與者願意賣出證券的最低報價。", "用於估計立即買進須支付的價格。", "The investor bought the shares at the ask price."),
    ("Bid-ask spread", "買賣價差", "最低賣價與最高買價之間的差額。", "用於衡量交易成本與市場流動性。", "A narrow bid-ask spread indicates better liquidity."),
    ("Market order", "市價單", "要求立即以市場可得最佳價格成交的委託。", "用於優先確保成交而非控制價格。", "She submitted a market order to buy immediately."),
    ("Limit order", "限價單", "僅在指定價格或更有利價格成交的委託。", "用於控制成交價格但須承擔不成交風險。", "The buy limit order will execute only at the limit or lower."),
    ("Stop order", "停損單", "當市場價格觸及停止價後轉為市價單的條件委託。", "用於限制損失或順勢建立部位。", "The stop order became a market order after the trigger."),
    ("Stop-limit order", "停損限價單", "觸及停止價後轉為限價單而非市價單的條件委託。", "用於兼顧觸發條件與成交價格控制。", "The stop-limit order was triggered but remained unfilled."),
    ("Buy stop order", "買進停損單", "當價格上升至停止價時觸發買進的委託。", "用於回補空頭或突破價格時進場。", "The buy stop protected the short position from further losses."),
    ("Sell stop order", "賣出停損單", "當價格下降至停止價時觸發賣出的委託。", "用於限制多頭部位的下檔損失。", "The sell stop was triggered when the price fell."),
    ("Day order", "當日有效委託", "若未於提交當日成交便自動失效的委託。", "用於限制委託有效期間。", "The unfilled day order expired at the market close."),
    ("Good-till-cancelled order", "取消前有效委託", "在成交或投資人取消前持續有效的委託。", "用於長期等待指定價格。", "The good-till-cancelled order remained open for several weeks."),
    ("Immediate-or-cancel order", "立即成交否則取消委託", "可成交部分須立即執行，其餘部分立即取消的委託。", "用於避免未成交數量留在委託簿。", "The immediate-or-cancel order was only partially filled."),
    ("Fill-or-kill order", "全部立即成交否則取消委託", "必須立即全部成交，否則整筆取消的委託。", "用於要求數量完整且立即執行。", "The fill-or-kill order was cancelled because full size was unavailable."),
    ("All-or-none order", "全部成交委託", "只有在全部數量可成交時才執行，但不一定要求立即完成。", "用於避免部分成交。", "The all-or-none instruction prevented a partial execution."),
    ("Hidden order", "隱藏委託", "全部委託數量不在公開委託簿顯示的限價委託。", "用於降低大型委託暴露造成的市場衝擊。", "The institution used a hidden order to conceal its size."),
    ("Iceberg order", "冰山委託", "僅顯示總數量的一小部分並於成交後補充顯示的委託。", "用於分批揭露大型交易需求。", "Only a small portion of the iceberg order was visible."),
    ("Market-on-close order", "收盤市價委託", "要求盡可能接近正式收盤價執行的市價委託。", "用於追蹤以收盤價計算的指數。", "The fund used a market-on-close order for rebalancing."),
    ("Limit-on-close order", "收盤限價委託", "僅在收盤價格符合限價條件時於收盤執行的委託。", "用於控制收盤交易的最差價格。", "The limit-on-close order did not execute."),
    ("Short sale", "放空交易", "出售借入證券並預期日後以較低價格買回歸還的交易。", "用於獲利於價格下跌或進行避險。", "The investor made a short sale after expecting a price decline."),
    ("Short covering", "空頭回補", "買進先前放空的證券以歸還出借人的行為。", "用於結束空頭部位並實現損益。", "Short covering pushed the share price higher."),
    ("Margin purchase", "融資買進", "以自有資金加上向經紀商借款購買證券的交易。", "用於提高曝險並理解槓桿風險。", "A margin purchase magnifies both gains and losses."),
    ("Initial margin", "原始保證金", "建立槓桿部位時投資人須先投入的最低權益比例或金額。", "用於決定可建立部位的槓桿程度。", "The initial margin requirement was fifty percent."),
    ("Maintenance margin", "維持保證金", "持有槓桿部位期間帳戶必須維持的最低權益水準。", "用於判斷是否觸發追繳保證金。", "The account fell below the maintenance margin."),
    ("Margin call", "追繳保證金", "帳戶權益低於維持水準時要求投資人補充資金或擔保品的通知。", "用於管理信用風險與強制平倉風險。", "The price decline triggered a margin call."),
    ("Leverage ratio", "槓桿比率", "資產價值相對於投資人自有權益的倍數。", "用於衡量借款放大報酬與損失的程度。", "A higher leverage ratio increases equity risk."),
    ("Execution risk", "執行風險", "委託可能未成交、延遲成交或以不利價格成交的風險。", "用於選擇委託類型與交易策略。", "A limit order carries execution risk."),
    ("Market impact", "市場衝擊", "交易本身造成證券市場價格不利變動的成本。", "用於評估大型委託的隱性交易成本。", "The large purchase had significant market impact."),
    ("Implementation shortfall", "執行落差", "投資決策時理論部位價值與實際執行後部位價值之差。", "用於綜合衡量延遲、價差與市場衝擊。", "Implementation shortfall measures the total cost of execution."),
    ("Liquidity", "流動性", "資產能迅速、大量且以接近公允價值成交的能力。", "用於評估交易成本與變現容易程度。", "Highly liquid shares can be traded with little price impact."),
    ("Trading volume", "成交量", "特定期間內完成交易的股份數量。", "用於衡量市場活動與流動性。", "Trading volume rose sharply after the announcement."),
    ("Turnover ratio", "週轉率", "期間成交股數或金額相對於可交易股份或市值的比率。", "用於比較不同市場或證券的交易活躍程度。", "A high turnover ratio suggests active trading."),
    ("Free float", "自由流通量", "排除策略性、控制性或受限制持股後可由公眾交易的股份。", "用於指數加權與流動性分析。", "The index uses free float to adjust market capitalization."),
    ("Float-adjusted market capitalization", "自由流通調整市值", "以總市值乘上自由流通比例所得的可投資市值。", "用於降低不可交易持股對指數權重的影響。", "Float-adjusted market capitalization determines the stock's index weight."),
    ("Price index", "價格指數", "只反映成分證券價格變動而不計現金股利再投資的指數。", "用於衡量純粹的資本利得表現。", "A price index excludes reinvested dividends."),
    ("Total return index", "總報酬指數", "假設現金股利與其他分配再投資而衡量整體報酬的指數。", "用於比較包含收益再投資的投資績效。", "The total return index includes reinvested dividends."),
    ("Price-weighted index", "價格加權指數", "依各成分股每股價格決定權重的股票指數。", "用於理解高價股對指數變動較具影響力。", "A high-priced stock has more influence in a price-weighted index."),
    ("Equal-weighted index", "等權重指數", "每一成分證券在指數中具有相同初始權重的指數。", "用於降低大型公司主導程度但需頻繁再平衡。", "An equal-weighted index assigns the same weight to every constituent."),
    ("Market-capitalization-weighted index", "市值加權指數", "依成分公司總市值決定權重的指數。", "用於反映市場整體投資組合的價值變動。", "Larger companies dominate a market-capitalization-weighted index."),
    ("Fundamental-weighted index", "基本面加權指數", "依營收、盈餘、現金流或帳面價值等基本面指標決定權重的指數。", "用於避免權重直接隨市場價格上升。", "The fundamental-weighted index uses company sales to set weights."),
    ("Index rebalancing", "指數再平衡", "定期將成分權重調回指數規則所要求水準的過程。", "用於維持指數方法的一致性。", "Quarterly index rebalancing generated substantial trading."),
    ("Index reconstitution", "指數成分重組", "依資格規則新增、刪除或替換指數成分證券的過程。", "用於維持指數代表性。", "Annual reconstitution changed several index constituents."),
    ("Index divisor", "指數除數", "將成分證券總價格或總市值轉換為可比較指數水準的調整因子。", "用於處理拆股與成分變更而維持指數連續性。", "The index divisor was adjusted after the stock split."),
    ("Broad market index", "廣泛市場指數", "涵蓋某市場大部分可投資股票的指數。", "用作整體股票市場的績效基準。", "A broad market index represents most listed equities."),
    ("Multi-market index", "多市場指數", "涵蓋多個國家或地區股票市場的指數。", "用於衡量跨國權益投資績效。", "The multi-market index tracks equities across several countries."),
    ("Sector index", "產業部門指數", "追蹤特定產業部門公司表現的指數。", "用於產業配置與相對績效分析。", "The sector index outperformed the broad market."),
    ("Style index", "風格指數", "依價值、成長、市值或其他投資風格分類證券的指數。", "用作風格投資策略的比較基準。", "The value style index had a lower price-to-book ratio."),
    ("Security market index", "證券市場指數", "以一籃子證券代表特定市場或市場區隔績效的統計指標。", "用於衡量市場報酬、建立基準與發展衍生商品。", "The security market index serves as a performance benchmark."),
    ("Index replication", "指數複製", "持有全部或抽樣成分證券以追蹤指數報酬的投資方法。", "用於被動式投資組合管理。", "The fund uses full replication to track the index."),
    ("Tracking error", "追蹤誤差", "投資組合相對基準主動報酬的波動程度。", "用於衡量指數基金偏離基準的風險。", "Low tracking error indicates close index replication."),
    ("Survivorship bias", "存活者偏誤", "資料只包含存續證券或基金而排除失敗者所造成的績效高估。", "用於評估歷史指數與回測資料品質。", "Survivorship bias can overstate historical performance."),
    ("Efficient market", "效率市場", "證券價格能迅速且充分反映可得資訊的市場。", "用於判斷取得異常報酬的可行性。", "In an efficient market, prices quickly reflect new information."),
    ("Market efficiency", "市場效率", "市場價格納入資訊的速度與完整程度。", "用於評估主動管理與資訊分析的價值。", "Greater market efficiency makes persistent excess returns harder to earn."),
    ("Weak-form efficiency", "弱式效率", "目前價格已反映所有過去價格與成交量資訊的市場效率形式。", "用於檢驗技術分析能否持續產生異常報酬。", "Weak-form efficiency challenges profits based on past prices."),
    ("Semi-strong-form efficiency", "半強式效率", "目前價格已反映所有公開可得資訊的市場效率形式。", "用於檢驗基本面分析能否持續產生異常報酬。", "Semi-strong efficiency implies rapid adjustment to public news."),
    ("Strong-form efficiency", "強式效率", "目前價格已反映所有公開與非公開資訊的市場效率形式。", "用於檢驗內部資訊是否能帶來異常報酬。", "Strong-form efficiency assumes even private information is reflected."),
    ("Random walk", "隨機漫步", "價格變動彼此獨立且難以由過去變動預測的概念。", "用於說明弱式效率市場的價格行為。", "Under a random walk, yesterday's return does not predict today's return."),
    ("Abnormal return", "異常報酬", "證券實際報酬超過依風險與市場模型估計正常報酬的部分。", "用於事件研究與經理人績效分析。", "The announcement produced a positive abnormal return."),
    ("Event study", "事件研究", "衡量特定事件前後證券異常報酬的方法。", "用於檢驗市場反應速度與事件價值影響。", "The event study measured returns around the merger announcement."),
    ("Information cascade", "資訊瀑布", "投資人忽略自身資訊並跟隨先前他人行動的群體現象。", "用於解釋羊群行為與價格偏離。", "An information cascade caused investors to follow the crowd."),
    ("Herding", "羊群行為", "投資人模仿他人交易而非完全依賴獨立分析的行為。", "用於分析泡沫與市場動能。", "Herding amplified the market rally."),
    ("Loss aversion", "損失趨避", "相同金額損失造成的心理痛苦大於獲利帶來滿足的偏誤。", "用於解釋投資人過早獲利了結或不願認賠。", "Loss aversion may cause investors to hold losing stocks too long."),
    ("Overconfidence bias", "過度自信偏誤", "投資人高估自身知識、預測能力或資訊精確度的傾向。", "用於解釋過度交易與低估風險。", "Overconfidence often leads to excessive trading."),
    ("Confirmation bias", "確認偏誤", "偏好支持既有觀點的資訊並忽略相反證據的傾向。", "用於檢查研究流程是否客觀。", "Confirmation bias led the analyst to ignore negative evidence."),
    ("Anchoring bias", "錨定偏誤", "過度依賴最初數值或觀點而未充分因新資訊調整的傾向。", "用於辨識目標價與估值假設的僵化。", "The analyst anchored on the previous target price."),
    ("Availability bias", "可得性偏誤", "因資訊容易回想而高估其重要性或發生機率的傾向。", "用於解釋近期事件對判斷的過度影響。", "Availability bias made the recent crash seem more likely to recur."),
    ("Representativeness bias", "代表性偏誤", "依表面相似性分類並忽略基準機率或樣本限制的傾向。", "用於分析投資人對成長公司過度外推。", "Representativeness caused investors to extrapolate recent growth."),
    ("Disposition effect", "處分效果", "投資人傾向過早賣出獲利部位並長期持有虧損部位。", "用於理解實現盈虧的不對稱行為。", "The disposition effect delayed the sale of losing shares."),
    ("Momentum anomaly", "動能異常", "近期表現較佳的證券在短中期持續優於近期表現較差證券的現象。", "用於檢視價格延續與市場效率。", "The momentum strategy bought recent winners."),
    ("Value anomaly", "價值異常", "低估值股票長期報酬可能高於高估值股票的現象。", "用於研究價值因子與風險補償。", "The value anomaly favors stocks with low valuation multiples."),
    ("Post-earnings-announcement drift", "盈餘公告後漂移", "股價在盈餘意外公布後仍持續朝同方向緩慢調整的現象。", "用於檢驗資訊反應不足。", "Positive earnings surprise was followed by an upward price drift."),
    ("Limits to arbitrage", "套利限制", "成本、風險、融資與制度因素阻礙投資人消除錯價的情況。", "用於解釋市場異常為何可能持續。", "Short-sale constraints create limits to arbitrage."),
    ("Intrinsic value", "內在價值", "依資產未來預期現金流、風險與成長估計的基本價值。", "用於比較市場價格並形成投資建議。", "The analyst estimated intrinsic value above the market price."),
    ("Going concern value", "持續經營價值", "假設企業持續營運並利用資產共同創造現金流的價值。", "用於一般股權估值與併購分析。", "Going concern value usually exceeds liquidation value for a healthy firm."),
    ("Liquidation value", "清算價值", "停止營運並出售資產、清償負債後可供權益持有人分配的價值。", "用於困境企業與資產下檔估值。", "Liquidation value provides a downside estimate."),
    ("Fair value", "公允價值", "知情且自願的市場參與者在有序交易中交換資產的估計價格。", "用於財務報導與估值判斷。", "The shares were recorded at fair value."),
    ("Industry", "產業", "提供相似產品或服務且面臨共同需求與競爭因素的企業群體。", "用於比較公司基本面與估值。", "Firms in the industry face similar demand conditions."),
    ("Sector", "產業部門", "由數個相關產業組成的較廣泛經濟分類。", "用於由上而下的資產配置。", "The technology sector contains several distinct industries."),
    ("Industry classification", "產業分類", "依主要業務活動將公司系統化分組的方法。", "用於建立同業群組與產業指數。", "Industry classification helps analysts select comparable companies."),
    ("Cyclical industry", "景氣循環產業", "營收與獲利對整體經濟週期高度敏感的產業。", "用於預測景氣變化對公司盈餘的影響。", "Automobile demand is typical of a cyclical industry."),
    ("Defensive industry", "防禦型產業", "需求與獲利對經濟衰退相對不敏感的產業。", "用於經濟下行時降低投資組合波動。", "Utilities are often considered a defensive industry."),
    ("Growth industry", "成長型產業", "長期需求與營收預期高於整體經濟成長的產業。", "用於辨識結構性成長機會。", "Cloud computing has characteristics of a growth industry."),
    ("Mature industry", "成熟產業", "成長趨緩、競爭穩定且市場滲透率較高的產業。", "用於採用較穩定成長與股利假設。", "A mature industry often generates stable cash flow."),
    ("Declining industry", "衰退產業", "長期需求、產量或營收呈下降趨勢的產業。", "用於評估資產減損與退出風險。", "The declining industry faced persistent demand erosion."),
    ("Industry life cycle", "產業生命週期", "產業由導入、成長、成熟至衰退的發展階段。", "用於調整成長率、競爭與資本需求假設。", "The industry life cycle affects growth and profitability."),
    ("Embryonic stage", "萌芽期", "產品接受度低、技術不確定且企業風險高的產業初期階段。", "用於評估早期市場與高失敗率。", "Sales are limited during the embryonic stage."),
    ("Shakeout stage", "整併期", "產業成長放緩並促使弱勢競爭者退出或被收購的階段。", "用於預測集中度上升與競爭淘汰。", "Several weak competitors exited during the shakeout stage."),
    ("Porter's five forces", "波特五力", "以新進者、替代品、買方、供應商與既有競爭分析產業獲利能力的架構。", "用於系統化評估產業競爭強度。", "Porter's five forces identify the sources of competitive pressure."),
    ("Threat of new entrants", "新進者威脅", "新競爭者進入產業並壓低既有企業報酬的可能性。", "用於評估進入障礙的有效性。", "High capital requirements reduce the threat of new entrants."),
    ("Threat of substitutes", "替代品威脅", "其他產品滿足相同需求並限制產業定價能力的風險。", "用於評估需求彈性與長期利潤率。", "Streaming services increased the threat of substitutes."),
    ("Bargaining power of buyers", "買方議價能力", "客戶壓低價格、要求品質或取得有利條款的能力。", "用於分析企業定價權與毛利率。", "Concentrated customers have strong bargaining power."),
    ("Bargaining power of suppliers", "供應商議價能力", "供應商提高投入價格或降低供應條件的能力。", "用於評估成本壓力與供應風險。", "A scarce input gives suppliers greater bargaining power."),
    ("Rivalry among existing competitors", "既有競爭者間對抗", "產業內現有企業以價格、產品或行銷爭奪市場的強度。", "用於判斷產業利潤受競爭侵蝕程度。", "Intense rivalry reduced industry profit margins."),
    ("Barriers to entry", "進入障礙", "阻礙新企業進入產業的成本、法規、規模或品牌因素。", "用於評估既有企業競爭優勢的持久性。", "Patents create significant barriers to entry."),
    ("Economies of scale", "規模經濟", "產量增加時單位成本下降的現象。", "用於分析成本領先與進入障礙。", "Economies of scale lowered the firm's unit cost."),
    ("Network effect", "網路效應", "產品或服務價值隨使用者數量增加而提升的現象。", "用於評估平台企業的競爭優勢。", "The network effect strengthened the platform's market position."),
    ("Switching cost", "轉換成本", "客戶由現有供應商改用競爭者時承擔的金錢、時間或風險成本。", "用於衡量客戶留存與定價權。", "High switching costs support customer retention."),
    ("Pricing power", "定價能力", "企業提高售價而不致大幅流失需求的能力。", "用於評估競爭優勢與利潤率韌性。", "Strong branding gives the company pricing power."),
    ("Economic moat", "經濟護城河", "能長期保護企業超額報酬免受競爭侵蝕的持久優勢。", "用於評估高資本報酬的可持續性。", "The firm's patents provide a durable economic moat."),
    ("Top-down analysis", "由上而下分析", "先分析總體經濟與產業，再選擇個別公司的投資方法。", "用於將經濟情境連結至產業與股票選擇。", "Top-down analysis begins with the economic outlook."),
    ("Bottom-up analysis", "由下而上分析", "以個別公司基本面為核心而較少依賴總體預測的投資方法。", "用於發掘特定公司的錯價機會。", "Bottom-up analysis focuses on company-specific fundamentals."),
    ("Competitive strategy", "競爭策略", "企業用以取得成本、差異化或利基優勢的整體行動方針。", "用於評估公司在產業中的定位。", "The company's competitive strategy emphasizes product differentiation."),
    ("Cost leadership", "成本領先", "以低於競爭者的成本營運並取得價格或利潤優勢的策略。", "用於分析規模、流程與採購優勢。", "Cost leadership allows the firm to compete on price."),
    ("Product differentiation", "產品差異化", "透過獨特品質、品牌或功能使產品有別於競爭者的策略。", "用於評估品牌溢價與顧客忠誠度。", "Product differentiation supports premium pricing."),
    ("Dividend discount model", "股利折現模型", "將預期未來股利按權益必要報酬率折現以估計股票價值的模型。", "用於股利與價值關係穩定的公司估值。", "The dividend discount model values equity from expected dividends."),
    ("Gordon growth model", "高登成長模型", "假設股利以固定永續成長率成長的單階段股利折現模型。", "用於成熟且成長穩定公司的估值。", "The Gordon growth model assumes a constant dividend growth rate."),
    ("Two-stage dividend discount model", "兩階段股利折現模型", "先估計一段非穩定成長，再假設進入穩定永續成長的模型。", "用於成長率預期逐步正常化的公司。", "The two-stage model separates high growth from stable growth."),
    ("Three-stage dividend discount model", "三階段股利折現模型", "區分高成長、過渡與穩定成長三個階段的股利折現模型。", "用於成長逐步減速且轉換較平滑的公司。", "The three-stage model includes a transition period."),
    ("Required return on equity", "權益必要報酬率", "投資人承擔股票風險所要求的最低預期報酬率。", "用作權益現金流的折現率。", "A higher required return reduces estimated equity value."),
    ("Dividend growth rate", "股利成長率", "股利預期隨時間增加的比率。", "用於股利折現模型與永續價值估計。", "The analyst expects the dividend growth rate to stabilize."),
    ("Sustainable growth rate", "可持續成長率", "在不改變資本結構且不發行新股下可由保留盈餘支持的長期成長率。", "通常以保留率乘權益報酬率估計。", "Sustainable growth equals retention rate times return on equity."),
    ("Retention rate", "盈餘保留率", "淨利中未以股利分配而留在企業內的比例。", "用於估計內部融資支持的成長。", "A higher retention rate can support faster growth."),
    ("Dividend payout ratio", "股利支付率", "普通股股利相對於可供普通股股東淨利的比例。", "用於評估分配政策與保留盈餘。", "The dividend payout ratio rose as growth opportunities declined."),
    ("Free cash flow to equity", "股東自由現金流", "支付營運、資本支出及債權人淨付款後可供普通股股東使用的現金流。", "用於不依賴實際股利政策的股權估值。", "FCFE measures cash flow available to common shareholders."),
    ("FCFE model", "股東自由現金流模型", "將預期股東自由現金流按權益必要報酬率折現的估值模型。", "用於股利與支付能力不一致的公司。", "The FCFE model produced a value above the current price."),
    ("Free cash flow to the firm", "企業自由現金流", "支付營運與必要投資後可供所有資本提供者分配的現金流。", "用於先估計企業價值再扣除淨負債。", "FCFF is available to both debt and equity investors."),
    ("FCFF model", "企業自由現金流模型", "將企業自由現金流以加權平均資本成本折現以估計企業價值的模型。", "用於資本結構可能變動或高槓桿公司的估值。", "The FCFF model discounts cash flows at the weighted average cost of capital."),
    ("Terminal value", "終值", "明確預測期結束時所有後續現金流的現值。", "用於多階段估值並常占總價值很大比例。", "Terminal value represented most of the estimated firm value."),
    ("Perpetuity growth method", "永續成長法", "假設預測期後現金流以固定速度永續成長來估計終值的方法。", "用於連結長期穩定成長與終值。", "The perpetuity growth method assumes stable long-term growth."),
    ("Exit multiple method", "退出倍數法", "以預測期末財務指標乘上合理市場倍數估計終值的方法。", "用於相對估值架構下的終值估計。", "The exit multiple method applied an EBITDA multiple."),
    ("Present value of growth opportunities", "成長機會現值", "股票價值中來自未來具正淨現值投資機會的部分。", "用於區分既有資產價值與成長價值。", "PVGO explains why the stock trades above its no-growth value."),
    ("No-growth value", "零成長價值", "假設公司將全部盈餘分配且盈餘不成長時的股票價值。", "用於分析市場價格隱含的成長機會價值。", "No-growth value equals earnings divided by the required return."),
    ("Residual income", "剩餘利益", "淨利扣除期初權益帳面價值之必要資本費用後的收益。", "用於股利或自由現金流不易預測時估值。", "Residual income is profit after the equity charge."),
    ("Residual income model", "剩餘利益模型", "以目前帳面價值加上未來剩餘利益現值估計股權價值的模型。", "用於會計資訊可靠且公司不支付股利的情況。", "The residual income model starts with book value."),
    ("Book value of equity", "權益帳面價值", "資產負債表中總資產減總負債後歸屬股東的會計價值。", "用於剩餘利益模型與市價淨值比分析。", "Book value of equity is reported on the balance sheet."),
    ("Return on equity", "權益報酬率", "淨利相對於平均普通股權益的獲利能力比率。", "用於衡量股東資本效率與可持續成長。", "Return on equity improved because profit margins increased."),
    ("DuPont analysis", "杜邦分析", "將權益報酬率分解為利潤率、資產週轉率與財務槓桿的分析方法。", "用於辨識權益報酬率的營運與融資來源。", "DuPont analysis explains the drivers of return on equity."),
    ("Net profit margin", "淨利率", "淨利相對於營收的比例。", "用於杜邦分析與跨期獲利能力比較。", "The net profit margin increased after costs fell."),
    ("Asset turnover", "資產週轉率", "營收相對於平均總資產的比率。", "用於衡量資產產生銷售的效率。", "Higher asset turnover improved return on equity."),
    ("Financial leverage", "財務槓桿", "使用債務融資使股東報酬與風險被放大的程度。", "用於杜邦分析與資本結構評估。", "Financial leverage magnified the decline in equity returns."),
    ("Weighted average cost of capital", "加權平均資本成本", "依市場價值權重計算債務與權益資金成本的加權平均。", "用作企業自由現金流的折現率。", "The analyst discounted FCFF at the weighted average cost of capital."),
    ("Price-to-earnings ratio", "本益比", "每股市價除以每股盈餘的估值倍數。", "用於比較市場為每單位盈餘支付的價格。", "The stock trades at a price-to-earnings ratio of fifteen."),
    ("Trailing P/E", "歷史本益比", "以最近十二個月實際每股盈餘計算的本益比。", "用於依已實現盈餘進行相對估值。", "Trailing P/E uses earnings from the past twelve months."),
    ("Forward P/E", "預估本益比", "以未來十二個月或下一年度預估每股盈餘計算的本益比。", "用於反映市場對未來盈餘的定價。", "Forward P/E uses forecast earnings."),
    ("Justified P/E", "合理本益比", "由基本面成長、支付率與必要報酬率所支持的理論本益比。", "用於比較市場倍數與模型隱含倍數。", "The justified P/E rises with expected growth."),
    ("Earnings yield", "盈餘收益率", "每股盈餘除以每股市價，為本益比的倒數。", "用於比較股票盈餘報酬與其他資產收益率。", "Earnings yield is the inverse of the price-to-earnings ratio."),
    ("Price-to-book ratio", "股價淨值比", "每股市價除以每股權益帳面價值的倍數。", "常用於金融業或資產密集型公司估值。", "Banks are often compared using the price-to-book ratio."),
    ("Price-to-sales ratio", "股價營收比", "公司市值或每股市價相對於營收或每股營收的倍數。", "用於盈餘為負但營收具意義的公司。", "The price-to-sales ratio can be used when earnings are negative."),
    ("Price-to-cash-flow ratio", "股價現金流比", "每股市價相對於每股現金流的估值倍數。", "用於降低非現金會計項目對比較的影響。", "The price-to-cash-flow ratio was below the peer median."),
    ("Dividend yield", "股利殖利率", "每股年度股利除以每股市價的比例。", "用於衡量股票現金收益相對於價格的水準。", "The stock offers a dividend yield of four percent."),
    ("Enterprise value", "企業價值", "普通股市值加特別股與債務，再減現金及約當現金的整體營運價值。", "用於比較不同資本結構的公司。", "Enterprise value reflects the value of the operating business."),
    ("EV/EBITDA", "企業價值對稅息折舊攤銷前利益倍數", "企業價值除以稅息折舊攤銷前利益的估值倍數。", "用於跨資本結構與折舊政策比較。", "The company trades at eight times EV to EBITDA."),
    ("EV/Sales", "企業價值對營收倍數", "企業價值除以營收的估值倍數。", "用於比較低利潤或尚未獲利公司。", "EV to sales is useful when operating margins differ."),
    ("EV/EBIT", "企業價值對稅息前利益倍數", "企業價值除以稅息前利益的估值倍數。", "用於納入折舊影響並比較營運價值。", "EV to EBIT incorporates depreciation expense."),
    ("Comparable company analysis", "可比公司分析", "以相似上市公司的市場倍數估計目標公司相對價值的方法。", "用於選擇同業並套用基準倍數。", "Comparable company analysis used the peer median multiple."),
    ("Guideline public company method", "上市公司參考法", "以具可比性的公開交易公司作為私有或目標企業估值基準的方法。", "用於將公開市場倍數調整後套用至標的。", "The guideline public company method relied on listed peers."),
    ("Precedent transaction analysis", "先例交易分析", "以過去相似併購交易支付的倍數估計企業價值的方法。", "用於納入控制權溢價的交易估值。", "Precedent transactions implied a higher valuation."),
    ("Control premium", "控制權溢價", "取得企業控制權所支付超過少數股權市場價值的額外金額。", "用於併購與控制性持股估值。", "The acquirer paid a control premium."),
    ("Minority discount", "少數股權折價", "因缺乏控制決策能力而使少數股權價值降低的調整。", "用於私人公司或非控制性持股估值。", "A minority discount reduced the appraised share value."),
    ("Discount for lack of marketability", "缺乏市場性折價", "因股權難以迅速出售而相對可交易股權價值降低的調整。", "用於私有公司與受限制股份估值。", "The private shares required a discount for lack of marketability."),
    ("PEG ratio", "本益成長比", "本益比除以預期盈餘成長率的估值指標。", "用於將估值倍數與成長預期連結。", "A lower PEG ratio may indicate cheaper growth."),
    ("Normalized earnings", "正常化盈餘", "排除一次性、非經常或週期性極端因素後的可持續盈餘。", "用於避免倍數受暫時性盈餘扭曲。", "The analyst used normalized earnings for valuation."),
    ("Cyclically adjusted earnings", "景氣循環調整盈餘", "跨完整景氣週期平均或調整後的盈餘。", "用於評估高度週期性公司的中期獲利能力。", "Cyclically adjusted earnings smooth temporary peaks and troughs."),
    ("Enterprise multiple", "企業倍數", "以企業價值除以營運績效指標的相對估值倍數總稱。", "用於比較資本結構不同的企業。", "An enterprise multiple is less affected by financing choices."),
    ("Multifactor model", "多因子模型", "以多個系統性風險因子解釋或預測證券報酬的模型。", "用於風險歸因、必要報酬估計與投資組合建構。", "The multifactor model includes market, size, and value factors."),
    ("Factor sensitivity", "因子敏感度", "證券報酬對特定系統性因子變動的反應程度。", "用於衡量因子曝險與預期報酬來源。", "The stock has high sensitivity to the growth factor."),
    ("Market factor", "市場因子", "代表廣泛股票市場超額報酬的共同風險因子。", "用於解釋股票受整體市場影響的程度。", "The market factor explains broad movements in equity returns."),
    ("Size factor", "規模因子", "小型公司股票相對大型公司股票報酬差異的系統性因子。", "用於衡量投資組合的小型股曝險。", "The portfolio has positive exposure to the size factor."),
    ("Value factor", "價值因子", "低估值股票相對高估值股票報酬差異的系統性因子。", "用於衡量投資組合的價值風格曝險。", "The value factor performed well during the period."),
    ("Momentum factor", "動能因子", "近期贏家相對近期輸家報酬差異的系統性因子。", "用於衡量價格趨勢曝險。", "The strategy has a strong momentum factor loading."),
    ("Systematic risk", "系統性風險", "由整體市場或共同經濟因子造成且無法透過分散完全消除的風險。", "用於估計必要報酬與貝塔。", "Systematic risk cannot be eliminated through diversification."),
    ("Idiosyncratic risk", "個別風險", "源自特定公司或產業且可透過分散降低的風險。", "用於分析集中持股與主動風險。", "Diversification reduces idiosyncratic risk."),
    ("Beta", "貝塔係數", "證券報酬對市場報酬變動敏感度的衡量。", "用於資本資產定價模型估計權益必要報酬。", "A beta above one indicates greater market sensitivity."),
    ("Capital asset pricing model", "資本資產定價模型", "以無風險利率加市場風險溢酬乘貝塔估計必要報酬的模型。", "用於權益成本與估值折現率估計。", "CAPM links expected return to systematic market risk."),
    ("Equity risk premium", "權益風險溢酬", "投資人持有股票相對無風險資產所要求的額外報酬。", "用於估計權益必要報酬與市場折現率。", "A higher equity risk premium lowers stock valuations."),
    ("Active return", "主動報酬", "投資組合報酬減去基準報酬的差額。", "用於衡量主動管理相對績效。", "The manager generated a positive active return."),
]
