# CFA L1 Ethics ~100 terms
# format: (en, zh, definition, usage, example)

TERMS = [
("Code of Ethics", "道德規範", "CFA協會要求會員與考生遵守的核心道德原則總綱，涵蓋誠信、客戶利益優先等。", "討論職業操守、入會義務或紀律案件時引用。", "\"As CFA candidates, we must abide by the Code of Ethics in every client interaction.\""),
("Standards of Professional Conduct", "專業行為準則", "將道德規範具體化為可執行的行為標準，涵蓋專業、誠信、對客戶與雇主的職責等。", "評估某行為是否違規時對照各條標準。", "\"Before recommending the product, check whether it conflicts with the Standards of Professional Conduct.\""),
("Professionalism", "專業精神", "標準一：要求了解並遵守法律、獨立客觀、不誤導，並妥善使用資格稱謂。", "談執業資格、廣告文案與稱謂使用時。", "\"Professionalism means I won't claim 'CFA' status until I've actually earned the charter.\""),
("Knowledge of the Law", "了解法律", "須知悉並遵守適用法律、規定與準則；若衝突，以較嚴格者為準。", "跨境業務或法規衝突情境。", "\"Under Knowledge of the Law, if local rules are stricter than the Code, we follow the stricter rule.\""),
("Independence and Objectivity", "獨立與客觀", "分析與建議不得因饋贈、壓力或利益關係而偏頗。", "收受禮物、發行人關係、研究報告壓力。", "\"Accepting this luxury trip would compromise my independence and objectivity.\""),
("Misrepresentation", "不實陳述", "禁止保證報酬、誇大能力，或抄襲他人分析而不註明來源。", "行銷文案、研究報告歸因。", "\"Promising a guaranteed 15% return would be a clear misrepresentation.\""),
("Misconduct", "不當行為", "禁止欺詐、不誠實或任何損及專業誠信的行為。", "個人誠信爭議、職場舞弊。", "\"Falsifying expense reports is misconduct, even if it seems unrelated to investment advice.\""),
("Integrity of Capital Markets", "資本市場誠信", "標準二：禁止利用重大非公開資訊，並禁止操控股價等市場操縱。", "內線交易疑慮、盤前消息。", "\"Trading on that tip would violate integrity of capital markets.\""),
("Material Nonpublic Information", "重大非公開資訊", "若公開將顯著影響價格或投資人決策，且尚未公開的資訊。", "內線交易判斷、資訊牆。", "\"The CEO's private outlook is material nonpublic information—we cannot trade on it.\""),
("Mosaic Theory", "拼圖理論", "可合法彙整多項非重大、非公開或公開資訊，形成投資結論，不構成內線交易。", "區分合法研究與非法內線。", "\"Using mosaic theory, I combined industry data and public filings to reach my view.\""),
("Market Manipulation", "市場操縱", "透過虛假交易、散布謠言等方式意圖扭曲價格或交易量。", "洗售、哄抬、虛假資訊。", "\"Spreading false rumors to push the stock up is market manipulation.\""),
("Duties to Clients", "對客戶的職責", "標準三：忠誠、審慎與關懷；公平交易；適當性；績效呈現；機密。", "客戶關係衝突、帳戶優先順序。", "\"Duties to clients come before the firm's short-term revenue goals.\""),
("Loyalty, Prudence, and Care", "忠誠、審慎與關懷", "以客戶利益為先，並以審慎專業態度管理資產。", "信託責任、投資決策流程。", "\"Loyalty, prudence, and care require us to put the client's interest first.\""),
("Soft Dollar", "軟美元", "用客戶經紀佣金換取研究等服務；須對客戶有益且揭露。", "券商選擇、研究服務採購。", "\"Is this research package an appropriate soft-dollar expenditure for the client?\""),
("Fair Dealing", "公平交易", "對所有客戶公平分配投資機會與資訊，不得偏袒特定帳戶。", "IPO配置、推薦同步發布。", "\"Fair dealing means we allocate the IPO shares pro rata across eligible accounts.\""),
("Suitability", "適當性", "投資建議須符合客戶的目標、限制與風險承受度；組合層級亦須適當。", "Know-your-customer、IPS對照。", "\"A concentrated options strategy isn't suitable for this retiree's IPS.\""),
("Investment Policy Statement", "投資政策聲明書", "載明客戶目標、限制、風險承受與指引的正式文件（常簡稱 IPS）。", "開戶、再平衡、適當性檢查。", "\"Let's update the investment policy statement before changing the asset mix.\""),
("Performance Presentation", "績效呈現", "績效須公平、準確、完整，不得挑績優期間誤導。", "行銷簡報、歷史報酬揭露。", "\"Cherry-picking the best three years would violate performance presentation standards.\""),
("Preservation of Confidentiality", "保密義務", "除非客戶同意、法律要求或涉嫌違法，否則須保守客戶資訊。", "客戶資料分享、監管調閱。", "\"I can't share the client's holdings without consent—preservation of confidentiality applies.\""),
("Duties to Employers", "對雇主的職責", "標準四：忠誠；不得收取未揭露的額外報酬；主管須合理監督。", "離職競業、兼職、團隊管理。", "\"Duties to employers still apply while I'm resigning and transitioning clients.\""),
("Loyalty (to Employer)", "對雇主的忠誠", "不得傷害雇主利益，如竊取機密、挖角客戶（合約與準則範圍內）。", "離職準備、客戶名單。", "\"Copying the firm's models to my USB before leaving breaches loyalty to my employer.\""),
("Additional Compensation Arrangements", "額外報酬安排", "收受可能產生利益衝突的報酬前，須取得雇主書面同意。", "客戶贈禮、外部顧問費。", "\"I need written approval for this additional compensation arrangement from the client.\""),
("Responsibilities of Supervisors", "主管責任", "須建立並執行合理監督程序，防範違規。", "合規制度、團隊稽核。", "\"As a supervisor, I must enforce compliance procedures, not just hope people behave.\""),
("Investment Analysis, Recommendations, and Actions", "投資分析、建議與行動", "標準五：勤勉合理依據；與客戶充分溝通；保留紀錄。", "研究品質、模型假設說明。", "\"Standard V requires diligence and a reasonable basis before I publish the rating.\""),
("Diligence and Reasonable Basis", "勤勉與合理依據", "建議須基於充分調查與嚴謹分析。", "二手報告依賴、盡職調查。", "\"Relying only on a blog rumor fails diligence and reasonable basis.\""),
("Communication with Clients and Prospective Clients", "與客戶及準客戶溝通", "須揭露投資過程的重要因素、風險與限制，並區分事實與意見。", "研究報告、產品說明。", "\"In our communication with clients, we must clearly separate facts from opinions.\""),
("Record Retention", "紀錄保存", "須保留支持分析、建議與行動的適當紀錄。", "合規稽核、爭議舉證。", "\"Record retention means we keep the research files that support this recommendation.\""),
("Conflicts of Interest", "利益衝突", "標準六：須揭露衝突；交易優先順序；不得利用董事會等身分謀私。", "自營與客戶單、推薦揭露。", "\"Owning the stock personally creates a conflict of interest we must disclose.\""),
("Disclosure of Conflicts", "利益衝突揭露", "須完整、顯著揭露可能影響獨立客觀的衝突。", "研究報告聲明、客戶告知。", "\"Full disclosure of conflicts is required before we pitch this affiliated fund.\""),
("Priority of Transactions", "交易優先順序", "客戶與雇主交易優先於個人交易。", "個人帳戶、預先核准交易。", "\"Priority of transactions means client orders go before my personal trade.\""),
("Referral Fees", "介紹費", "收付介紹費須向客戶與雇主適當揭露。", "業務轉介、分潤。", "\"We must disclose this referral fee to the client in writing.\""),
("Responsibilities as a CFA Institute Member or Candidate", "會員或考生責任", "標準七：不得損害 CFA 誠信；考試相關資訊須保密。", "考試討論、資格行銷。", "\"Discussing specific exam questions violates responsibilities as a CFA candidate.\""),
("Conduct as Participants in CFA Institute Programs", "參與CFA協會專案之行為", "不得作弊、洩題或干擾考試與專案誠信。", "考場規範、題目討論。", "\"Sharing memorized exam content breaches conduct rules for CFA Institute programs.\""),
("Reference to CFA Institute, the CFA Designation, and the CFA Program", "提及CFA協會、稱謂與課程", "正確使用 CFA 稱謂與考生身分，不得暗示保證績效或誇大。", "名片、LinkedIn、廣告。", "\"You can't say 'CFA Level II' as if it were a designation—use the proper candidate wording.\""),
("Fiduciary Duty", "受信義務", "為受益人最佳利益行事的法律與道德義務。", "信託、退休金管理。", "\"As a fiduciary, I must act solely in the beneficiaries' best interest.\""),
("Custody", "保管", "對客戶資產的持有或控制；涉及安全與帳戶分離。", "資產保管安排、詐騙防範。", "\"Client assets should be held in proper custody, separate from firm funds.\""),
("Proxy Voting", "委託書投票", "代客戶行使投票權時須以客戶利益為依歸並有政策。", "公司治理、投票紀錄。", "\"Our proxy voting policy puts clients' long-term value first.\""),
("Best Execution", "最佳執行", "在考量價格、速度、研究服務等因素下，為客戶追求最有利的交易執行。", "券商選擇、交易成本。", "\"Best execution isn't only about the lowest commission—it's overall client benefit.\""),
("Front Running", "搶先交易", "知悉客戶大單後先為自己或他人交易，損害客戶。", "個人交易監控。", "\"Buying ahead of the client's large order is front running and prohibited.\""),
("Insider Trading", "內線交易", "利用重大非公開資訊買賣證券的違法行為。", "合規訓練、資訊牆。", "\"Insider trading can destroy both your career and market integrity.\""),
("Information Barrier / Fire Wall", "資訊牆", "阻隔部門間敏感資訊流動的內部控制機制。", "投行與研究、自營隔離。", "\"The information barrier keeps deal teams from leaking tips to the trading desk.\""),
("Watch List / Restricted List", "觀察名單／限制名單", "因敏感資訊而限制研究或交易的證券名單。", "合規控管、員工交易。", "\"That name is on the restricted list, so personal trading is blocked.\""),
("GIPS", "全球投資績效標準", "CFA協會推廣的公正績效計算與呈報自願標準。", "資產管理行銷、合規聲明。", "\"Our firm claims GIPS compliance for the composite presentation.\""),
("Composite", "投資組合綜合帳戶", "GIPS 下依類似策略歸組的投資組合集合，用於績效呈報。", "策略績效比較。", "\"All fee-paying discretionary accounts must be included in a composite.\""),
("Firm (GIPS definition)", "公司（GIPS定義）", "以投資管理為主要業務、可被區分的組織實體。", "GIPS 宣稱範圍。", "\"For GIPS, the firm definition determines which portfolios enter the composites.\""),
("Discretionary Portfolio", "全權委託投資組合", "經理人對投資決策具實質裁量權的帳戶。", "GIPS 納入條件。", "\"Only discretionary portfolios are required in GIPS composites.\""),
("Verification (GIPS)", "查核（GIPS）", "由獨立第三方檢視公司是否遵循 GIPS 政策與程序。", "行銷可信度。", "\"Third-party verification strengthens our GIPS compliance claim.\""),
("Plagiarism", "抄襲", "使用他人研究成果、模型或文字卻未適當歸因。", "報告撰寫、簡報。", "\"Copying another analyst's table without citation is plagiarism.\""),
("Guarantee of Returns", "報酬保證", "向客戶保證投資報酬屬不實陳述，原則上禁止。", "銷售話術。", "\"Never give a guarantee of returns—markets don't allow that honesty.\""),
("Partial Client List", "部分客戶名單", "行銷時僅列出部分客戶；須公平且不誤導。", "簡介手冊。", "\"If we publish a partial client list, it must not imply all clients are winners.\""),
("Whistleblowing", "揭弊", "為保護客戶或市場誠信而向當局舉報；在特定情況下可優先於對雇主忠誠。", "嚴重違法發現。", "\"Whistleblowing may be justified when client assets are at clear risk.\""),
("Moonlighting", "兼職", "在外從事有報酬活動；可能觸及忠誠與額外報酬揭露。", "顧問兼差。", "\"Moonlighting as a board advisor needs employer approval and disclosure.\""),
("Independent Practice", "獨立執業", "另行從事競爭業務前須通知雇主並處理衝突。", "離職創業。", "\"Independent practice while still employed usually requires written consent.\""),
("Client Priority", "客戶優先", "客戶利益與交易優於個人及特定關係人。", "下單順序。", "\"Client priority means family accounts don't jump the queue either.\""),
("Beneficial Ownership", "實質受益所有權", "即使非登記名義，仍享有經濟利益的持股，常納入個人交易規範。", "配偶帳戶、信託。", "\"Shares in my spouse's account count as my beneficial ownership for trading rules.\""),
("Blackout Period", "閉鎖期", "禁止員工買賣特定證券的時段，通常在報告發布前後。", "研究發布時程。", "\"We're in a blackout period until the report is released to all clients.\""),
("Preclearance", "預先核准", "個人交易前須取得合規核准的程序。", "員工交易政策。", "\"I submitted a preclearance request before buying the stock personally.\""),
("Material Gift", "重大饋贈", "可能影響獨立客觀的禮物或招待，通常須拒絕或揭露。", "節日禮品、差旅招待。", "\"A week-long resort stay is a material gift and should be declined.\""),
("Issuer-Paid Research", "發行人付費研究", "由標的公司付費的研究；須清楚揭露以防誤導。", "研究服務模式。", "\"Issuer-paid research must be labeled clearly so readers see the conflict.\""),
("Secondary Research", "二手研究", "使用他人研究；仍須以勤勉態度評估其可靠性。", "引用券商報告。", "\"Using secondary research is fine if I verify the assumptions myself.\""),
("Quantitative Model Reliance", "依賴量化模型", "使用模型時須了解假設、限制與資料品質，不能盲目採納。", "演算法建議。", "\"Blind quantitative model reliance without review fails reasonable basis.\""),
("Change in Investment Process", "投資流程變更", "重大流程改變須告知客戶。", "策略調整通知。", "\"A change in the investment process should be communicated promptly to clients.\""),
("Risk Disclosure", "風險揭露", "向客戶說明重要風險因素的義務。", "產品DM、會議紀錄。", "\"Risk disclosure must cover liquidity and leverage, not only market volatility.\""),
("Flash Report", "即時快報", "重大意見變更時迅速通知客戶，以維持公平交易。", "評等突變。", "\"Issue a flash report so all clients hear the downgrade at the same time.\""),
("Oversubscribed Issue", "超额認購發行", "需求大於供給的新發行；配置須公平。", "IPO分配。", "\"For an oversubscribed issue, allocate fairly—no favoritism to hot prospects.\""),
("Hot Issue", "熱門新股", "上市後可能大漲的新發行；特別禁止不公平配置給自己或關係人。", "IPO道德。", "\"Keeping hot issues for personal accounts violates fair dealing.\""),
("Block Trade", "整批交易", "大額一次性交易；執行時仍須兼顧公平與最佳執行。", "機構下單。", "\"When we execute a block trade, we still allocate fills fairly across accounts.\""),
("Average Price Execution", "均價執行", "多帳戶以平均價格分配成交；常見於公平分配。", "同步買賣。", "\"We used average price execution so no client got a preferential fill.\""),
("Directed Brokerage", "指定經紀", "客戶要求透過特定券商交易；可能影響最佳執行評估。", "客戶指示。", "\"Directed brokerage from the client must still be evaluated for overall benefit.\""),
("Principal Trade", "自營對作交易", "券商以自有帳戶與客戶成交；利益衝突須管理與揭露。", "造市、內部化。", "\"A principal trade with the client needs clear disclosure of the conflict.\""),
("Agency Trade", "代理交易", "券商僅代理客戶撮合，不自營對作。", "經紀角色說明。", "\"In an agency trade, we represent the client rather than trade against them.\""),
("Soft-Dollar Bundle", "軟美元套餐", "佣金同時涵蓋執行與研究等服務的安排。", "券商談判。", "\"Unpack the soft-dollar bundle and show what research the client actually receives.\""),
("Client Confidentiality Exception", "客戶保密例外", "法律要求或客戶涉嫌違法時，可突破保密。", "洗錢通報。", "\"Suspected money laundering is a client confidentiality exception—we must report.\""),
("Suitability at Portfolio Level", "投資組合層級適當性", "即使單一證券偏風險，若對整體組合適當仍可能可接受。", "衛星持股辯護。", "\"Suitability at the portfolio level can justify a small high-risk satellite position.\""),
("Total Return Mandate", "總報酬委託", "著重資本利得加收益的整體報酬目標。", "IPS目標撰寫。", "\"This endowment has a total return mandate, not income-only.\""),
("Relative Return Mandate", "相對報酬委託", "以擊敗或追蹤基準為目標的委託。", "主動管理合約。", "\"Under a relative return mandate, underperforming the benchmark is the key risk.\""),
("Absolute Return Mandate", "絕對報酬委託", "追求正報酬或與市場低相關的目標，而非擊敗基準。", "對沖基金、另類。", "\"An absolute return mandate cares less about beating the S&P 500.\""),
("Trust Beneficiaries", "信託受益人", "受信人須為其利益行事的對象。", "家族信託。", "\"Loyalty is owed to the trust beneficiaries, not the relative who referred the account.\""),
("Prudent Investor Rule", "審慎投資人規則", "以整體組合觀點評估風險與分散，而非單一證券。", "信託投資標準。", "\"The prudent investor rule judges the portfolio as a whole.\""),
("Loyalty to Caput vs Beneficiaries", "對委託人與受益人", "當利益衝突時，通常以受益人（客戶）為優先。", "家族壓力。", "\"Even if the patriarch complains, loyalty runs to the beneficiaries under the trust.\""),
("CFA Charterholder", "CFA特許資格持有人", "通過考試並滿足經驗等要求後獲頒稱謂者。", "職涯與稱謂。", "\"Only a CFA charterholder may use the CFA designation after their name.\""),
("CFA Candidate", "CFA考生", "報名並參與 CFA 課程考試者；不得暗示已具特許資格。", "履歷寫法。", "\"As a CFA candidate, I state my level clearly without implying I'm chartered.\""),
("Lapsed Charter", "失效特許資格", "未繳會費等導致稱謂不可再使用，直至恢復。", "稱謂合規。", "\"With a lapsed charter, you must stop using the CFA designation immediately.\""),
("Disciplinary Review Committee", "紀律審查委員會", "處理違反準則案件的協會機制相關單位。", "違規後果。", "\"Serious breaches can be referred for disciplinary review by CFA Institute.\""),
("Professional Conduct Statement", "專業行為聲明", "會員／考生定期申報是否涉及相關調查或違規的聲明。", "年度更新。", "\"I file the Professional Conduct Statement each year as required.\""),
("Sanction", "處分", "對違規者可能採取的懲戒，如譴責、停權或撤銷資格。", "紀律結果。", "\"A public sanction can permanently damage an analyst's reputation.\""),
("Global Investment Performance Standards", "全球投資績效標準（全名）", "GIPS 的全稱，統一績效計算與呈報做法。", "正式文件。", "\"We present returns in accordance with the Global Investment Performance Standards.\""),
("Portability of Performance", "績效可攜性", "經理人轉換公司時，歷史績效在符合條件下方可繼續使用。", "團隊跳槽行銷。", "\"Portability of performance requires the decision-makers and records to move intact.\""),
("Model / Simulated Results", "模型／模擬績效", "非真實管理資金的績效；須顯著標示且不可與真實績效混淆。", "回測行銷。", "\"Label model results clearly—never mix simulated performance with live composites.\""),
("Temporary Ineffectiveness of Compliance", "合規短暫失效", "制度失靈時主管仍有責任迅速補正並限制活動。", "系統當機、監控缺口。", "\"During temporary ineffectiveness of compliance systems, halt sensitive trading.\""),
("Adequate Compliance System", "妥適合規制度", "主管須建立與業務複雜度相稱的監督機制。", "新業務線。", "\"An adequate compliance system scales with product complexity and headcount.\""),
("Reasonable Care", "合理注意", "以同業謹慎專業人士會採取的注意程度行事。", "盡職調查深度。", "\"Reasonable care means checking audited statements, not only marketing slides.\""),
("Due Diligence", "盡職調查", "投資前對標的、管理人或產品進行系統性查核。", "基金遴選、私募。", "\"Our due diligence covered operations, valuation, and compliance history.\""),
("Know Your Customer (KYC)", "認識你的客戶", "了解客戶身分、目標與背景，以支持適當性與防制洗錢。", "開戶流程。", "\"KYC isn't bureaucracy—it's how we prove suitability later.\""),
("Anti-Money Laundering (AML)", "防制洗錢", "偵測並通報可疑資金流動的法規與程序義務。", "大額現金、異常轉帳。", "\"AML red flags include unexplained third-party wires into the account.\""),
("Custody Rule", "保管規則", "關於誰可持有客戶資產及如何保障資產安全的規範要求。", "獨立保管人。", "\"The custody rule pushes us toward a qualified independent custodian.\""),
("Side-by-Side Management", "並行管理", "同時管理收費結構不同的帳戶（如對沖基金與長只基金）可能產生衝突。", "配置優先。", "\"Side-by-side management needs allocation policies to prevent favoritism.\""),
("Cross Trade", "交叉交易", "在客戶帳戶間直接買賣；須公平定價並符合最佳利益。", "降低市場衝擊。", "\"A cross trade can save costs if priced fairly for both clients.\""),
("Related-Party Transaction", "關係人交易", "與關係企業或關聯人士交易；須揭露並證明公平。", "集團產品。", "\"This related-party transaction needs independent pricing and clear disclosure.\""),
("Marketing Brochure Review", "文宣審查", "行銷材料發布前的合規審核，避免不實陳述。", "產品上架。", "\"Legal must finish the marketing brochure review before the roadshow.\""),
("Social Media Conduct", "社群媒體行為", "在社群平台的言論仍受不得誤導、保密與稱謂規則約束。", "貼文、直播荐股。", "\"Social media conduct still falls under misrepresentation and confidentiality rules.\""),
("Outside Business Activity", "外部業務活動", "與雇主業務以外的活動；須申報以防衝突。", "合規表格。", "\"Report every outside business activity, even unpaid board seats.\""),
]