# CFA L1 Fixed Income ~250
TERMS = [
    ("Bond", "債券", "發行人承諾依約支付利息並於到期償還本金的固定收益證券。", "用於描述政府或企業的借款工具。", "This bond pays interest every six months."),
    ("Issuer", "發行人", "為籌措資金而發行債務證券並承擔還本付息義務的實體。", "分析債券信用風險時辨識責任主體。", "The issuer plans to refinance the debt next year."),
    ("Bondholder", "債券持有人", "持有債券並對發行人享有契約性現金流請求權的投資人。", "討論投資人權利與清償順位時使用。", "The bondholder received the coupon payment on time."),
    ("Par Value", "票面價值", "債券到期時通常由發行人償還的本金金額，又稱面額。", "計算票息與到期償還金額。", "The bond has a par value of one thousand dollars."),
    ("Principal", "本金", "發行人借入且依契約須償還的金額。", "區分本金償還與利息支付。", "The principal will be repaid at maturity."),
    ("Maturity Date", "到期日", "發行人須償還剩餘本金並完成契約義務的日期。", "衡量債券期限與現金流時點。", "The maturity date is five years from today."),
    ("Tenor", "期限", "債務工具自發行日至到期日的原始期間長度。", "比較不同發行批次的期限。", "We selected a ten-year tenor for the new issue."),
    ("Coupon Rate", "票面利率", "每年票息相對於債券票面價值的百分比。", "由面額推算年度票息。", "The coupon rate is fixed at five percent."),
    ("Coupon Payment", "票息支付", "發行人依債券條款定期支付給持有人的利息現金流。", "建立債券現金流時間表。", "The next coupon payment arrives in June."),
    ("Coupon Frequency", "付息頻率", "債券每年支付票息的次數。", "調整每期票息與複利期間。", "The coupon frequency is semiannual."),

    ("Indenture", "債券契約", "規範發行人與債券持有人權利義務及債券條款的法律文件。", "查核擔保、限制條款與違約處理。", "Please review the indenture before buying the bond."),
    ("Trustee", "受託人", "代表債券持有人監督契約遵循並在違約時採取行動的機構。", "說明債權人權益的代理與執行。", "The trustee notified investors of the covenant breach."),
    ("Affirmative Covenant", "積極性限制條款", "要求發行人執行特定行為的契約承諾，例如提供報表或繳納稅款。", "評估發行人持續履約義務。", "The affirmative covenant requires audited statements."),
    ("Negative Covenant", "消極性限制條款", "限制發行人從事可能損害債權人利益之行為的契約條款。", "檢視舉債、資產處分或股利限制。", "The negative covenant limits additional borrowing."),
    ("Cross-Default Provision", "交叉違約條款", "發行人對其他債務違約時，使本債券亦可被視為違約的條款。", "評估違約事件的連鎖影響。", "The cross-default provision triggered an early review."),
    ("Pari Passu", "同等受償", "表示某債務與發行人其他同順位債務享有相同清償順位。", "比較無擔保債務的法律順位。", "These notes rank pari passu with existing senior debt."),
    ("Security", "擔保品", "為保障債務償還而設定權利的特定資產或財產。", "分析擔保債券的回收來源。", "Real estate serves as security for the bond."),
    ("Collateral", "抵押品", "借款人提供以支持債務、違約時可供債權人處分的資產。", "評估有擔保債務的損失程度。", "The lender inspected the collateral before closing."),
    ("Sinking Fund", "償債基金", "要求發行人依時程分期贖回部分債券或提撥資金的安排。", "降低到期一次償還的再融資風險。", "The sinking fund retires part of the issue annually."),
    ("Maintenance Covenant", "維持性條款", "要求發行人在存續期間持續符合特定財務比率或條件的條款。", "監控槓桿與償債能力。", "The maintenance covenant sets a leverage ceiling."),

    ("Fixed-Rate Bond", "固定利率債券", "票面利率在債券存續期間維持不變的債券。", "預估確定的定期票息。", "I prefer a fixed-rate bond for stable income."),
    ("Floating-Rate Note", "浮動利率票據", "票息依參考利率加減報價利差定期重設的債務工具。", "降低利率變動造成的價格敏感度。", "The floating-rate note resets every quarter."),
    ("Reference Rate", "參考利率", "浮動利率工具用來決定票息的市場基準利率。", "計算下一重設期的票息。", "The reference rate rose by twenty basis points."),
    ("Quoted Margin", "報價利差", "浮動利率票據票息中固定加在參考利率上的利差。", "由契約決定每期票息加碼。", "The quoted margin is one hundred basis points."),
    ("Zero-Coupon Bond", "零息債券", "不定期支付票息，通常折價發行並於到期按面額償還的債券。", "以買入價與到期價差取得報酬。", "The zero-coupon bond pays no periodic interest."),
    ("Step-Up Coupon Bond", "階升票息債券", "票面利率依預定時程逐步提高的債券。", "分析不同期間的契約票息。", "The step-up coupon increases after year three."),
    ("Deferred Coupon Bond", "遞延付息債券", "在初期延後票息支付，之後開始支付較高票息的債券。", "配合初期現金流不足的融資需求。", "The deferred coupon begins paying in two years."),
    ("Payment-in-Kind Bond", "實物支付債券", "允許發行人以新增債券而非現金支付部分或全部利息的債券。", "評估現金節省與本金累積風險。", "The company paid interest with additional notes."),
    ("Inflation-Linked Bond", "通膨連結債券", "本金或票息依指定物價指數調整的債券。", "提供對抗通膨風險的曝險。", "The inflation-linked bond protects purchasing power."),
    ("Capital-Indexed Bond", "本金指數連結債券", "本金按通膨指數調整，票息以調整後本金乘固定利率計算的債券。", "計算實質報酬與通膨補償。", "The capital-indexed bond adjusts its principal for inflation."),

    ("Bullet Bond", "到期一次還本債券", "本金在到期日一次全額償還的債券。", "與分期攤還結構比較再融資風險。", "The bullet bond repays all principal at maturity."),
    ("Amortizing Bond", "攤還債券", "存續期間按期償還部分本金，使未償本金逐步下降的債券。", "分析每期本金與利息現金流。", "The amortizing bond returns principal each year."),
    ("Fully Amortizing Bond", "完全攤還債券", "透過定期付款在到期前將本金與利息全部清償的債券。", "常見於房貸及其證券化商品。", "The loan is fully amortizing over twenty years."),
    ("Partially Amortizing Bond", "部分攤還債券", "存續期間償還部分本金，並在到期支付剩餘大額本金的債券。", "辨識到期氣球付款風險。", "The partially amortizing bond has a final balloon payment."),
    ("Perpetual Bond", "永續債券", "沒有到期日且理論上持續支付票息的債券。", "以永續年金概念進行估值。", "The perpetual bond has no scheduled maturity."),
    ("Bearer Bond", "無記名債券", "不登記所有人，持有人憑實體債券或息票主張付款的債券。", "理解歷史債券的所有權形式。", "The bearer bond belongs to whoever possesses it."),
    ("Registered Bond", "記名債券", "發行人或代理機構登記持有人身分並向其付款的債券。", "確認利息及本金付款對象。", "The registered bond records the investor's name."),
    ("Domestic Bond", "國內債券", "發行人在其本國市場以本國貨幣發行的債券。", "依發行市場與貨幣分類。", "The domestic bond was issued in the local market."),
    ("Foreign Bond", "外國債券", "外國發行人在某國國內市場以該市場貨幣發行的債券。", "辨識如揚基債券等跨國發行。", "The foreign bond is denominated in the host currency."),
    ("Eurobond", "歐洲債券", "在某貨幣所屬國家以外的市場發行、通常由國際承銷團銷售的債券。", "分類國際債券市場工具。", "The Eurobond was sold to investors across several countries."),

    ("Callable Bond", "可贖回債券", "賦予發行人在到期前依約定價格買回債券權利的債券。", "評估利率下降時的提前贖回風險。", "The issuer called the bond after rates fell."),
    ("Call Option", "贖回權", "由發行人持有、可在特定日期按特定價格贖回債券的嵌入式選擇權。", "拆解可贖回債券價值。", "The call option benefits the issuer when yields decline."),
    ("Call Price", "贖回價格", "發行人行使贖回權時支付給債券持有人的價格。", "計算被提前贖回的現金流。", "The call price is one hundred and two percent of par."),
    ("Call Protection", "贖回保護期", "限制發行人在指定初始期間內贖回債券的條款。", "衡量投資人免受近期再投資風險的期間。", "The bond offers five years of call protection."),
    ("Putable Bond", "可回售債券", "賦予持有人在到期前依約定價格賣回給發行人的權利之債券。", "評估利率上升或信用惡化時的保護。", "She exercised the put when market yields increased."),
    ("Put Option", "回售權", "由債券持有人持有、可要求發行人提前買回債券的嵌入式選擇權。", "拆解可回售債券價值。", "The put option increases the bond's value to investors."),
    ("Convertible Bond", "可轉換債券", "允許持有人依約定條件將債券轉換為發行人普通股的債券。", "同時分析債券底價與股權上漲潛力。", "The investor converted the bond into common shares."),
    ("Conversion Ratio", "轉換比率", "每單位可轉換債券可換得的普通股股數。", "計算轉換價值。", "The conversion ratio is twenty shares per bond."),
    ("Conversion Price", "轉換價格", "由債券面額除以轉換比率所得的隱含每股價格。", "比較市價以判斷轉換吸引力。", "The conversion price is fifty dollars per share."),
    ("Exchangeable Bond", "可交換債券", "可轉換為非發行人本身、通常為關係企業普通股的債券。", "區分可轉換債券的標的股份。", "The exchangeable bond converts into shares of a subsidiary."),

    ("Bond Price", "債券價格", "債券預期現金流按適當要求報酬率折現後的現值。", "估算債券公平價值。", "The bond price rose after yields declined."),
    ("Full Price", "全價", "包含自上次付息日起應計利息的債券結算價格，又稱髒價。", "計算買方實際支付金額。", "The full price includes accrued interest."),
    ("Flat Price", "淨價", "不含應計利息的債券報價，又稱乾淨價格。", "用於市場報價及跨日比較。", "The dealer quoted the flat price at ninety-eight."),
    ("Accrued Interest", "應計利息", "自上次付息日至結算日已累積、由買方支付給賣方的票息部分。", "由淨價推算全價。", "Accrued interest is added at settlement."),
    ("Day-Count Convention", "日數計算慣例", "規定利息期間實際天數與年度基礎天數的計算方法。", "計算應計利息及貨幣市場收益率。", "This bond uses the thirty-over-three-sixty convention."),
    ("Settlement Date", "交割日", "交易雙方完成證券與款項交換的日期。", "決定應計利息與所有權移轉。", "The settlement date is two business days after the trade."),
    ("Trade Date", "交易日", "買賣雙方達成債券交易協議的日期。", "區分成交與實際交割時點。", "We agreed on the price on the trade date."),
    ("Premium Bond", "溢價債券", "市場價格高於票面價值的債券，通常因票面利率高於市場要求報酬率。", "分析價格向面額收斂的效果。", "The premium bond trades above par."),
    ("Discount Bond", "折價債券", "市場價格低於票面價值的債券，通常因票面利率低於市場要求報酬率。", "分析資本利得與到期收斂。", "The discount bond trades below par."),
    ("Price Convergence", "價格收斂", "若未違約，債券價格隨到期日接近而趨向票面價值的現象。", "解釋折溢價逐期攤銷。", "Price convergence pulls the bond toward par."),

    ("Current Yield", "當期收益率", "年度票息除以債券目前全價或市場價格所得的收益率。", "快速衡量票息收入但忽略資本利得與時間價值。", "The current yield is the annual coupon divided by price."),
    ("Yield to Maturity", "到期殖利率", "使債券承諾現金流現值等於目前全價的單一折現率。", "假設持有至到期且票息按同率再投資。", "The yield to maturity is higher than the coupon rate."),
    ("Yield to Call", "贖回殖利率", "假設債券在指定首次或某贖回日被贖回時的內部報酬率。", "評估可贖回債券的可能報酬。", "We calculated the yield to call using the first call date."),
    ("Yield to Put", "回售殖利率", "假設持有人在指定回售日行使權利時的內部報酬率。", "評估可回售債券的最低持有期報酬。", "The yield to put assumes the investor exercises the option."),
    ("Yield to Worst", "最差殖利率", "在未違約前提下，各可能贖回或到期情境殖利率中的最低值。", "保守評估含選擇權債券的收益。", "The analyst reports the yield to worst."),
    ("Money-Weighted Return", "金額加權報酬率", "使投資所有現金流淨現值為零的內部報酬率，受現金流時點與金額影響。", "衡量投資人實際投入資金的績效。", "The money-weighted return reflects the timing of contributions."),
    ("Holding Period Return", "持有期報酬率", "持有期間收到的收入加價格變動，相對於期初投資價格的報酬率。", "衡量特定投資期間的總報酬。", "The holding period return includes coupon income and price gain."),
    ("Realized Yield", "實現殖利率", "依實際售價、持有期間及票息再投資率計得的投資報酬率。", "檢視實際結果與到期殖利率假設差異。", "The realized yield fell because reinvestment rates were lower."),
    ("Reinvestment Income", "再投資收益", "將收到的中間票息再投資所產生的額外收入。", "分解債券持有期總報酬。", "Reinvestment income increased when short-term rates rose."),
    ("Bond-Equivalent Yield", "債券等值收益率", "將週期收益率依一年兩期單利年化的報價慣例。", "比較不同付息頻率或貨幣市場工具。", "The bond-equivalent yield annualizes the semiannual rate."),

    ("Spot Rate", "即期利率", "適用於從今日至特定到期日之單一現金流的零息利率。", "逐筆折現債券各期現金流。", "Use the two-year spot rate for that cash flow."),
    ("Spot Curve", "即期利率曲線", "不同到期期限零息即期利率所形成的期限結構。", "為無套利債券估值提供折現率。", "The spot curve is upward sloping today."),
    ("Par Rate", "平價利率", "使新發行附息債券價格等於面額的票面利率。", "由即期曲線推導平價殖利率曲線。", "The par rate makes the bond trade at par."),
    ("Par Curve", "平價殖利率曲線", "各期限假設平價債券之票面利率所連成的曲線。", "比較市場各期限的平價融資成本。", "The par curve summarizes coupon rates for par bonds."),
    ("Forward Rate", "遠期利率", "由目前即期利率隱含、適用於未來某期間的利率。", "依無套利關係推導未來借貸價格。", "The forward rate applies to a loan starting next year."),
    ("Forward Curve", "遠期利率曲線", "一系列未來期間隱含遠期利率所形成的曲線。", "分析市場隱含的未來利率路徑。", "The forward curve steepened after the policy announcement."),
    ("Bootstrapping", "拔靴法", "利用較短期限工具逐步解出各期即期利率的程序。", "由平價債券價格建立即期曲線。", "We used bootstrapping to derive the spot rates."),
    ("Discount Factor", "折現因子", "將特定未來時點的一單位現金流換算為今日價值的乘數。", "由即期利率計算現值。", "Multiply the cash flow by its discount factor."),
    ("No-Arbitrage Pricing", "無套利定價", "以可複製現金流組合的成本決定資產價格，避免無風險獲利機會。", "使用即期利率逐期評價債券。", "No-arbitrage pricing values each cash flow separately."),
    ("Forward Pricing Model", "遠期定價模型", "透過即期利率間的複利關係計算隱含遠期利率的架構。", "檢查期限結構的一致性。", "The forward pricing model links spot and forward rates."),

    ("Yield Curve", "殖利率曲線", "在同一時點描繪相似信用風險債券殖利率與到期期限關係的曲線。", "分析利率期限結構。", "The yield curve changed after the central bank meeting."),
    ("Normal Yield Curve", "正常殖利率曲線", "長期殖利率高於短期殖利率的向上傾斜曲線。", "常見於市場預期成長或期限溢酬為正時。", "A normal yield curve slopes upward."),
    ("Inverted Yield Curve", "反轉殖利率曲線", "短期殖利率高於長期殖利率的向下傾斜曲線。", "常被用來討論緊縮政策與衰退預期。", "The yield curve inverted last month."),
    ("Flat Yield Curve", "平坦殖利率曲線", "短中長期殖利率大致相近的曲線。", "可能反映經濟週期或利率預期轉折。", "The yield curve became nearly flat."),
    ("Humped Yield Curve", "駝峰殖利率曲線", "中期殖利率高於短期與長期殖利率的曲線。", "描述特定期限供需或政策預期。", "The humped curve peaks at five years."),
    ("Bull Steepener", "多頭陡峭化", "短期殖利率下降幅度大於長期殖利率，使曲線變陡且債券價格上升。", "描述寬鬆預期下的曲線變動。", "A bull steepener followed the rate cut."),
    ("Bull Flattener", "多頭平坦化", "長期殖利率下降幅度大於短期殖利率，使曲線變平且價格普遍上升。", "描述長端強勁上漲。", "The recession forecast caused a bull flattener."),
    ("Bear Steepener", "空頭陡峭化", "長期殖利率上升幅度大於短期殖利率，使曲線變陡且價格下跌。", "描述通膨或期限溢酬上升。", "Higher inflation expectations produced a bear steepener."),
    ("Bear Flattener", "空頭平坦化", "短期殖利率上升幅度大於長期殖利率，使曲線變平且價格下跌。", "描述央行升息帶動短端上升。", "The policy hike triggered a bear flattener."),
    ("Term Structure of Interest Rates", "利率期限結構", "同類風險債務工具的利率或殖利率隨到期期限變化的關係。", "研究即期、遠期與殖利率曲線。", "The term structure reflects rates across maturities."),

    ("Pure Expectations Theory", "純預期理論", "主張長期利率由目前短期利率及預期未來短期利率決定，不含期限溢酬。", "解釋遠期利率與市場預期的關係。", "Pure expectations theory assumes no term premium."),
    ("Liquidity Preference Theory", "流動性偏好理論", "認為投資人偏好短期證券，持有長期債券需獲得正的流動性或期限溢酬。", "解釋曲線通常向上傾斜。", "Liquidity preference theory adds a positive term premium."),
    ("Segmented Markets Theory", "市場區隔理論", "認為各期限市場由偏好特定期限的借貸雙方供需獨立決定。", "解釋不同期限可能各自定價。", "Segmented markets theory treats maturities as separate markets."),
    ("Preferred Habitat Theory", "偏好棲息地理論", "認為投資人偏好特定期限，但獲得足夠溢酬時願意移至其他期限。", "結合期限偏好與可移動性解釋曲線。", "Preferred habitat theory allows investors to change maturities."),
    ("Term Premium", "期限溢酬", "投資人持有較長期債券所要求的額外報酬，補償利率與流動性風險。", "分解長期殖利率的風險補償。", "The term premium increased for long bonds."),
    ("Inflation Premium", "通膨溢酬", "名目利率中補償預期通膨造成購買力損失的部分。", "由名目殖利率分析通膨預期。", "The inflation premium rose with expected prices."),
    ("Default Risk Premium", "違約風險溢酬", "投資人因借款人可能無法依約付款而要求的額外報酬。", "比較信用債與無風險債殖利率。", "The default risk premium widened after the downgrade."),
    ("Liquidity Premium", "流動性溢酬", "投資人為承擔難以迅速且低成本交易的風險所要求的額外報酬。", "分析交易不活絡債券的殖利率。", "The illiquid issue carries a liquidity premium."),
    ("Maturity Effect", "到期效應", "其他條件相同下，債券價格對殖利率變動的敏感度通常隨到期期間增加而提高。", "比較長短期債券的利率風險。", "The maturity effect makes the long bond more volatile."),
    ("Coupon Effect", "票息效應", "其他條件相同下，低票息債券通常比高票息債券具有更高利率敏感度。", "比較不同票面利率債券的價格風險。", "The coupon effect gives the low-coupon bond more duration."),

    ("Interest Rate Risk", "利率風險", "市場利率變動導致債券價格或投資價值變動的風險。", "衡量固定收益部位的主要市場風險。", "Long-term bonds carry greater interest rate risk."),
    ("Macaulay Duration", "麥考利存續期間", "以各期現金流現值權重計算的收款時間加權平均，單位為年。", "衡量債券現金流的平均回收時點。", "The Macaulay duration is six years."),
    ("Modified Duration", "修正存續期間", "麥考利存續期間除以一加每期殖利率，用以近似價格對殖利率的百分比敏感度。", "估計殖利率小幅變動造成的價格變化。", "Modified duration estimates the percentage price change."),
    ("Effective Duration", "有效存續期間", "利用利率上、下移情境重新估值，衡量含選擇權債券對基準曲線變動的敏感度。", "評估現金流會隨利率改變的債券。", "Use effective duration for the callable bond."),
    ("Approximate Modified Duration", "近似修正存續期間", "以殖利率上下小幅變動所得價格差，近似無選擇權債券的價格敏感度。", "無解析存續期間時採情境估算。", "We estimated approximate modified duration from two prices."),
    ("Dollar Duration", "金額存續期間", "修正存續期間乘債券全價，表示殖利率變動一單位造成的價格金額變化。", "衡量部位利率風險的貨幣金額。", "Dollar duration converts sensitivity into currency terms."),
    ("Price Value of a Basis Point", "一基點價格價值", "殖利率變動一個基點時債券價格的近似金額變化，又稱PVBP或DV01。", "配置或避險部位的微小利率風險。", "The price value of a basis point is eighty dollars."),
    ("Key Rate Duration", "關鍵利率存續期間", "只變動殖利率曲線某特定期限節點時，債券價格的敏感度。", "衡量非平行曲線變動風險。", "Key rate duration reveals exposure at ten years."),
    ("Portfolio Duration", "投資組合存續期間", "在適當假設下，以市場價值權重加總各債券存續期間所得的組合敏感度。", "估計固定收益投資組合的利率風險。", "The portfolio duration is the weighted average of holdings."),
    ("Duration Gap", "存續期間缺口", "資產與負債存續期間經規模調整後的差異，反映權益對利率變動的敏感度。", "資產負債管理中衡量利率錯配。", "The bank reduced its duration gap."),

    ("Convexity", "凸性", "描述債券價格與殖利率非線性關係曲率的指標，可改善存續期間估計。", "估計較大利率變動下的價格變化。", "Convexity improves the duration-based estimate."),
    ("Effective Convexity", "有效凸性", "透過利率上下移並重新估算現金流，衡量含選擇權債券的價格曲率。", "分析可贖回或可回售債券。", "Effective convexity accounts for changing cash flows."),
    ("Positive Convexity", "正凸性", "殖利率下降時價格上升幅度大於同幅殖利率上升時價格下降幅度的特性。", "說明一般無選擇權債券的有利曲率。", "A straight bond usually has positive convexity."),
    ("Negative Convexity", "負凸性", "利率下降時因現金流縮短或上漲受限，使價格曲線向內彎曲的特性。", "常見於可贖回債券與房貸證券。", "The callable bond shows negative convexity at low yields."),
    ("Duration-Convexity Estimate", "存續期間凸性估計", "以存續期間的一階效果加上凸性的二階效果估計債券價格變動。", "提升殖利率變動較大時的估價準確度。", "The duration-convexity estimate closely matched the new price."),
    ("Convexity Adjustment", "凸性調整", "在存續期間價格估計中加入與殖利率變動平方相關的修正項。", "修正線性估計誤差。", "Add the convexity adjustment for a large yield move."),
    ("Yield Volatility", "殖利率波動度", "市場殖利率隨時間變動的幅度，會影響含選擇權債券價值。", "選擇權調整利差與有效存續期間分析。", "Higher yield volatility increased the option value."),
    ("Parallel Shift", "平行移動", "殖利率曲線所有期限利率以相同基點幅度變動的情境。", "基本存續期間衡量通常採此假設。", "We tested a parallel shift of fifty basis points."),
    ("Nonparallel Shift", "非平行移動", "殖利率曲線不同期限利率變動幅度不一致的情境。", "使用關鍵利率存續期間分析。", "A nonparallel shift changed the curve's slope."),
    ("Immunization", "免疫策略", "透過匹配資產與負債的現值及利率敏感度，降低利率變動對目標價值的影響。", "管理特定未來負債的固定收益策略。", "The pension fund uses immunization for its liabilities."),

    ("Credit Risk", "信用風險", "借款人未依契約支付本金或利息，或信用惡化造成損失的風險。", "分析公司債要求報酬率。", "Credit risk is higher for the weaker issuer."),
    ("Default Risk", "違約風險", "發行人無法或不願按時履行契約付款義務的可能性。", "估計違約機率與潛在損失。", "The market now sees greater default risk."),
    ("Credit Migration Risk", "信用遷移風險", "信用評等上調或下調導致債券價值變動的風險。", "評估評等變化對利差與價格的影響。", "Credit migration risk increased before the review."),
    ("Credit Rating", "信用評等", "評等機構對債務工具或發行人相對信用風險的意見。", "作為信用分析的外部參考而非保證。", "The bond received an investment-grade credit rating."),
    ("Investment Grade", "投資等級", "通常指評等為BBB減或Baa3以上、違約風險相對較低的債務。", "依評等區分債券信用類別。", "The mandate allows only investment-grade bonds."),
    ("High-Yield Bond", "高收益債券", "評等低於投資等級且通常提供較高殖利率以補償較高信用風險的債券。", "分析投機等級信用市場。", "The high-yield bond offers a sizable spread."),
    ("Probability of Default", "違約機率", "借款人在指定期間內發生違約事件的可能性。", "計算預期信用損失。", "The probability of default rose after earnings weakened."),
    ("Loss Given Default", "違約損失率", "違約時曝險金額中無法回收的比例，等於一減回收率。", "與違約機率共同估算預期損失。", "Loss given default depends on collateral and seniority."),
    ("Recovery Rate", "回收率", "違約後債權人可收回的曝險金額比例。", "評估違約損失與擔保價值。", "Senior secured debt usually has a higher recovery rate."),
    ("Expected Loss", "預期損失", "通常以違約機率、違約損失率及違約曝險額相乘估計的平均信用損失。", "量化信用風險成本。", "Expected loss combines default probability and severity."),

    ("Seniority", "清償順位", "債權在發行人資本結構中相對於其他請求權的受償優先次序。", "判斷違約時可能回收程度。", "Seniority affects recovery in liquidation."),
    ("Senior Secured Debt", "優先有擔保債務", "由特定資產擔保且清償順位高於次順位債務的債務。", "評估較高順位與擔保帶來的信用保護。", "Senior secured debt has a claim on pledged assets."),
    ("Senior Unsecured Debt", "優先無擔保債務", "無特定抵押品但順位高於次順位債務的債務。", "分析一般債權對發行人資產的請求。", "The company issued senior unsecured notes."),
    ("Subordinated Debt", "次順位債務", "在優先債務獲償後才受償的債務。", "評估較低回收率與較高信用利差。", "Subordinated debt absorbs losses before senior debt."),
    ("Structural Subordination", "結構性次順位", "控股公司債權人對子公司資產的請求落後於子公司自身債權人的情形。", "分析集團法律實體間的受償順序。", "Holding-company debt faces structural subordination."),
    ("Priority of Claims", "求償優先順序", "清算時各類債權與股權依法律及契約獲得分配的次序。", "估計不同證券的回收率。", "Priority of claims determines who is paid first."),
    ("Capacity", "償債能力", "借款人以營運現金流履行債務義務的能力，是信用分析核心。", "信用分析五大要素之一。", "We assessed the borrower's capacity to service debt."),
    ("Capital", "資本實力", "借款人的權益基礎與承擔損失能力，反映財務緩衝。", "評估槓桿與債權人保護。", "Strong capital provides a cushion for creditors."),
    ("Character", "信用意願", "借款人管理階層履約紀錄、誠信與還款意願的質性評估。", "補充量化信用指標。", "The lender questioned management's character after the disclosure."),
    ("Conditions", "外部條件", "影響借款人償債能力的產業、經濟與貸款用途等外部因素。", "進行情境與產業信用分析。", "Economic conditions weakened the borrower's outlook."),

    ("Leverage Ratio", "槓桿比率", "衡量債務相對於權益、資產或盈餘規模的比率。", "評估發行人債務負擔。", "The leverage ratio rose after the acquisition."),
    ("Debt-to-EBITDA", "債務對EBITDA比率", "總債務相對於息稅折舊攤銷前盈餘的倍數。", "比較企業償還債務所需的盈餘能力。", "Debt-to-EBITDA fell below three times."),
    ("Interest Coverage Ratio", "利息保障倍數", "以營業利益或EBITDA除以利息費用，衡量支付利息的能力。", "檢視現金流對利息負擔的緩衝。", "The interest coverage ratio improved this quarter."),
    ("Debt Service Coverage Ratio", "償債保障倍數", "可用於償債的現金流除以利息與應付本金總額。", "評估整體債務支付能力。", "The project maintains a healthy debt service coverage ratio."),
    ("Cash Flow Stability", "現金流穩定性", "企業營運現金流在不同期間與景氣情境下的可預測程度。", "判斷債務服務能力的可靠性。", "Stable cash flow supports the issuer's rating."),
    ("Business Risk", "營運風險", "產業競爭、需求、成本及營運特性造成企業盈餘不確定性的風險。", "信用分析中先評估產業與公司基本面。", "Business risk is high in this cyclical industry."),
    ("Financial Risk", "財務風險", "使用債務融資與固定付款義務造成股東及債權人風險增加的程度。", "結合槓桿與流動性分析信用。", "Financial risk increased after the debt-funded purchase."),
    ("Covenant Quality", "限制條款品質", "債券契約對債權人保護範圍、嚴格程度及可執行性的整體評估。", "比較不同債券的契約保護。", "Investors demanded stronger covenant quality."),
    ("Notching", "評等級距調整", "依債務順位、擔保與回收前景，將特定債券評等相對發行人評等調高或調低。", "區分發行人評等與個別債務評等。", "The agency applied notching to the subordinated issue."),
    ("Credit Watch", "信用觀察名單", "評等機構因重大事件而對可能近期調整評等的發行人或債務所作標示。", "監控潛在評等變動。", "The issuer was placed on credit watch negative."),

    ("Yield Spread", "殖利率利差", "某債券殖利率與選定基準殖利率之差。", "衡量信用、流動性及其他風險補償。", "The yield spread widened by thirty basis points."),
    ("Benchmark Spread", "基準利差", "債券殖利率與相近到期基準政府債券殖利率之差。", "快速比較信用債相對價值。", "The benchmark spread is quoted over the ten-year government bond."),
    ("G-Spread", "政府債券利差", "債券殖利率與以政府債券殖利率插值得到之相同期限利率的差。", "相較單一基準債券更精確配對期限。", "The G-spread uses an interpolated government yield."),
    ("I-Spread", "交換利率利差", "債券殖利率與相同期限標準利率交換固定利率之差。", "以交換曲線作為市場基準。", "The I-spread is measured over the swap rate."),
    ("Z-Spread", "零波動利差", "加在整條即期利率曲線各期限上，使債券現金流現值等於市場價格的固定利差。", "評價無嵌入式選擇權債券的整體利差。", "The Z-spread discounts every cash flow consistently."),
    ("Option-Adjusted Spread", "選擇權調整利差", "在利率路徑模型中扣除嵌入式選擇權影響後的利差。", "比較含選擇權與不含選擇權債券的信用補償。", "The option-adjusted spread removes the call option's effect."),
    ("Credit Spread", "信用利差", "信用風險債券相對於低風險基準所提供的額外殖利率。", "反映預期損失、風險溢酬與流動性。", "Credit spreads tightened after strong earnings."),
    ("Spread Risk", "利差風險", "信用或流動性利差變動導致債券價格變動的風險。", "管理公司債相對政府債的價格波動。", "Spread risk remains even if government yields are unchanged."),
    ("Spread Duration", "利差存續期間", "債券價格對信用利差小幅變動的百分比敏感度。", "估計利差擴大或縮小的價格影響。", "Spread duration measures sensitivity to spread changes."),
    ("Basis Point", "基點", "利率或殖利率的萬分之一，即百分之零點零一。", "報價利率與利差的微小變動。", "The spread narrowed by five basis points."),

    ("Securitization", "證券化", "將產生現金流的資產集合並透過特殊目的機構發行證券的融資過程。", "把貸款轉化為可交易固定收益證券。", "Securitization converts loans into marketable securities."),
    ("Special Purpose Entity", "特殊目的實體", "為持有資產並發行證券而設立、與資產出售人法律隔離的實體。", "降低發起人破產對資產池的影響。", "The special purpose entity owns the receivables."),
    ("Bankruptcy Remote", "破產隔離", "特殊目的實體及其資產與發起人破產風險在法律上分離的設計。", "提升證券化資產對投資人的保護。", "The structure is designed to be bankruptcy remote."),
    ("True Sale", "真實出售", "資產由發起人有效轉讓給特殊目的實體，而非僅作擔保融資。", "確保資產不被納入發起人破產財產。", "Legal counsel confirmed the transfer as a true sale."),
    ("Asset-Backed Security", "資產擔保證券", "由汽車貸款、信用卡應收款等非房貸資產池現金流支持的證券。", "投資消費或商業應收款證券化商品。", "The asset-backed security is backed by auto loans."),
    ("Mortgage-Backed Security", "房貸擔保證券", "由住宅或商業不動產抵押貸款池的本金與利息支持的證券。", "分析提前還款與延長風險。", "The mortgage-backed security receives monthly mortgage payments."),
    ("Collateralized Debt Obligation", "擔保債務憑證", "以債券、貸款或其他債務組合為擔保並分層發行的結構型證券。", "依分層承擔資產池信用風險。", "The collateralized debt obligation holds corporate loans."),
    ("Collateralized Loan Obligation", "擔保貸款憑證", "主要以槓桿貸款池為擔保並分層發行的CDO。", "取得企業貸款池不同風險層級曝險。", "The collateralized loan obligation purchased syndicated loans."),
    ("Originator", "發起人", "創造貸款或應收款並可能將其出售給證券化實體的機構。", "辨識資產來源與承作標準。", "The originator sold the loans to the trust."),
    ("Servicer", "服務機構", "負責向借款人收款、管理逾期並將現金轉交證券化信託的機構。", "評估證券化交易的營運品質。", "The servicer collects monthly payments from borrowers."),

    ("Tranche", "分層", "證券化交易中具有不同受償順位、風險及報酬特性的證券層級。", "依投資人風險偏好分配現金流。", "The senior tranche receives payments first."),
    ("Senior Tranche", "優先層", "在結構型商品中優先獲得現金流並最後承擔損失的分層。", "提供較低信用風險與較低收益。", "The senior tranche has the highest credit rating."),
    ("Mezzanine Tranche", "夾層", "受償順位介於優先層與權益層之間的分層。", "承擔中等程度信用風險。", "The mezzanine tranche offers a higher coupon."),
    ("Equity Tranche", "權益層", "最先承擔資產池損失且最後收取剩餘現金流的分層。", "取得高風險的剩餘收益曝險。", "The equity tranche absorbs the first losses."),
    ("Waterfall", "現金流瀑布", "規定資產池現金流依優先順序分配給費用及各證券分層的機制。", "分析結構型商品付款順序。", "The waterfall directs cash to senior investors first."),
    ("Credit Tranching", "信用分層", "透過不同損失承擔順位，將資產池信用風險重新分配給各分層。", "創造不同信用評等的證券。", "Credit tranching protects the senior notes."),
    ("Time Tranching", "時間分層", "依本金付款先後順序，把提前還款與到期風險分配給不同分層。", "常見於CMO結構。", "Time tranching redirects principal among bond classes."),
    ("Overcollateralization", "超額擔保", "資產池價值高於所發行證券本金的信用增強方式。", "以額外資產吸收初始損失。", "Overcollateralization provides a cushion against defaults."),
    ("Excess Spread", "超額利差", "資產池利息收入扣除證券利息、費用及損失後的剩餘金額。", "作為證券化內部信用增強。", "Excess spread covered the month's credit losses."),
    ("Reserve Account", "準備金帳戶", "預先提撥或由超額現金流累積、用於彌補資產池短缺的帳戶。", "提供結構型證券信用支持。", "The reserve account covered a temporary payment shortfall."),

    ("Credit Enhancement", "信用增強", "透過內部或外部機制降低證券投資人預期信用損失的安排。", "提升證券化分層的信用品質。", "Credit enhancement helped the senior notes earn a top rating."),
    ("Internal Credit Enhancement", "內部信用增強", "由交易本身提供的保護，如次順位、超額擔保及超額利差。", "不依賴外部第三方承諾。", "Subordination is a form of internal credit enhancement."),
    ("External Credit Enhancement", "外部信用增強", "由第三方提供的保證、信用狀或保險等信用支持。", "降低投資人對資產池違約的曝險。", "A bank guarantee provides external credit enhancement."),
    ("Subordination", "次順位安排", "使較低順位分層先吸收損失，以保護較高順位分層的結構。", "證券化常見的內部信用增強。", "Subordination shields the senior tranche from initial losses."),
    ("Prepayment Risk", "提前還款風險", "借款人較預期更早償還本金，使投資人須以較低利率再投資的風險。", "分析房貸擔保證券現金流。", "Prepayment risk rises when mortgage rates fall."),
    ("Contraction Risk", "縮短風險", "利率下降時提前還款加速，導致證券平均期限縮短的風險。", "評估MBS在降息環境下的表現。", "Contraction risk shortened the security's life."),
    ("Extension Risk", "延長風險", "利率上升時提前還款放緩，導致證券平均期限延長的風險。", "評估MBS在升息環境下的敏感度。", "Extension risk increased as refinancing slowed."),
    ("Prepayment Rate", "提前還款率", "資產池未償本金在一段期間內被提前償還的比率。", "預測MBS本金現金流。", "The prepayment rate fell after mortgage rates rose."),
    ("Conditional Prepayment Rate", "條件提前還款率", "將單月提前還款率年化後表示的房貸池提前還款速度。", "比較不同房貸池的提前還款假設。", "The conditional prepayment rate reached eight percent."),
    ("Single Monthly Mortality", "單月清償率", "某月期初本金扣除排定攤還後，被提前償還的本金比例。", "由月度資料衡量提前還款。", "Single monthly mortality measures one month's prepayments."),

    ("Pass-Through Security", "轉手證券", "將資產池收到的本金與利息扣除費用後按比例轉付投資人的證券。", "最基本的房貸證券化形式。", "The pass-through security distributes monthly cash flows."),
    ("Agency Mortgage-Backed Security", "機構房貸擔保證券", "由政府機構或政府贊助企業發行或保證的房貸擔保證券。", "區分機構與非機構MBS信用風險。", "The agency mortgage-backed security carries a guarantee."),
    ("Non-Agency Mortgage-Backed Security", "非機構房貸擔保證券", "未獲政府機構或政府贊助企業保證的房貸擔保證券。", "主要依資產品質與信用增強分析。", "The non-agency mortgage-backed security depends on private credit support."),
    ("Residential Mortgage-Backed Security", "住宅房貸擔保證券", "以住宅不動產抵押貸款池為支持的證券。", "分析借款人提前還款與違約行為。", "The residential mortgage-backed security contains home loans."),
    ("Commercial Mortgage-Backed Security", "商用房貸擔保證券", "以辦公室、零售或其他商用不動產房貸池支持的證券。", "著重物業現金流、LTV與DSCR。", "The commercial mortgage-backed security is backed by office loans."),
    ("Collateralized Mortgage Obligation", "擔保房貸債務憑證", "將房貸轉手證券現金流重新分配至不同到期與提前還款特性的分層。", "透過時間分層管理提前還款風險。", "The collateralized mortgage obligation has several bond classes."),
    ("Planned Amortization Class", "計畫攤還層", "在提前還款速度落於指定區間時，依預定本金時程收款的CMO分層。", "提供較穩定的平均存續期間。", "The planned amortization class follows a principal schedule."),
    ("Support Tranche", "支援層", "吸收提前還款速度變動以保護PAC本金時程的CMO分層。", "承擔較高縮短與延長風險。", "The support tranche absorbs prepayment variability."),
    ("Average Life", "平均存續年限", "以本金償還額加權計算的平均收回本金時間。", "比較攤還型及證券化商品期限。", "The average life shortened as prepayments accelerated."),
    ("Weighted Average Coupon", "加權平均票息", "以未償本金加權計算資產池內貸款票面利率的平均值。", "描述房貸或貸款池利息特徵。", "The weighted average coupon of the pool is four percent."),

    ("Money Market", "貨幣市場", "交易原始到期通常不超過一年的短期債務工具之市場。", "管理短期融資與流動性。", "The firm raised cash in the money market."),
    ("Treasury Bill", "國庫券", "政府發行、通常以折價方式出售且一年內到期的零息工具。", "作為短期低信用風險基準。", "The treasury bill matures in ninety days."),
    ("Commercial Paper", "商業本票", "企業發行的短期、通常無擔保之貨幣市場債務。", "支應營運資金與短期融資。", "The company issued commercial paper for working capital."),
    ("Certificate of Deposit", "定期存單", "銀行接受定期存款並承諾在到期支付本金與利息的工具。", "投資銀行短期信用曝險。", "The certificate of deposit matures next month."),
    ("Banker's Acceptance", "銀行承兌匯票", "由銀行承諾在未來日期付款、常用於國際貿易融資的匯票。", "降低買賣雙方的交易信用風險。", "The exporter sold the banker's acceptance at a discount."),
    ("Negotiable Certificate of Deposit", "可轉讓定期存單", "可在次級市場交易、通常面額較大的銀行定期存款憑證。", "機構投資人短期資金配置。", "The negotiable certificate of deposit was sold before maturity."),
    ("Eurodollar Deposit", "歐洲美元存款", "存放於美國境外銀行的美元定期存款。", "國際貨幣市場美元融資。", "The bank placed funds in a Eurodollar deposit."),
    ("Repurchase Agreement", "附買回協議", "一方出售證券並承諾日後按約定價格買回的短期擔保融資。", "以高品質證券作抵押取得短期資金。", "The dealer borrowed overnight through a repurchase agreement."),
    ("Reverse Repurchase Agreement", "附賣回協議", "從現金提供者角度，買入證券並同意日後賣回的交易。", "進行短期擔保放款。", "The fund entered a reverse repurchase agreement."),
    ("Repo Rate", "附買回利率", "附買回交易中由買回價與出售價差所隱含的融資利率。", "比較短期擔保融資成本。", "The repo rate declined in overnight trading."),

    ("Repo Margin", "附買回保證金", "擔保品市場價值高於所貸現金的百分比，用來保護現金提供者。", "管理擔保品價格下跌風險。", "The lender required a larger repo margin."),
    ("Haircut", "折扣率", "擔保品市場價值相對可借款金額所扣除的比例。", "決定附買回交易可融資金額。", "A five percent haircut applies to the collateral."),
    ("Overnight Repo", "隔夜附買回", "期限為一個工作日的附買回交易。", "滿足每日短期流動性需求。", "The bank funded the position with an overnight repo."),
    ("Term Repo", "定期附買回", "到期日超過一日且事先確定的附買回交易。", "鎖定一段期間的擔保融資。", "The dealer arranged a one-month term repo."),
    ("Open Repo", "開放式附買回", "沒有固定到期日、任一方可依通知終止的附買回交易。", "提供彈性的持續短期融資。", "The open repo continues until either party terminates it."),
    ("Discount Rate", "折價收益率", "以面額為基礎並按特定年度天數將折價年化的貨幣市場報價。", "常用於國庫券報價但低估投資報酬。", "The bill is quoted on a discount rate basis."),
    ("Add-On Rate", "加成利率", "以初始投資金額為基礎計算利息並年化的貨幣市場利率。", "比較存單等工具的報酬。", "The deposit pays interest on an add-on rate basis."),
    ("Money Market Yield", "貨幣市場收益率", "將持有期報酬以三百六十天年度及購買價格為基礎年化的收益率。", "把折價工具轉為較可比較的報價。", "The money market yield uses the purchase price as its base."),
    ("Effective Annual Yield", "有效年收益率", "考慮一年內複利效果後的年度實際報酬率。", "比較不同複利頻率的投資。", "The effective annual yield includes compounding."),
    ("Holding Period Yield", "持有期收益率", "期末收回金額減期初投資，再除以期初投資所得的期間報酬。", "將短期工具報酬轉換為年化指標前先計算。", "The holding period yield covers the ninety-day investment."),

    ("Floating-Rate Coupon", "浮動票息", "依參考利率加報價利差，在每個重設日重新決定的票息。", "計算浮動利率票據現金流。", "The floating-rate coupon resets next week."),
    ("Reset Date", "利率重設日", "浮動利率工具依當時參考利率決定下一期票息的日期。", "追蹤票息調整時點。", "The reset date occurs at the start of each quarter."),
    ("Reset Frequency", "重設頻率", "浮動利率票息在一年內重新設定的次數。", "衡量票息追隨市場利率的速度。", "The reset frequency is monthly."),
    ("Cap", "利率上限", "限制浮動票息或利率不得超過特定水準的契約條款。", "保護發行人免受利率過度上升。", "The cap limits the coupon to seven percent."),
    ("Floor", "利率下限", "規定浮動票息或利率不得低於特定水準的契約條款。", "保護投資人的最低利息收入。", "The floor keeps the coupon above two percent."),
    ("Collar", "利率上下限", "同時設置浮動利率上限與下限的結構。", "把票息限制在預定區間內。", "The collar keeps the rate between two and six percent."),
    ("Inverse Floater", "反向浮動利率票據", "票息隨參考利率上升而下降、隨參考利率下降而上升的票據。", "取得對利率變動的槓桿反向曝險。", "The inverse floater's coupon fell as rates rose."),
    ("Capped Floater", "設有上限的浮動利率票據", "浮動票息受到最高票息限制的票據。", "評估投資人放棄的利率上升利益。", "The capped floater stopped resetting above six percent."),
    ("Floored Floater", "設有下限的浮動利率票據", "浮動票息享有最低票息保障的票據。", "評估利率下降時的收益保護。", "The floored floater still pays at least two percent."),
    ("Discount Margin", "折現利差", "使浮動利率票據預期現金流現值等於市場價格、加於參考利率的利差。", "衡量浮動利率票據要求報酬與相對價值。", "The discount margin widened after the issuer was downgraded."),

    ("Reinvestment Risk", "再投資風險", "中間現金流可能無法按原先假設的利率再投資之風險。", "評估高票息債券及可贖回債券報酬。", "Falling rates increased the bond's reinvestment risk."),
    ("Call Risk", "贖回風險", "發行人在不利於投資人的時點提前贖回債券所造成的風險。", "衡量可贖回債券的上漲限制。", "Call risk is greatest when rates decline."),
    ("Put Benefit", "回售權利益", "持有人可按約定價格提前賣回債券所提供的價值與下檔保護。", "解釋可回售債券價格較高、殖利率較低。", "The put benefit protects investors when yields rise."),
    ("Liquidity Risk", "流動性風險", "無法迅速以接近公平價值的價格出售債券之風險。", "評估買賣價差與市場深度。", "Liquidity risk is high for the small issue."),
    ("Inflation Risk", "通膨風險", "通膨上升使固定名目現金流實質購買力下降的風險。", "比較名目債券與通膨連結債券。", "Inflation risk erodes fixed coupon payments."),
    ("Event Risk", "事件風險", "併購、監管、災害或其他突發事件使發行人信用急遽惡化的風險。", "進行公司債壓力測試。", "The leveraged takeover created significant event risk."),
    ("Currency Risk", "匯率風險", "債券計價貨幣相對投資人本位貨幣變動造成報酬不確定性的風險。", "評估外幣債券投資。", "Currency risk reduced the investor's home-currency return."),
    ("Volatility Risk", "波動度風險", "利率波動度變化影響嵌入式選擇權與債券價值的風險。", "分析可贖回、可回售與MBS。", "Higher volatility risk lowered the callable bond's value."),
    ("Model Risk", "模型風險", "估值模型、參數或假設不正確而導致錯誤定價或風險衡量的可能性。", "評估複雜固定收益商品。", "Model risk is material for structured securities."),
    ("Legal Risk", "法律風險", "契約無法執行、法規改變或法律結構有缺陷造成損失的風險。", "審查債券契約與證券化真實出售。", "Legal risk could weaken the collateral claim."),

    ("Interest Rate Tree", "利率樹", "以離散節點表示未來可能短期利率路徑的模型。", "評價含嵌入式選擇權債券。", "The analyst used an interest rate tree to value the call."),
    ("Binomial Model", "二項式模型", "每期假設狀態向上或向下演變的離散時間估值模型。", "建立無套利利率樹並反向估值。", "The binomial model produced two rates at each step."),
    ("Backward Induction", "反向歸納法", "從到期現金流開始，沿模型節點逐期折現回今日的估值方法。", "計算含選擇權債券節點價值。", "Backward induction starts from the final cash flows."),
    ("Path Dependency", "路徑相依性", "證券現金流或價值不只取決於終點，也取決於利率或資產價格經過路徑的特性。", "分析MBS與某些結構型商品。", "Mortgage prepayments create path dependency."),
    ("Embedded Option", "嵌入式選擇權", "包含在債券契約內、使發行人或持有人可改變現金流的權利。", "評估可贖回、可回售或可轉換債券。", "The embedded option changes the bond's cash flows."),
    ("Straight Bond", "普通債券", "不含嵌入式選擇權、依固定契約支付本金與利息的債券。", "作為含權債券的基礎價值。", "The straight bond has no call or put feature."),
    ("Option Cost", "選擇權成本", "債券嵌入式選擇權對投資人價值或利差造成的影響。", "由Z利差與OAS差異理解發行人贖回權成本。", "The option cost explains the gap between Z-spread and OAS."),
    ("Callable Bond Value", "可贖回債券價值", "普通債券價值減去發行人持有的贖回權價值。", "拆解可贖回債券定價。", "Callable bond value falls when the call option becomes more valuable."),
    ("Putable Bond Value", "可回售債券價值", "普通債券價值加上投資人持有的回售權價值。", "拆解可回售債券定價。", "Putable bond value includes the investor's put option."),
    ("Option-Adjusted Price", "選擇權調整價格", "在利率路徑模型下考慮嵌入式選擇權行使後得到的債券估值。", "比較模型價值與市場價格。", "The option-adjusted price reflects likely call behavior."),
]
