# CFA L1 FSA ~300
TERMS = [
    ("Financial reporting", "財務報導", "企業向外部使用者提供財務資訊的程序，主要成果為通用目的財務報表。", "理解報導架構", "Investors rely on financial reporting to assess the company."),
    ("Financial statements", "財務報表", "以結構化方式呈現企業財務狀況、績效與現金流量的一組報表。", "公司整體分析", "The analyst reviewed the financial statements before valuing the stock."),
    ("Notes to financial statements", "財務報表附註", "附註揭露會計政策、估計與報表項目的補充細節，屬完整財報的一部分。", "補充揭露分析", "Please read the notes to understand the pension assumptions."),
    ("Management commentary", "管理階層評論", "管理階層對營運成果、風險及未來展望的敘述性說明，通常未經與財報相同程度的查核。", "評估管理觀點", "Management commentary explains why margins declined."),
    ("Auditor's report", "查核報告", "獨立會計師對財報是否依適用準則允當表達所出具的意見。", "判斷財報可靠性", "The auditor's report contained an unmodified opinion."),
    ("Unmodified opinion", "無修正式意見", "查核人員認為財報在所有重大方面均依適用架構允當表達。", "辨識正常查核結果", "An unmodified opinion generally increases confidence in the statements."),
    ("Qualified opinion", "保留意見", "除特定重大但非廣泛影響事項外，財報仍允當表達。", "辨識查核警訊", "The qualified opinion related to inventory valuation."),
    ("Adverse opinion", "否定意見", "財報存在重大且廣泛的不實表達，因而未允當表達。", "重大風險判讀", "An adverse opinion is a serious warning to investors."),
    ("Disclaimer of opinion", "無法表示意見", "查核人員因證據不足等原因無法取得形成意見的基礎。", "評估查核限制", "The auditor issued a disclaimer of opinion after a severe scope limitation."),
    ("International Financial Reporting Standards", "國際財務報導準則", "由 IASB 制定、供多國採用的原則導向財務報導準則。", "跨國報表比較", "The subsidiary prepares its accounts under IFRS."),
    ("US GAAP", "美國一般公認會計原則", "由 FASB 主導制定、適用於美國報導環境的會計準則體系。", "美國公司分析", "The issuer reports under US GAAP."),
    ("IASB", "國際會計準則理事會", "負責制定與發布 IFRS 的獨立準則制定機構。", "理解準則來源", "The IASB develops international reporting standards."),
    ("FASB", "財務會計準則委員會", "負責制定美國 GAAP 的主要民間準則制定機構。", "理解美國準則", "The FASB issued new guidance on accounting treatment."),
    ("Conceptual framework", "觀念架構", "界定財務報導目的、資訊品質特性與報表要素的基礎架構。", "解讀會計原則", "The conceptual framework guides standard setting."),
    ("Accrual accounting", "應計會計", "交易在經濟效果發生時認列，而非僅於現金收付時認列。", "連結盈餘與現金", "Accrual accounting records revenue before cash may be collected."),
    ("Going concern", "繼續經營假設", "假設企業在可預見未來將持續營運，而非清算或大幅縮減。", "評估計量基礎", "The statements were prepared on a going concern basis."),
    ("Materiality", "重大性", "若資訊遺漏或錯誤可能影響使用者決策，即具有重大性。", "判斷揭露重要性", "The error was not material to the annual statements."),
    ("Faithful representation", "忠實表述", "資訊應完整、中立且無重大錯誤地反映其所代表的經濟現象。", "評估資訊品質", "Neutral estimates support faithful representation."),
    ("Relevance", "攸關性", "資訊具預測價值或確認價值，能影響使用者決策。", "篩選決策資訊", "Timely impairment data improves relevance."),
    ("Comparability", "可比性", "資訊能讓使用者辨識不同企業或不同期間間的相同與差異。", "同業與趨勢比較", "Consistent policies improve comparability across years."),
    ("Financial reporting quality", "財務報導品質", "財報能忠實呈現經濟實質並提供決策有用資訊的程度。", "評估報表可信度", "High financial reporting quality helps investors estimate sustainable earnings."),
    ("Earnings quality", "盈餘品質", "報導盈餘反映可持續營運績效並有能力預測未來盈餘的程度。", "預測持續盈餘", "Recurring operating profit usually supports higher earnings quality."),
    ("Conservative accounting", "保守會計", "在不確定情況下較早認列損失、較晚認列利益的審慎處理。", "分析偏誤方向", "Conservative accounting may reduce current income."),
    ("Aggressive accounting", "積極會計", "透過容許範圍內較樂觀的估計或政策提高當期盈餘或資產。", "辨識盈餘高估", "Aggressive accounting can inflate reported profit."),
    ("Earnings management", "盈餘管理", "管理階層運用會計選擇或交易安排使盈餘達成特定目標。", "偵測人為平滑", "Analysts suspected earnings management after the unusual reserve release."),
    ("Accounting fraud", "會計舞弊", "故意違反準則或虛構交易以重大誤導財報使用者。", "辨識非法操縱", "Fictitious sales may indicate accounting fraud."),
    ("Revenue recognition", "收入認列", "企業在履行對客戶的履約義務並取得對價權利時認列收入。", "判斷收入時點", "Revenue recognition occurs when control transfers to the customer."),
    ("Performance obligation", "履約義務", "合約中向客戶移轉可區分商品或服務的承諾。", "分拆合約收入", "Each distinct service may be a separate performance obligation."),
    ("Transaction price", "交易價格", "企業預期因移轉承諾商品或服務而有權取得的對價金額。", "衡量合約收入", "The transaction price includes estimated variable consideration."),
    ("Variable consideration", "變動對價", "因折扣、退貨、獎金或罰款而可能變動的合約對價。", "估計收入金額", "Variable consideration was constrained because returns were uncertain."),
    ("Contract asset", "合約資產", "企業已履約但收取對價的權利仍取決於時間以外條件的資產。", "分析未開票收入", "The builder recorded a contract asset for work completed."),
    ("Contract liability", "合約負債", "企業已收取對價但尚未履行商品或服務移轉義務的負債。", "分析遞延收入", "The annual subscription created a contract liability."),
    ("Principal", "主理人", "在商品或服務移轉客戶前即控制該項目者，通常按總額認列收入。", "判斷總額報導", "The principal reports gross revenue and related cost."),
    ("Agent", "代理人", "安排他方提供商品或服務但未先取得控制者，通常僅按淨額佣金認列收入。", "判斷淨額報導", "The agent recognizes only its commission as revenue."),
    ("Bill-and-hold arrangement", "先開票後代管安排", "賣方已開票但依客戶要求暫時保管商品的安排，須符合嚴格條件才可認列收入。", "審查提前認列", "The analyst questioned revenue from a bill-and-hold arrangement."),
    ("Consignment", "寄售", "商品交由經銷方銷售但控制通常仍由寄售方持有，交付時通常不認列收入。", "辨識未完成銷售", "Delivery on consignment does not necessarily create revenue."),
    ("Channel stuffing", "通路灌貨", "企業向通路商過量出貨以提前認列收入，可能降低盈餘品質。", "偵測收入操縱", "Rising receivables may signal channel stuffing."),
    ("Related-party transaction", "關係人交易", "企業與具控制或重大影響關係的個人或實體間交易，可能非按市場條件進行。", "評估交易公允性", "The notes disclosed a large related-party transaction."),
    ("Nonrecurring item", "非經常性項目", "不預期規律重現、對預測持續盈餘應另行評估的損益項目。", "正規化盈餘", "The analyst excluded the nonrecurring gain from forecasts."),
    ("Pro forma earnings", "備考盈餘", "管理階層自行調整 GAAP 或 IFRS 盈餘後提出的非準則績效數字。", "審查替代績效", "Pro forma earnings excluded several restructuring charges."),
    ("Income statement", "損益表", "呈現一段期間內收入、費用及損益以衡量企業績效的報表。", "分析獲利能力", "The income statement shows how profit was generated."),
    ("Revenue", "收入", "企業正常活動所產生的經濟利益總流入，會增加權益但不含業主投入。", "衡量營運規模", "Revenue increased after the company raised prices."),
    ("Cost of goods sold", "銷貨成本", "本期已售存貨的成本，包括取得或製造商品的相關成本。", "計算毛利", "Higher material costs increased cost of goods sold."),
    ("Gross profit", "毛利", "收入減去銷貨成本後的金額，反映產品基本獲利。", "分析定價能力", "Gross profit rose despite flat sales volume."),
    ("Operating expenses", "營業費用", "支持主要營運但未直接列入銷貨成本的費用，如銷售及管理費。", "評估成本控制", "Operating expenses grew faster than revenue."),
    ("Operating income", "營業利益", "收入扣除與核心營運相關成本及費用後的利益。", "衡量核心績效", "Operating income improved as margins expanded."),
    ("EBIT", "息稅前利益", "扣除利息與所得稅前的利益，常用於比較資本結構不同的企業。", "跨公司營運比較", "EBIT allows comparison before financing costs."),
    ("EBITDA", "息稅折舊攤銷前利益", "EBIT 加回折舊與攤銷的非 GAAP 績效指標，並不等同現金流量。", "粗略衡量營運能力", "EBITDA is not a substitute for cash flow."),
    ("Net income", "淨利", "所有收入與費損計入後歸屬於該期間的最終利益。", "衡量底線績效", "Net income declined because of a tax charge."),
    ("Other comprehensive income", "其他綜合損益", "依準則不計入淨利、而直接列入綜合損益的特定未實現損益。", "分析權益變動", "Currency translation gains appeared in other comprehensive income."),
    ("Comprehensive income", "綜合損益", "淨利加其他綜合損益，反映非業主交易造成的權益總變動。", "衡量完整績效", "Comprehensive income exceeded net income this year."),
    ("Basic earnings per share", "基本每股盈餘", "普通股股東可得淨利除以加權平均流通普通股股數。", "每股績效分析", "Basic earnings per share increased to three dollars."),
    ("Diluted earnings per share", "稀釋每股盈餘", "假設具稀釋效果的潛在普通股轉換後計算的每股盈餘。", "評估潛在稀釋", "Diluted earnings per share includes convertible securities."),
    ("Weighted-average shares", "加權平均股數", "依流通時間加權計算期間內普通股股數，用於每股盈餘分母。", "計算 EPS", "The stock issuance increased weighted-average shares."),
    ("Stock split", "股票分割", "按比例增加股數並降低每股面額，不改變股東總權益；EPS 須追溯調整。", "調整每股資料", "The stock split doubled shares outstanding."),
    ("Treasury stock method", "庫藏股法", "計算選擇權稀釋時，假設執行所得用於按平均市價買回股票。", "計算稀釋 EPS", "The treasury stock method measures option dilution."),
    ("If-converted method", "假設轉換法", "假設可轉換證券於期初轉換，調整分子及分母以計算稀釋 EPS。", "處理可轉換證券", "The if-converted method added back after-tax interest."),
    ("Antidilutive security", "反稀釋證券", "若納入會提高 EPS 或降低每股虧損，計算稀釋 EPS 時應排除。", "篩選潛在普通股", "The options were antidilutive and therefore excluded."),
    ("Common-size income statement", "共同比損益表", "將各損益項目表示為收入百分比，便於跨期及跨公司比較。", "比較利潤結構", "A common-size income statement highlights margin changes."),
    ("Expense recognition", "費用認列", "費用依與收入配合、立即認列或系統性分攤原則計入適當期間。", "判斷損益期間", "Expense recognition should reflect resource consumption."),
    ("Balance sheet", "資產負債表", "於特定日期呈現資產、負債及權益的財務狀況報表。", "分析財務結構", "The balance sheet shows resources and obligations."),
    ("Accounting equation", "會計等式", "資產等於負債加權益，是複式記帳與資產負債表的基礎。", "檢視報表平衡", "Every transaction preserves the accounting equation."),
    ("Asset", "資產", "企業因過去事項控制、預期帶來未來經濟效益的經濟資源。", "辨識經濟資源", "The patent qualifies as an asset."),
    ("Liability", "負債", "企業因過去事項而負有移轉經濟資源的現時義務。", "辨識償付義務", "The loan is reported as a liability."),
    ("Equity", "權益", "資產扣除所有負債後屬於所有者的剩餘權益。", "衡量淨資產", "Retained earnings increased total equity."),
    ("Current asset", "流動資產", "預期於正常營業週期或一年內實現、出售或耗用的資產。", "分析短期流動性", "Cash is a current asset."),
    ("Current liability", "流動負債", "預期於正常營業週期或一年內清償的義務。", "評估短期償債", "Accounts payable is a current liability."),
    ("Cash and cash equivalents", "現金及約當現金", "現金與短期、高流動性且價值變動風險極低的投資。", "衡量即時流動性", "Treasury bills may qualify as cash equivalents."),
    ("Accounts receivable", "應收帳款", "企業因賒銷商品或服務而對客戶擁有的收款權利。", "分析信用銷售", "Accounts receivable rose faster than sales."),
    ("Allowance for doubtful accounts", "備抵呆帳", "對應收款項預期無法收回金額的抵減資產估計。", "評估信用損失", "The company increased its allowance for doubtful accounts."),
    ("Bad debt expense", "呆帳費用", "本期因預期信用損失而認列的費用。", "衡量收款風險", "Bad debt expense increased after customer defaults."),
    ("Prepaid expense", "預付費用", "已支付現金但效益將於未來期間耗用的資產。", "調整期間費用", "Prepaid insurance will become expense over time."),
    ("Accounts payable", "應付帳款", "因賒購商品或服務而欠供應商的短期無息義務。", "分析供應商融資", "Longer payment terms increased accounts payable."),
    ("Accrued liability", "應計負債", "費用已發生但尚未支付或尚未開票所形成的義務。", "辨識未付款費用", "Unpaid wages created an accrued liability."),
    ("Deferred revenue", "遞延收入", "企業先收款但尚未履約所認列的負債，又稱未賺得收入。", "評估未來履約", "Deferred revenue will be recognized as service is delivered."),
    ("Working capital", "營運資金", "流動資產減流動負債，反映企業短期營運資金緩衝。", "衡量短期財務彈性", "Positive working capital supports daily operations."),
    ("Noncurrent asset", "非流動資產", "不符合流動資產定義、預期長期持有或使用的資產。", "分析長期投資", "The factory is a noncurrent asset."),
    ("Noncurrent liability", "非流動負債", "預期不在一年或正常營業週期內清償的義務。", "評估長期槓桿", "The ten-year bond is a noncurrent liability."),
    ("Retained earnings", "保留盈餘", "歷年累積淨利減股利及相關調整後留存於企業的權益。", "追蹤盈餘累積", "Dividends reduce retained earnings."),
    ("Accumulated other comprehensive income", "累計其他綜合損益", "歷年其他綜合損益累積於權益中的金額。", "分析未實現損益", "Translation losses reduced accumulated other comprehensive income."),
    ("Common-size balance sheet", "共同比資產負債表", "將各資產、負債與權益項目表示為總資產百分比。", "比較資本結構", "The common-size balance sheet reveals asset mix changes."),
    ("Statement of cash flows", "現金流量表", "按營業、投資與籌資活動解釋期間內現金及約當現金變動。", "評估現金創造", "The statement of cash flows reconciles opening and closing cash."),
    ("Operating cash flow", "營業活動現金流量", "主要收益活動及非投資、非籌資交易產生的現金流量。", "衡量核心現金流", "Operating cash flow exceeded net income."),
    ("Investing cash flow", "投資活動現金流量", "取得或處分長期資產與特定投資所產生的現金流量。", "分析資本配置", "Buying equipment reduced investing cash flow."),
    ("Financing cash flow", "籌資活動現金流量", "與所有者及借款人間資金取得或償還相關的現金流量。", "分析融資決策", "Debt repayment produced a financing cash outflow."),
    ("Direct method", "直接法", "直接列示主要營業現金收款與付款類別以計算營業現金流。", "呈現營運收付", "The direct method reports cash collected from customers."),
    ("Indirect method", "間接法", "由淨利出發，調整非現金項目與營運資產負債變動以求營業現金流。", "調節淨利與現金", "The indirect method adds back depreciation."),
    ("Cash flow from operations", "來自營運之現金流量", "企業日常營運產生的淨現金流入或流出，等同營業活動現金流量。", "分析盈餘轉現", "Cash flow from operations remained positive."),
    ("Capital expenditure", "資本支出", "取得或改善不動產、廠房及設備等長期資產的現金支出。", "衡量再投資", "Capital expenditure increased after the plant expansion."),
    ("Free cash flow to the firm", "企業自由現金流量", "支付營運費用與必要投資後，可供債權人及股東分配的現金流。", "企業價值評估", "Free cash flow to the firm supports enterprise valuation."),
    ("Free cash flow to equity", "股東自由現金流量", "滿足營運、資本支出及淨借款需求後可供普通股股東分配的現金流。", "股權價值評估", "Free cash flow to equity can fund dividends."),
    ("Noncash transaction", "非現金交易", "不直接收付現金但影響資產、負債或權益的投資或籌資交易。", "補充現金流揭露", "The equipment acquired through a lease was a noncash transaction."),
    ("Interest paid", "支付利息", "IFRS 可在一致政策下列為營業或籌資現金流；美國 GAAP 通常列為營業活動。", "準則分類比較", "Interest paid was classified as an operating cash flow."),
    ("Interest received", "收取利息", "IFRS 可列營業或投資活動；美國 GAAP 通常列為營業活動。", "準則分類比較", "The bank classified interest received as operating cash flow."),
    ("Dividends paid", "支付股利", "IFRS 可列營業或籌資活動；美國 GAAP 列為籌資活動。", "分析股東分配", "Dividends paid reduced financing cash flow."),
    ("Dividends received", "收取股利", "IFRS 可列營業或投資活動；美國 GAAP 通常列為營業活動。", "準則分類比較", "Dividends received were included in operating cash flow."),
    ("Cash flow quality", "現金流量品質", "現金流量可持續、來源透明且與報導盈餘一致的程度。", "評估績效持續性", "Stable operating cash flow suggests better cash flow quality."),
    ("Cash conversion", "現金轉換", "將應計盈餘轉化為實際營業現金流的能力。", "比較淨利與 CFO", "Weak cash conversion may indicate aggressive revenue recognition."),
    ("Operating cash flow ratio", "營業現金流量比率", "營業現金流量除以流動負債，用以衡量短期負債的現金保障。", "短期償債分析", "The operating cash flow ratio improved this year."),
    ("Cash interest coverage", "現金利息保障倍數", "營業現金流加利息與稅後除以支付利息，用以衡量現金付息能力。", "評估付息風險", "Cash interest coverage fell after new borrowing."),
    ("Cash flow reconciliation", "現金流量調節", "將淨利調整為營業現金流，說明應計項目與非現金項目的影響。", "檢視盈餘品質", "The cash flow reconciliation highlighted rising receivables."),
    ("Inventory", "存貨", "持有供出售、正在生產或將耗用於生產的資產。", "分析營運資產", "Inventory increased ahead of the holiday season."),
    ("FIFO", "先進先出法", "假設最早取得的存貨先出售，期末存貨反映較近期成本。", "衡量存貨成本", "FIFO produced a lower cost of sales during inflation."),
    ("LIFO", "後進先出法", "假設最近取得的存貨先出售；美國 GAAP 允許但 IFRS 禁止。", "通膨下成本分析", "LIFO matched recent costs against current revenue."),
    ("Weighted-average cost", "加權平均成本法", "以可供銷售存貨平均單位成本分配銷貨成本與期末存貨。", "平滑單位成本", "Weighted-average cost reduced price volatility."),
    ("Specific identification", "個別辨認法", "以每項特定存貨的實際成本分配銷貨成本，適合不可互換項目。", "高價獨特商品", "The dealer uses specific identification for each vehicle."),
    ("Periodic inventory system", "定期盤存制", "期間內不持續更新存貨，期末盤點後計算銷貨成本。", "存貨紀錄制度", "A periodic inventory system requires a physical count."),
    ("Perpetual inventory system", "永續盤存制", "每次購銷均即時更新存貨數量與成本。", "即時追蹤存貨", "The perpetual inventory system updates stock after every sale."),
    ("Net realizable value", "淨變現價值", "估計售價減完工及銷售所需成本後的金額。", "存貨減損衡量", "Inventory was written down to net realizable value."),
    ("Lower of cost and net realizable value", "成本與淨變現價值孰低法", "IFRS 通常以成本與淨變現價值較低者衡量存貨。", "判斷存貨跌價", "The lower of cost and net realizable value rule reduced inventory."),
    ("Inventory write-down", "存貨跌價損失", "存貨帳面金額高於可回收金額時降低存貨並認列損失。", "反映存貨減值", "The obsolete goods caused an inventory write-down."),
    ("Reversal of inventory write-down", "存貨跌價回升", "IFRS 在淨變現價值回升時可於原跌價範圍內迴轉；美國 GAAP 通常禁止。", "比較 IFRS 與 GAAP", "IFRS permitted a reversal of the inventory write-down."),
    ("LIFO reserve", "LIFO 準備", "FIFO 存貨帳面額超過 LIFO 存貨帳面額的差額。", "轉換 LIFO 至 FIFO", "Adding the LIFO reserve converts inventory toward FIFO."),
    ("LIFO liquidation", "LIFO 層清算", "LIFO 存貨量下降導致較早低成本層流入銷貨成本，可能暫時提高毛利。", "調整不可持續盈餘", "LIFO liquidation boosted reported profit."),
    ("Inventory turnover", "存貨週轉率", "銷貨成本除以平均存貨，衡量存貨出售或耗用速度。", "評估存貨效率", "Inventory turnover slowed as demand weakened."),
    ("Days of inventory on hand", "存貨持有天數", "期間天數除以存貨週轉率，估計存貨平均持有日數。", "衡量庫存期間", "Days of inventory on hand rose to sixty."),
    ("Gross profit method", "毛利法", "利用歷史毛利率估計銷貨成本與期末存貨，常用於中期估計。", "估計存貨餘額", "The retailer used the gross profit method after the fire."),
    ("Inventory obsolescence", "存貨過時", "存貨因技術、時尚或需求變化而失去部分或全部銷售價值。", "評估跌價風險", "Rapid innovation increased inventory obsolescence."),
    ("Purchase commitment", "採購承諾", "企業承諾於未來按約定價格購買存貨，若不可取消可能產生損失風險。", "分析表外承諾", "The purchase commitment became unfavorable when prices fell."),
    ("Inventory cost capitalization", "存貨成本資本化", "將使存貨達到目前地點與狀態的採購、轉換及其他必要成本列入存貨。", "判斷存貨成本", "Freight-in qualifies for inventory cost capitalization."),
    ("Abnormal waste", "異常耗損", "超出正常生產水準的材料、人工或製造費用，通常應立即費用化。", "排除不當資本化", "Abnormal waste was expensed immediately."),
    ("Property, plant, and equipment", "不動產、廠房及設備", "供生產、出租或管理用途且預期使用超過一期的有形資產。", "分析營運長期資產", "Property, plant, and equipment represents most of the asset base."),
    ("Capitalization", "資本化", "將支出列為資產並於未來期間逐步認列費用，而非立即費用化。", "判斷支出處理", "Capitalization raises current profit relative to expensing."),
    ("Expensing", "費用化", "將支出於發生期間直接計入損益。", "比較會計選擇", "Expensing lowers current income and assets."),
    ("Depreciation", "折舊", "將有形長期資產可折舊金額於估計耐用年限內系統性分攤。", "分攤資產成本", "Depreciation allocates the machine's cost over its life."),
    ("Straight-line depreciation", "直線折舊法", "每期認列相同折舊金額，假設資產效益平均耗用。", "穩定分攤成本", "Straight-line depreciation produces equal annual expense."),
    ("Accelerated depreciation", "加速折舊法", "資產早期認列較多折舊、後期較少，反映效益較快耗用。", "前高後低費用", "Accelerated depreciation reduces early reported income."),
    ("Double-declining balance", "雙倍餘額遞減法", "以直線折舊率兩倍乘期初帳面金額的加速折舊法。", "計算加速折舊", "Double-declining balance records more expense initially."),
    ("Units-of-production method", "生產數量法", "依實際產量或使用量占預估總量比例認列折舊。", "配合資產使用", "The mine uses the units-of-production method."),
    ("Useful life", "耐用年限", "企業預期使用資產的期間或預期產出單位數。", "估計折舊期間", "A longer useful life lowers annual depreciation."),
    ("Residual value", "殘值", "資產達耐用年限終點時，扣除處分成本後預期可收回的金額。", "計算可折舊金額", "A higher residual value reduces depreciation expense."),
    ("Carrying amount", "帳面金額", "資產成本扣除累計折舊、攤銷及累計減損後的報表金額。", "比較回收價值", "The asset's carrying amount exceeded its recoverable amount."),
    ("Historical cost model", "歷史成本模式", "長期資產按原始成本減累計折舊與減損列報。", "衡量長期資產", "The company uses the historical cost model for equipment."),
    ("Revaluation model", "重估價模式", "IFRS 允許特定長期資產類別按公允價值重估後金額列報。", "分析 IFRS 資產", "The revaluation model increased land and equity."),
    ("Revaluation surplus", "重估增值", "資產向上重估通常在其他綜合損益認列並累積於權益的金額。", "追蹤重估影響", "The property revaluation created a revaluation surplus."),
    ("Component depreciation", "組成部分折舊", "將重大且耐用年限不同的資產組件分別折舊；IFRS 要求較明確。", "提高折舊精確性", "Component depreciation treats the aircraft engine separately."),
    ("Derecognition", "除列", "資產處分或不再預期產生效益時，自資產負債表移除其帳面金額。", "處理資產出售", "The company recognized a gain on derecognition."),
    ("Gain on disposal", "處分利益", "處分價款高於資產帳面金額的差額，通常計入損益。", "分析非經常損益", "The gain on disposal increased pretax income."),
    ("Asset turnover", "資產週轉率", "收入除以平均總資產，衡量資產產生銷售的效率。", "評估資產效率", "Asset turnover improved after idle assets were sold."),
    ("Capitalized interest", "資本化利息", "符合條件資產建造期間的借款成本列入資產成本，而非立即列作利息費用。", "分析建造中資產", "Capitalized interest delayed expense recognition."),
    ("Investment property", "投資性不動產", "為賺取租金、資本增值或兩者而持有的不動產；IFRS 可採成本或公允價值模式。", "辨識非自用不動產", "The office building held for rent is investment property."),
    ("Intangible asset", "無形資產", "可辨認、無實體形態且由企業控制的非貨幣性資產。", "分析無形資源", "The acquired patent is an intangible asset."),
    ("Identifiable intangible", "可辨認無形資產", "可分離出售或源自合約或法定權利的無形資產。", "區分商譽", "The customer list is an identifiable intangible."),
    ("Finite-lived intangible", "有限耐用年限無形資產", "預期經濟效益期間有限，須於耐用年限內攤銷並測試減損。", "計算攤銷", "The license is a finite-lived intangible."),
    ("Indefinite-lived intangible", "非確定耐用年限無形資產", "沒有可預見效益終止期限，不攤銷但至少每年測試減損。", "年度減損分析", "The brand was classified as an indefinite-lived intangible."),
    ("Amortization", "攤銷", "將有限年限無形資產的可攤銷金額於耐用年限內系統性分攤。", "分攤無形成本", "Patent amortization reduced operating income."),
    ("Research cost", "研究支出", "為取得新知識而進行探索活動的支出，IFRS 與美國 GAAP 通常均立即費用化。", "研發會計分析", "Research cost was expensed as incurred."),
    ("Development cost", "發展支出", "將研究成果應用於新產品或製程的支出；IFRS 符合條件時資本化，美國 GAAP 多數費用化。", "比較研發準則", "IFRS allowed capitalization of qualifying development cost."),
    ("Goodwill", "商譽", "企業合併對價超過可辨認淨資產公允價值的剩餘金額。", "分析併購溢價", "The acquisition created substantial goodwill."),
    ("Internally generated goodwill", "內部產生商譽", "企業自行建立的聲譽、人才與協同價值，因不可可靠衡量而不得認列。", "排除未認列資產", "Internally generated goodwill is not recorded."),
    ("Impairment", "減損", "資產帳面金額超過可回收或可支持金額時認列的價值下降。", "調降高估資產", "Weak demand triggered an impairment test."),
    ("Recoverable amount", "可回收金額", "IFRS 下資產公允價值減處分成本與使用價值兩者較高者。", "IFRS 減損測試", "The recoverable amount fell below carrying value."),
    ("Value in use", "使用價值", "資產持續使用及最終處分預期現金流量的折現值。", "估計可回收金額", "Management estimated value in use with discounted cash flows."),
    ("Cash-generating unit", "現金產生單位", "能產生大致獨立現金流入的最小資產組合，用於 IFRS 減損測試。", "分配與測試商譽", "Goodwill was allocated to a cash-generating unit."),
    ("Impairment loss", "減損損失", "資產帳面金額超過其可回收或公允價值基礎金額的差額。", "認列價值下降", "The impairment loss reduced current earnings."),
    ("Impairment reversal", "減損迴轉", "IFRS 對商譽以外資產在價值回升時可有限迴轉；美國 GAAP 對持有使用資產通常禁止。", "準則差異分析", "The impairment reversal was permitted under IFRS."),
    ("Goodwill impairment", "商譽減損", "商譽所屬報導單位或現金產生單位價值不足時認列的損失，不得迴轉。", "評估併購績效", "Goodwill impairment signaled that the acquisition underperformed."),
    ("Software development cost", "軟體開發成本", "依軟體用途與開發階段適用特定資本化規則的支出。", "分析科技公司資產", "Some software development cost was capitalized after feasibility."),
    ("Patent", "專利權", "賦予持有人在一定期間內排他使用發明的法定無形權利。", "辨識法定無形資產", "The patent protects the new production process."),
    ("Trademark", "商標權", "用以識別商品或服務來源的名稱、符號或設計權利。", "分析品牌資產", "The acquired trademark has an indefinite life."),
    ("Deferred tax asset", "遞延所得稅資產", "可減除暫時性差異或虧損扣抵預期使未來應付所得稅減少的金額。", "分析未來稅益", "The loss carryforward created a deferred tax asset."),
    ("Deferred tax liability", "遞延所得稅負債", "應課稅暫時性差異預期使未來應付所得稅增加的金額。", "分析未來稅負", "Accelerated tax depreciation created a deferred tax liability."),
    ("Temporary difference", "暫時性差異", "資產或負債帳面金額與課稅基礎間未來會迴轉的差異。", "計算遞延所得稅", "The warranty liability created a temporary difference."),
    ("Permanent difference", "永久性差異", "會計所得與課稅所得間永不迴轉的差異，不產生遞延所得稅。", "調節有效稅率", "Tax-exempt interest is a permanent difference."),
    ("Tax base", "課稅基礎", "為稅務目的歸屬於資產或負債的金額。", "辨認暫時差異", "The asset's tax base was below its carrying amount."),
    ("Income tax expense", "所得稅費用", "當期所得稅費用加遞延所得稅費用的總額。", "分析稅後盈餘", "Income tax expense exceeded taxes paid."),
    ("Current tax expense", "當期所得稅費用", "依本期課稅所得及現行稅法計算的應付所得稅。", "估計本期稅負", "Current tax expense reflects taxable income."),
    ("Effective tax rate", "有效稅率", "所得稅費用除以稅前會計利益，反映實際報導稅負比例。", "比較稅務效率", "The effective tax rate fell after a tax credit."),
    ("Statutory tax rate", "法定稅率", "稅法對課稅所得規定的名目所得稅率。", "調節稅率差異", "The statutory tax rate remained unchanged."),
    ("Valuation allowance", "遞延所得稅資產備抵", "美國 GAAP 下，遞延所得稅資產較可能無法實現部分的抵減金額。", "評估 DTA 可實現性", "A larger valuation allowance reduced the net deferred tax asset."),
    ("Unrecognized tax benefit", "未認列租稅利益", "因稅務處理不確定而未在財報中認列的潛在所得稅利益。", "分析稅務不確定性", "The audit increased the unrecognized tax benefit."),
    ("Tax loss carryforward", "課稅虧損後抵", "本期課稅虧損可依法律抵減未來課稅所得的權利。", "辨識未來稅盾", "The tax loss carryforward may reduce future taxes."),
    ("Tax rate change", "稅率變動", "已制定稅率改變時，遞延所得稅資產與負債須按預期迴轉稅率重新衡量。", "調整遞延稅項", "The tax rate change reduced the deferred tax liability."),
    ("Deferred tax expense", "遞延所得稅費用", "期間內遞延所得稅負債淨增加或資產淨減少所形成的稅費用。", "調節現金稅與費用", "Deferred tax expense raised the total tax provision."),
    ("Taxes payable", "應付所得稅", "截至報導日已發生但尚未支付給稅務機關的當期所得稅負債。", "分析短期稅負", "Taxes payable increased with taxable profit."),
    ("Book income", "會計所得", "依財務報導準則計算、在所得稅前列報的利益。", "與課稅所得比較", "Book income differed from taxable income."),
    ("Taxable income", "課稅所得", "依稅法規定計算、作為當期所得稅基礎的所得。", "計算現金稅負", "Taxable income was reduced by accelerated depreciation."),
    ("Tax reconciliation", "所得稅調節", "說明法定稅率計算的稅額與實際所得稅費用差異。", "辨識稅率驅動因子", "The tax reconciliation showed foreign tax effects."),
    ("Indefinite reversal criterion", "不確定迴轉條件", "若差異預期不會在可預見未來迴轉，特定情況下可能不認列相關遞延稅負。", "分析海外盈餘稅務", "Management applied the indefinite reversal criterion to foreign earnings."),
    ("Debt financing", "債務融資", "企業以借款或發行債券取得資金並承諾支付本金與利息。", "分析資本結構", "Debt financing increased financial leverage."),
    ("Bond payable", "應付公司債", "企業發行債券所形成的契約性長期負債。", "評估長期借款", "The bond payable matures in ten years."),
    ("Face value", "票面金額", "債券到期應償還的本金金額，也是票息計算基礎。", "計算債券現金流", "The bond has a face value of one thousand dollars."),
    ("Coupon rate", "票面利率", "債券每年票息除以票面金額的契約利率。", "計算利息支付", "The coupon rate determines the cash interest."),
    ("Effective interest method", "有效利率法", "以發行時市場利率乘期初攤銷後成本計算利息費用並攤銷折溢價。", "衡量債券成本", "The effective interest method amortizes the discount."),
    ("Bond discount", "公司債折價", "債券發行價格低於票面金額的差額，會使有效利息費用高於現金票息。", "分析借款成本", "The bond discount increases interest expense over time."),
    ("Bond premium", "公司債溢價", "債券發行價格高於票面金額的差額，會使有效利息費用低於現金票息。", "分析利息費用", "The bond premium is amortized until maturity."),
    ("Debt covenant", "債務契約條款", "借款合約中限制借款人行為或要求維持特定財務條件的約定。", "評估違約風險", "The company nearly breached its debt covenant."),
    ("Lease", "租賃", "在一段期間內以對價換取控制已辨認資產使用權的合約。", "分析使用權融資", "The warehouse contract qualifies as a lease."),
    ("Right-of-use asset", "使用權資產", "承租人在租賃期間控制使用標的資產權利所認列的資產。", "承租人資產分析", "The lessee recognized a right-of-use asset."),
    ("Lease liability", "租賃負債", "承租人對未來租賃付款現值所認列的義務。", "承租人負債分析", "The lease liability declines as payments are made."),
    ("Finance lease", "融資租賃", "實質移轉標的資產大部分風險與報酬的租賃，費用呈利息加折舊。", "評估融資性租賃", "The equipment lease was classified as a finance lease."),
    ("Operating lease", "營業租賃", "美國 GAAP 承租人分類中未達融資租賃條件者，通常認列單一租賃費用。", "分析租賃費用型態", "The office lease was classified as an operating lease."),
    ("Short-term lease exemption", "短期租賃豁免", "IFRS 允許租期十二個月內且無購買選擇權的租賃不認列使用權資產與負債。", "簡化承租會計", "The lessee elected the short-term lease exemption."),
    ("Defined benefit plan", "確定給付退休金計畫", "雇主承諾按公式支付退休福利，並承擔精算與投資風險。", "分析退休金義務", "The defined benefit plan exposed the employer to longevity risk."),
    ("Defined contribution plan", "確定提撥退休金計畫", "雇主僅承諾提撥固定金額，員工承擔投資績效風險。", "衡量退休金費用", "The employer contributes five percent to the defined contribution plan."),
    ("Projected benefit obligation", "預計給付義務", "依未來薪資估計計算員工已服務所累積退休給付的精算現值。", "衡量退休金負債", "A lower discount rate increased the projected benefit obligation."),
    ("Plan assets", "退休金計畫資產", "依法獨立持有、專供支付退休給付的投資資產。", "計算淨退休金部位", "Strong markets increased plan assets."),
    ("Funded status", "退休金提撥狀況", "計畫資產公允價值減確定給付義務，表示超額或不足提撥。", "評估退休金缺口", "The pension plan had an underfunded status."),
    ("Pension service cost", "退休金服務成本", "員工本期服務使確定給付義務增加的現值。", "分析退休金費用", "Pension service cost rose with employee compensation."),
    ("Financial asset", "金融資產", "包括現金、他方權益工具或收取現金及其他金融資產的合約權利。", "金融工具分類", "The bond investment is a financial asset."),
    ("Amortized cost", "攤銷後成本", "金融資產或負債初始金額經本金償還及有效利率攤銷調整後的衡量基礎。", "衡量債務工具", "The held loan is measured at amortized cost."),
    ("Fair value through profit or loss", "透過損益按公允價值衡量", "公允價值變動直接計入當期損益的金融工具分類。", "分析交易性投資", "The trading security is measured at fair value through profit or loss."),
    ("Fair value through OCI", "透過其他綜合損益按公允價值衡量", "公允價值變動多數先列入其他綜合損益的金融資產分類。", "分析 OCI 投資", "The debt investment is measured at fair value through OCI."),
    ("Held-to-maturity security", "持有至到期證券", "美國 GAAP 下具固定付款且企業有意圖及能力持有至到期的債務證券。", "攤銷後成本分類", "The bond was classified as a held-to-maturity security."),
    ("Trading security", "交易目的證券", "以近期出售獲利為目的持有、其未實現損益計入淨利的證券。", "短期投資分析", "The trading security generated an unrealized gain."),
    ("Equity method", "權益法", "投資人具重大影響時，按持股比例認列被投資者淨利並調整投資帳面額。", "關聯企業投資", "The investor used the equity method for its associate."),
    ("Significant influence", "重大影響", "參與被投資者財務與營運政策決策但不具控制的能力，通常持股百分之二十至五十。", "判斷權益法", "Board representation indicated significant influence."),
    ("Associate", "關聯企業", "投資人對其具有重大影響但非子公司或合資的被投資實體。", "辨識權益法投資", "The twenty-five percent investee is an associate."),
    ("Joint venture", "合資", "各方共同控制且對淨資產享有權利的安排，IFRS 通常採權益法。", "分析共同控制", "The partners formed a joint venture."),
    ("Business combination", "企業合併", "收購方取得一項或多項業務控制的交易或事項。", "分析併購會計", "The business combination expanded the product line."),
    ("Acquisition method", "收購法", "企業合併中辨認收購方、按公允價值衡量對價與可辨認淨資產並認列商譽。", "處理企業合併", "The acquisition method revalued acquired assets."),
    ("Control", "控制", "投資者有權主導被投資者相關活動、承擔變動報酬並能運用權力影響報酬。", "判斷是否合併", "Voting rights gave the parent control."),
    ("Subsidiary", "子公司", "受另一實體控制、其財報通常納入母公司合併報表的企業。", "合併範圍判定", "The parent consolidated its subsidiary."),
    ("Consolidation", "合併報表", "將母子公司資產、負債、收入與費用逐項合併並抵銷集團內交易。", "集團報表分析", "Consolidation eliminated intercompany sales."),
    ("Noncontrolling interest", "非控制權益", "子公司權益中不直接或間接歸屬於母公司的部分。", "分析少數股東權益", "Noncontrolling interest was presented within equity."),
    ("Intercompany transaction", "集團內交易", "同一合併集團內實體彼此進行的交易，合併時須抵銷。", "避免重複認列", "The intercompany transaction was eliminated on consolidation."),
    ("Goodwill under full goodwill method", "完全商譽法下商譽", "按收購方及非控制權益的全部公允價值衡量整體商譽的方法。", "企業合併衡量", "The full goodwill method produced higher goodwill."),
    ("Proportionate consolidation", "比例合併法", "按投資比例逐項認列共同安排資產、負債、收入與費用的方法，適用範圍有限。", "共同安排分析", "Proportionate consolidation reports a share of each line item."),
    ("Foreign currency transaction", "外幣交易", "以企業功能性貨幣以外貨幣計價或結算的交易。", "分析匯率影響", "The euro purchase created a foreign currency transaction."),
    ("Functional currency", "功能性貨幣", "企業主要經濟環境中產生及支用現金的貨幣。", "決定換算方法", "The subsidiary's functional currency is the euro."),
    ("Presentation currency", "表達貨幣", "企業選擇用於呈現財務報表的貨幣。", "集團報表呈現", "The group uses the dollar as its presentation currency."),
    ("Foreign currency translation", "外幣報表換算", "將外國營運以功能性貨幣編製的財報轉換為母公司表達貨幣。", "合併海外子公司", "Foreign currency translation created an OCI adjustment."),
    ("Remeasurement", "外幣重新衡量", "將帳簿貨幣報表轉為功能性貨幣，相關損益通常計入淨利。", "功能性貨幣轉換", "Remeasurement produced a foreign exchange loss."),
    ("Current rate method", "現行匯率法", "功能性貨幣非母公司貨幣時，資產負債按期末匯率換算，換算差額列入 OCI。", "換算獨立海外營運", "The current rate method translated assets at the closing rate."),
    ("Temporal method", "時態法", "功能性貨幣為母公司貨幣時，貨幣性項目按現行匯率、非貨幣性項目多按歷史匯率重新衡量。", "重新衡量外幣帳簿", "The temporal method created a gain in net income."),
    ("Monetary asset", "貨幣性資產", "將收取固定或可決定貨幣單位數量的資產，如現金與應收帳款。", "分析匯兌曝險", "Accounts receivable is a monetary asset."),
    ("Monetary liability", "貨幣性負債", "將支付固定或可決定貨幣單位數量的義務，如應付帳款與債務。", "分析匯兌曝險", "The foreign loan is a monetary liability."),
    ("Translation adjustment", "換算調整數", "現行匯率法因使用不同匯率換算報表項目而產生、通常列入 OCI 的差額。", "解讀累計換算差額", "The translation adjustment reduced comprehensive income."),
    ("Transaction gain or loss", "外幣交易損益", "外幣貨幣性項目自交易日至結算日因匯率變動產生的損益。", "分析淨利波動", "The weaker currency caused a transaction loss."),
    ("Hyperinflationary economy", "高度通膨經濟", "累積通膨極高且貨幣購買力快速下降的經濟環境，須採特殊報導處理。", "調整海外財報", "The subsidiary operates in a hyperinflationary economy."),
    ("Purchasing power gain", "購買力利益", "通膨期間持有淨貨幣性負債因實質償付負擔下降而產生的利益。", "通膨會計分析", "Net monetary liabilities generated a purchasing power gain."),
    ("Purchasing power loss", "購買力損失", "通膨期間持有淨貨幣性資產因貨幣購買力下降而產生的損失。", "通膨會計分析", "Cash holdings caused a purchasing power loss."),
    ("Exchange rate", "匯率", "一種貨幣以另一種貨幣表示的交換價格。", "換算外幣項目", "The exchange rate moved against the exporter."),
    ("Closing rate", "期末匯率", "報導期間末即期匯率，現行匯率法用於換算資產與負債。", "期末報表換算", "Liabilities were translated at the closing rate."),
    ("Historical rate", "歷史匯率", "交易發生或資產負債最初認列時的匯率。", "換算非貨幣項目", "Share capital was translated at the historical rate."),
    ("Average rate", "平均匯率", "期間匯率的合理平均值，匯率未劇烈波動時可近似換算收入與費用。", "換算期間損益", "Revenue was translated at the average rate."),
    ("Currency exposure", "貨幣曝險", "企業價值或報導數字對匯率變動的敏感程度。", "評估外匯風險", "The foreign debt increased currency exposure."),
    ("Natural hedge", "自然避險", "以同一貨幣的營運流入與流出或資產與負債互相抵銷匯率風險。", "降低外匯波動", "Local borrowing provided a natural hedge."),
    ("Current ratio", "流動比率", "流動資產除以流動負債，衡量短期償債能力。", "流動性分析", "The current ratio declined below two."),
    ("Quick ratio", "速動比率", "現金、短期投資與應收款除以流動負債，排除較不流動存貨。", "嚴格流動性分析", "The quick ratio remained above one."),
    ("Cash ratio", "現金比率", "現金及約當現金加有價證券除以流動負債。", "即時償債分析", "The cash ratio indicates the strongest liquidity test."),
    ("Receivables turnover", "應收帳款週轉率", "賒銷收入除以平均應收帳款，衡量收款效率。", "信用管理分析", "Receivables turnover fell as collections slowed."),
    ("Days sales outstanding", "應收帳款天數", "期間天數除以應收帳款週轉率，估計平均收款日數。", "分析收款速度", "Days sales outstanding increased to forty-five."),
    ("Payables turnover", "應付帳款週轉率", "賒購額除以平均應付帳款，衡量支付供應商速度。", "供應商付款分析", "Payables turnover decreased after terms were extended."),
    ("Days payable outstanding", "應付帳款天數", "期間天數除以應付帳款週轉率，估計平均付款日數。", "分析付款政策", "Days payable outstanding rose to sixty."),
    ("Operating cycle", "營業週期", "存貨持有天數加應收帳款天數，表示投入存貨至收回現金的時間。", "衡量營運週期", "The operating cycle shortened after faster collections."),
    ("Cash conversion cycle", "現金轉換週期", "存貨天數加應收天數減應付天數，衡量現金被營運占用的期間。", "營運資金效率", "A shorter cash conversion cycle improves liquidity."),
    ("Gross profit margin", "毛利率", "毛利除以收入，反映定價能力與產品成本控制。", "獲利率分析", "Gross profit margin expanded after the price increase."),
    ("Operating profit margin", "營業利益率", "營業利益除以收入，衡量核心營運每單位收入的獲利。", "營運獲利分析", "Operating profit margin improved through cost savings."),
    ("Net profit margin", "淨利率", "淨利除以收入，衡量收入最終轉化為淨利的比例。", "整體獲利分析", "Net profit margin fell because of higher interest expense."),
    ("Return on assets", "資產報酬率", "淨利除以平均總資產，衡量資產產生利益的能力。", "資產獲利分析", "Return on assets improved with better utilization."),
    ("Return on equity", "權益報酬率", "普通股股東可得淨利除以平均普通股權益，衡量股東投資報酬。", "股東報酬分析", "Return on equity rose as leverage increased."),
    ("Debt-to-assets ratio", "負債對資產比率", "總負債除以總資產，衡量資產由債務融資的比例。", "償債能力分析", "The debt-to-assets ratio signaled higher financial risk."),
    ("Debt-to-equity ratio", "負債權益比", "總債務或總負債除以總權益，衡量財務槓桿。", "資本結構分析", "The debt-to-equity ratio increased after the bond issue."),
    ("Financial leverage ratio", "財務槓桿比率", "平均總資產除以平均總權益，顯示每單位權益支持的資產規模。", "杜邦分析", "A higher financial leverage ratio can amplify return on equity."),
    ("Interest coverage ratio", "利息保障倍數", "EBIT 除以利息費用，衡量營業利益支付利息的能力。", "長期償債分析", "Interest coverage weakened as borrowing costs rose."),
    ("Fixed charge coverage", "固定支出保障倍數", "可供支付固定費用的盈餘除以利息與租賃等固定支出。", "評估固定承諾", "Fixed charge coverage captures lease obligations."),
    ("Dividend payout ratio", "股利支付率", "普通股股利除以普通股股東可得淨利，衡量盈餘分配比例。", "股利政策分析", "The dividend payout ratio remained stable."),
    ("Retention ratio", "盈餘保留率", "一減股利支付率，表示淨利保留於企業再投資的比例。", "估計內生成長", "A high retention ratio may support future growth."),
    ("DuPont analysis", "杜邦分析", "將 ROE 分解為利潤率、資產效率與財務槓桿等驅動因素。", "診斷 ROE 來源", "DuPont analysis showed that leverage drove the higher return."),
    ("Three-step DuPont model", "三階段杜邦模型", "將 ROE 分解為淨利率、總資產週轉率與財務槓桿比率。", "基本 ROE 分解", "The three-step DuPont model isolates three return drivers."),
    ("Five-step DuPont model", "五階段杜邦模型", "進一步將 ROE 分解為稅負、利息負擔、EBIT 利潤率、資產週轉及槓桿。", "深入 ROE 分析", "The five-step DuPont model identified weak interest burden."),
    ("Tax burden ratio", "稅負比率", "淨利除以稅前利益，衡量所得稅對報酬的保留程度。", "五階段杜邦分析", "The tax burden ratio improved after tax credits."),
    ("Interest burden ratio", "利息負擔比率", "稅前利益除以 EBIT，衡量利息費用對獲利的侵蝕。", "五階段杜邦分析", "The interest burden ratio fell after new debt issuance."),
    ("EBIT margin", "EBIT 利潤率", "EBIT 除以收入，衡量利息與稅前的營運獲利能力。", "杜邦營運分析", "EBIT margin expanded despite flat revenue."),
    ("Sustainable growth rate", "永續成長率", "在維持資本結構且不發行新股時，ROE 乘盈餘保留率所估計的長期成長率。", "估計內生成長", "The sustainable growth rate is driven by return and retention."),
    ("Horizontal analysis", "水平分析", "比較同一財報項目跨期間的金額或百分比變動。", "趨勢變化分析", "Horizontal analysis revealed rapid expense growth."),
    ("Vertical analysis", "垂直分析", "將財報項目表示為同期間基準項目的百分比。", "結構比較分析", "Vertical analysis expresses expenses as a percentage of sales."),
    ("Trend analysis", "趨勢分析", "以基期為基準觀察多期間財務項目的方向與速度。", "長期績效判讀", "Trend analysis showed five years of margin compression."),
    ("Ratio analysis", "比率分析", "運用財務報表數字間關係評估流動性、效率、槓桿與獲利能力。", "綜合財務診斷", "Ratio analysis helps compare firms of different sizes."),
    ("Benchmarking", "標竿比較", "將企業比率與同業、產業或自身歷史基準比較。", "解讀比率高低", "Benchmarking showed that inventory levels were excessive."),
    ("Segment reporting", "部門報導", "按管理階層監控的營運部門揭露收入、損益與資產等資訊。", "分析多元化企業", "Segment reporting revealed weakness in the Asian division."),
    ("Geographic segment", "地區部門", "依營運所在地或客戶所在地區分的財務資訊。", "評估地區風險", "The geographic segment data showed strong European growth."),
    ("Sensitivity analysis", "敏感度分析", "衡量關鍵假設變動對財務結果或估值的影響。", "測試估計風險", "Sensitivity analysis tested a higher discount rate."),
    ("Scenario analysis", "情境分析", "同時改變多項假設以評估不同一致情境下的結果。", "壓力測試預測", "Scenario analysis compared recession and expansion outcomes."),
    ("Normalized earnings", "正常化盈餘", "排除非經常、非營運或不具代表性項目後的可持續盈餘估計。", "建立預測基礎", "Normalized earnings excluded the litigation gain."),
    ("Quality of earnings ratio", "盈餘品質比率", "營業現金流量除以淨利，用以評估盈餘的現金支持程度。", "檢視盈餘轉現", "The quality of earnings ratio exceeded one."),
    ("Accrual ratio", "應計比率", "以應計項目相對資產衡量盈餘中非現金成分，較高值可能表示盈餘品質較弱。", "偵測應計異常", "A rising accrual ratio concerned the analyst."),
    ("Altman Z-score", "Altman Z 分數", "結合多項財務比率估計企業破產風險的統計模型。", "信用風險篩選", "The low Altman Z-score suggested financial distress."),
    ("Clean surplus relation", "乾淨盈餘關係", "期末權益等於期初權益加淨利減股利，假設損益均經過損益表。", "權益估值分析", "Other comprehensive income can break the clean surplus relation."),
    ("Accounting policy", "會計政策", "企業編製財報所採用的特定原則、基礎、慣例與方法。", "評估可比性", "The note explains the company's accounting policy."),
    ("Accounting estimate", "會計估計", "因衡量不確定性而依最新可靠資訊估計的報表金額。", "分析判斷風險", "Useful life is an accounting estimate."),
    ("Change in accounting policy", "會計政策變動", "自一種允許政策改採另一種政策，通常須追溯適用以維持可比性。", "處理政策改變", "The change in accounting policy was applied retrospectively."),
    ("Change in accounting estimate", "會計估計變動", "因新資訊或新發展修正估計，通常於當期及未來期間推延認列。", "處理估計更新", "The change in accounting estimate affected future depreciation."),
    ("Prior-period error", "前期錯誤", "過去期間因未使用或誤用當時可得可靠資訊造成的遺漏或錯誤，通常追溯更正。", "更正歷史報表", "The prior-period error required restatement."),
    ("Retrospective application", "追溯適用", "如同新政策一直被採用般重編前期比較數字及期初權益。", "政策變動處理", "Retrospective application improved comparability."),
    ("Prospective application", "推延適用", "新估計的影響自變動當期及未來期間認列，不重編過去。", "估計變動處理", "Prospective application left prior results unchanged."),
    ("Subsequent event", "期後事項", "報導日後至財報授權發布日前發生、可能需要調整或揭露的事項。", "期末報導完整性", "The lawsuit settlement was a subsequent event."),
    ("Adjusting event", "調整期後事項", "提供報導日已存在狀況之進一步證據，須調整財報金額。", "修正期末估計", "The customer's bankruptcy was an adjusting event."),
    ("Nonadjusting event", "非調整期後事項", "反映報導日後才發生狀況，不調整金額但重大時須揭露。", "揭露重大後續事件", "The post-year-end fire was a nonadjusting event."),
    ("Contingent liability", "或有負債", "因過去事項形成、是否存在或金額取決於不確定未來事件的可能義務。", "分析不確定負債", "The lawsuit may create a contingent liability."),
    ("Provision", "負債準備", "時間或金額不確定但符合認列條件的現時義務負債。", "估計未來支出", "The company recognized a provision for warranties."),
    ("Loss contingency", "損失或有事項", "可能導致損失且取決於未來事件的既存情況，美國 GAAP 依可能性與可估計性處理。", "評估潛在損失", "The legal claim was disclosed as a loss contingency."),
    ("Restructuring charge", "重組費用", "因關閉設施、裁員或重大組織調整而認列的成本。", "正規化營業盈餘", "The restructuring charge reduced current profit."),
    ("Special purpose entity", "特殊目的實體", "為特定狹窄目的成立、可能用於融資或風險隔離的實體。", "評估表外風險", "The analyst examined the special purpose entity for hidden leverage."),
    ("Off-balance-sheet financing", "資產負債表外融資", "取得資金或使用資產卻未在資產負債表充分呈現相關負債的安排。", "調整財務槓桿", "Off-balance-sheet financing understated apparent leverage."),
    ("Cookie jar reserve", "餅乾罐準備", "好年景過度提列準備並於壞年景轉回，以平滑盈餘的作法。", "辨識盈餘管理", "The reserve release looked like a cookie jar reserve."),
    ("Big bath accounting", "大洗澡會計", "在表現已差的期間一次認列大量損失，使未來期間較易呈現改善。", "偵測損失集中", "Management may use big bath accounting during restructuring."),
    ("Classification shifting", "分類移轉", "在不改變淨利下，將核心費用移至特殊項目以美化營業績效。", "檢查核心盈餘", "Classification shifting overstated recurring operating income."),
    ("Backdating", "倒填日期", "將交易或選擇權日期追溯設定為較有利日期，可能造成不實報導。", "辨識治理風險", "The regulator investigated option backdating."),
]
