# CFA L1 Quantitative Methods ~150
TERMS = [
("Descriptive Statistics", "敘述統計", "用以整理、摘要與描述資料特徵的統計方法，如平均數與標準差。", "報告績效與風險摘要。", "\"Descriptive statistics show the fund's average return and volatility last year.\""),
("Inferential Statistics", "推論統計", "從樣本推論母體參數或檢定假設的方法。", "回測是否顯著。", "\"Inferential statistics help us test whether alpha is significantly positive.\""),
("Population", "母體", "研究對象的全體集合。", "定義分析範圍。", "\"Our population is all listed banks in the region, not just the sample we screened.\""),
("Sample", "樣本", "自母體抽取、用以推論的子集。", "抽樣設計。", "\"A random sample of 200 stocks should represent the broader equity universe.\""),
("Parameter", "參數", "描述母體特徵的數值，如母體平均數 μ。", "模型設定。", "\"Beta is a parameter we estimate from return data.\""),
("Statistic", "統計量", "由樣本計算、用以估計參數的數值。", "樣本平均、樣本變異數。", "\"The sample mean is a statistic that estimates the population mean.\""),
("Nominal Scale", "名目尺度", "僅分類而無順序的測量尺度。", "產業代碼。", "\"Sector labels are on a nominal scale—you can't rank them numerically.\""),
("Ordinal Scale", "順序尺度", "有順序但間距無明確數量意義的尺度。", "信用評等排序。", "\"Credit ratings are ordinal: AA is better than A, but the gap isn't a fixed distance.\""),
("Interval Scale", "等距尺度", "有順序且間距有意義，但零點不代表「無」。", "溫度類比、部分評分。", "\"On an interval scale, differences are meaningful but ratios may not be.\""),
("Ratio Scale", "比率尺度", "有真正零點，可做倍率比較的尺度。", "報酬、價格、市值。", "\"Returns are on a ratio scale—zero means no return, and 10% is twice 5%.\""),
("Frequency Distribution", "次數分配", "將資料分組並計算各組出現次數的表或圖。", "報酬分佈檢視。", "\"The frequency distribution of monthly returns looks roughly bell-shaped.\""),
("Absolute Frequency", "絕對次數", "某一組實際出現的觀察個數。", "直方圖解讀。", "\"The absolute frequency in the −2% to 0% bin is 14 months.\""),
("Relative Frequency", "相對次數", "某一組次數佔總觀察數的比例。", "機率近似。", "\"The relative frequency of positive months is 58%.\""),
("Cumulative Frequency", "累積次數", "低於或等於某上限之所有組次數加總。", "分位數概念。", "\"Cumulative frequency helps us find how many returns fell below zero.\""),
("Histogram", "直方圖", "以長條顯示各組次數的圖形。", "視覺化報酬。", "\"The histogram shows fat tails compared with a normal curve.\""),
("Frequency Polygon", "次數多邊形", "以折線連接各組中點次數的圖。", "比較兩分佈。", "\"Overlay the frequency polygons to compare the two strategies.\""),
("Bar Chart", "長條圖", "用長條比較類別資料的圖。", "產業配置。", "\"This bar chart compares allocation weights across sectors.\""),
("Contingency Table", "列聯表", "呈現兩個類別變數交叉次數的表。", "違約 vs 評等。", "\"The contingency table cross-tabulates default status by rating category.\""),
("Arithmetic Mean", "算術平均數", "所有觀察值加總後除以個數。", "平均報酬（單期等權）。", "\"The arithmetic mean monthly return was 0.8%.\""),
("Geometric Mean", "幾何平均數", "反映複利成長的平均報酬率。", "多年年化報酬。", "\"Use the geometric mean to report multi-year compound performance.\""),
("Weighted Mean", "加權平均數", "依權重加權後的平均。", "組合報酬。", "\"Portfolio return is the weighted mean of constituent returns.\""),
("Median", "中位數", "排序後位於正中的數值，較不受極端值影響。", "偏態資料中心。", "\"With outliers present, the median is more robust than the mean.\""),
("Mode", "眾數", "出現次數最多的數值或類別。", "最常見評等。", "\"The mode of the rating distribution is BBB.\""),
("Quantile", "分位數", "將資料分成等比例部分的切割點，如四分位、百分位。", "風險分位、排名。", "\"The 5% quantile of the loss distribution is our VaR input.\""),
("Quartile", "四分位數", "將資料分成四等分的分位數。", "箱型圖。", "\"The interquartile range sits between the first and third quartiles.\""),
("Percentile", "百分位數", "低於該值的觀察所佔百分比位置。", "同儕排名。", "\"Our fund's return is at the 75th percentile of the peer group.\""),
("Range", "全距", "最大值減最小值，粗略衡量離散程度。", "快速看波動。", "\"The range of daily returns widened during the crisis.\""),
("Mean Absolute Deviation", "平均絕對偏差", "各觀察值與平均數絕對差的平均。", "簡易離散度。", "\"Mean absolute deviation is easier to explain than variance to clients.\""),
("Variance", "變異數", "觀察值與平均數差平方的平均（母體或樣本定義不同）。", "風險度量基礎。", "\"Variance squares deviations, so large outliers dominate the measure.\""),
("Standard Deviation", "標準差", "變異數的平方根，與原單位相同的離散度量。", "波動度、風險。", "\"The strategy's annualized standard deviation is about 12%.\""),
("Sample Variance", "樣本變異數", "以 n−1 為分母的變異數估計，具不偏性。", "樣本估計。", "\"Use sample variance with n−1 when estimating from a sample.\""),
("Coefficient of Variation", "變異係數", "標準差除以平均數，便於比較不同尺度的相對風險。", "跨資產比較。", "\"The coefficient of variation shows risk per unit of mean return.\""),
("Target Downside Deviation", "目標下方偏差", "僅衡量低於目標報酬之離差的風險指標。", "下行風險。", "\"Target downside deviation focuses on returns below the required 5%.\""),
("Skewness", "偏態", "分佈不對稱程度；正偏右尾長，負偏左尾長。", "報酬型態。", "\"Negative skewness means more frequent small gains and occasional large losses.\""),
("Kurtosis", "峰度", "衡量尾部厚度與峰度；超額峰度大於 0 表示厚尾。", "極端風險。", "\"High kurtosis warns that extreme returns occur more often than normal.\""),
("Excess Kurtosis", "超額峰度", "峰度減 3，相對常態分佈的尾部差異。", "常態假設檢視。", "\"Excess kurtosis of 2.5 suggests fat tails versus the normal distribution.\""),
("Sample Skewness", "樣本偏態", "由樣本估計的偏態係數。", "資料診斷。", "\"Sample skewness is negative, so mean return overstates typical outcomes.\""),
("Sample Kurtosis", "樣本峰度", "由樣本估計的峰度。", "模型假設。", "\"Sample kurtosis is too high to assume normality for short-horizon VaR.\""),
("Covariance", "共變異數", "衡量兩變數同向變動程度的指標。", "投資組合風險。", "\"Positive covariance means the assets tend to move together.\""),
("Correlation", "相關係數", "將共變異數標準化至 −1 到 +1 的線性關聯度量。", "分散效果。", "\"Correlation near zero between the assets improves diversification.\""),
("Spurious Correlation", "虛假相關", "看似相關但無因果、或由共同因子造成的誤導關聯。", "資料探勘警覺。", "\"That link looks like spurious correlation driven by a common macro factor.\""),
("Probability", "機率", "事件發生可能性的數值度量，介於 0 與 1。", "情境分析。", "\"We assign a 30% probability to a mild recession scenario.\""),
("Empirical Probability", "經驗機率", "以相對頻率估計的機率。", "歷史違約率。", "\"The empirical probability of default is based on the last 20 years of data.\""),
("Subjective Probability", "主觀機率", "依判斷賦予的機率。", "前瞻情境。", "\"Management's subjective probability of winning the contract is 40%.\""),
("A Priori Probability", "先驗機率", "依邏輯或對稱性得出的機率，如公正骰子。", "理論機率。", "\"For a fair die, the a priori probability of rolling a six is one-sixth.\""),
("Dutch Book Theorem", "荷蘭賭定理", "若主觀機率不一致，可被構造必輸賭局；強調機率須一致。", "機率校準。", "\"Inconsistent scenario probabilities violate the Dutch book idea of coherence.\""),
("Unconditional Probability", "無條件機率", "不依賴其他事件資訊的事件機率，亦稱邊際機率。", "基準機率。", "\"The unconditional probability of default is 2% across the portfolio.\""),
("Conditional Probability", "條件機率", "在已知另一事件發生下的機率，記為 P(A|B)。", "更新判斷。", "\"The conditional probability of default given a downgrade is much higher.\""),
("Joint Probability", "聯合機率", "兩事件同時發生的機率。", "同時違約。", "\"Joint probability of both bonds defaulting is critical for the CDO tranche.\""),
("Multiplication Rule", "乘法法則", "P(AB)=P(A|B)P(B)，用於聯合機率。", "決策樹。", "\"Use the multiplication rule to compute the probability of both events.\""),
("Addition Rule", "加法法則", "P(A或B)=P(A)+P(B)−P(AB)。", "重疊事件。", "\"The addition rule avoids double-counting the overlap between events.\""),
("Independent Events", "獨立事件", "一事件發生不影響另一事件機率。", "風險假設。", "\"If defaults are independent events, portfolio risk is easier to diversify.\""),
("Mutually Exclusive Events", "互斥事件", "不能同時發生的事件。", "情境切割。", "\"Recession and boom are treated as mutually exclusive scenarios here.\""),
("Exhaustive Events", "窮盡事件", "涵蓋所有可能結果的事件集合。", "情境完備。", "\"Our scenarios are exhaustive: they cover every macro outcome we model.\""),
("Bayes' Formula", "貝氏公式", "以新資訊更新先驗機率得到後驗機率的公式。", "訊號更新。", "\"Bayes' formula updates our prior after the earnings surprise.\""),
("Prior Probability", "先驗機率", "取得新資訊前的機率信念。", "貝氏更新。", "\"Our prior probability of a rate cut was 25% before the inflation print.\""),
("Posterior Probability", "後驗機率", "納入新資訊後更新的機率。", "決策修訂。", "\"The posterior probability of a cut rose to 60% after the weak jobs data.\""),
("Expected Value", "期望值", "各結果以機率加權的平均結果。", "報酬預測。", "\"The expected value of the project NPV is positive but skewed.\""),
("Variance of a Random Variable", "隨機變數變異數", "結果偏離期望值的平方期望。", "不確定性。", "\"Higher variance of the random variable means less predictable cash flows.\""),
("Standard Deviation of a Random Variable", "隨機變數標準差", "變異數平方根，衡量不確定性。", "風險溝通。", "\"Quote the standard deviation of the random variable alongside expected return.\""),
("Covariance of Two Random Variables", "兩隨機變數共變異數", "衡量兩隨機變數共變程度。", "組合建構。", "\"We need the covariance of the two random variables for portfolio variance.\""),
("Portfolio Expected Return", "投資組合期望報酬", "各資產權重與期望報酬的加權和。", "資產配置。", "\"Portfolio expected return is the weighted average of component expected returns.\""),
("Portfolio Variance", "投資組合變異數", "取決於權重、各資產變異數與兩兩共變異數。", "分散化計算。", "\"Portfolio variance falls when we add a low-covariance asset.\""),
("Correlation Matrix", "相關矩陣", "多個資產兩兩相關係數組成的矩陣。", "風險模型。", "\"Check the correlation matrix before sizing the relative-value trades.\""),
("Counting Principles", "計數原理", "排列組合等計算可能結果數的方法。", "機率分母。", "\"Counting principles help enumerate outcomes in a discrete probability model.\""),
("Permutation", "排列", "考慮順序的選取方式數。", "順序重要。", "\"If order matters, use a permutation rather than a combination.\""),
("Combination", "組合", "不考慮順序的選取方式數。", "選股子集。", "\"Choosing 5 stocks out of 20 is a combination problem.\""),
("Probability Distribution", "機率分配", "隨機變數所有可能值與其機率的描述。", "模型假設。", "\"We model losses with a probability distribution that allows fat tails.\""),
("Discrete Distribution", "離散分配", "隨機變數只能取有限或可數值的分配。", "違約次數。", "\"Default counts follow a discrete distribution.\""),
("Continuous Distribution", "連續分配", "可在區間內取無限多值的分配。", "價格、報酬。", "\"Returns are often modeled with a continuous distribution.\""),
("Probability Function", "機率函數", "離散隨機變數取某值的機率 p(x)。", "離散模型。", "\"The probability function assigns 0.1 to a full prepayment scenario.\""),
("Probability Density Function", "機率密度函數", "連續分配的密度函數；面積代表機率。", "常態曲線。", "\"Under the PDF, probability equals area between two outcomes.\""),
("Cumulative Distribution Function", "累積分佈函數", "隨機變數小於等於某值的機率 F(x)。", "分位計算。", "\"Read the CDF to find the probability of returns below −5%.\""),
("Uniform Distribution", "均勻分配", "在區間內各點等可能（連續）或各結果等機率（離散）。", "無資訊先驗。", "\"If we have no view, a uniform distribution over scenarios may be a start.\""),
("Binomial Distribution", "二項分配", "n 次獨立成功失敗試驗中成功次數的分配。", "違約計數、上漲天數。", "\"Model the number of defaults with a binomial distribution.\""),
("Bernoulli Trial", "白努利試驗", "只有成功或失敗兩結果的單一試驗。", "二項基礎。", "\"Each loan either defaults or not—a Bernoulli trial.\""),
("Binomial Random Variable", "二項隨機變數", "n 次白努利試驗成功次數。", "次數模型。", "\"The binomial random variable X is the number of up days in 20 sessions.\""),
("Normal Distribution", "常態分配", "鐘形、對稱、由平均數與標準差決定的連續分配。", "許多財務模型假設。", "\"Many risk models assume a normal distribution of returns.\""),
("Univariate Distribution", "單變量分配", "單一變數的機率分配。", "單一資產。", "\"Start with the univariate distribution of equity returns before adding factors.\""),
("Multivariate Distribution", "多變量分配", "多個變數的聯合分配。", "組合建模。", "\"A multivariate distribution captures joint movements across assets.\""),
("Multivariate Normal", "多變量常態", "各邊際為常態且由平均向量與共變矩陣決定的聯合分配。", "平均－變異數分析。", "\"Mean-variance optimization often assumes multivariate normal returns.\""),
("Standard Normal Distribution", "標準常態分配", "平均 0、標準差 1 的常態分配，常用 z。", "查表、z 檢定。", "\"Convert to the standard normal distribution to read critical values.\""),
("Z-Score", "Z分數", "觀察值距離平均數幾個標準差：(x−μ)/σ。", "標準化。", "\"A z-score of −2 means the return is two standard deviations below the mean.\""),
("Confidence Interval", "信賴區間", "以樣本估計母數時，在某信心水準下可能涵蓋真值的區間。", "估計精度。", "\"The 95% confidence interval for mean return is 4% to 8%.\""),
("Student's t-Distribution", "t分配", "小樣本、常態母體且變異數未知時用於推論的厚尾分配。", "小樣本檢定。", "\"With 15 observations, use Student's t-distribution instead of z.\""),
("Degrees of Freedom", "自由度", "可自由變動的資料個數，影響 t、χ² 等分配形狀。", "檢定設定。", "\"Degrees of freedom equal n−1 for a one-sample t-test of the mean.\""),
("Lognormal Distribution", "對數常態分配", "變數取對數後為常態；常用於股價（非負、右偏）。", "Black-Scholes 等。", "\"Stock prices are often modeled as lognormal, while returns are closer to normal.\""),
("Continuously Compounded Return", "連續複利報酬", "ln(S1/S0)，與對數常態價格模型相連。", "選擇權、時間序列。", "\"Use continuously compounded returns when working with log prices.\""),
("Monte Carlo Simulation", "蒙地卡羅模擬", "以隨機抽樣模擬大量可能路徑以估計結果分佈。", "風險、衍生評價。", "\"Monte Carlo simulation generates thousands of rate paths for the callable bond.\""),
("Historical Simulation", "歷史模擬", "以歷史資料重新抽樣或重播來估計風險。", "VaR。", "\"Historical simulation VaR uses actual past return sequences.\""),
("Bootstrap", "自助法", "自樣本有放回重抽以估計抽樣分配。", "小樣本推論。", "\"Bootstrap the Sharpe ratios to see if the difference is significant.\""),
("Central Limit Theorem", "中央極限定理", "樣本夠大時，樣本平均近似常態，無論母體是否常態。", "大樣本推論。", "\"By the central limit theorem, the mean of 50 returns is approximately normal.\""),
("Sampling Distribution", "抽樣分配", "統計量在反覆抽樣下的機率分配。", "估計不確定性。", "\"The sampling distribution of the mean gets tighter as n increases.\""),
("Standard Error", "標準誤", "統計量抽樣分配的標準差，衡量估計精度。", "信賴區間。", "\"The standard error of the mean is σ divided by square root of n.\""),
("Hypothesis Testing", "假設檢定", "用樣本證據決定是否拒絕關於母體的陳述。", "策略是否有效。", "\"Hypothesis testing asks whether observed alpha is just luck.\""),
("Null Hypothesis", "虛無假設", "受檢定、通常代表「無效果」或基準陳述 H0。", "檢定起點。", "\"The null hypothesis is that the true information ratio equals zero.\""),
("Alternative Hypothesis", "對立假設", "與 H0 對立的陳述 Ha。", "雙尾或單尾。", "\"The alternative hypothesis is that the strategy's mean return exceeds the benchmark.\""),
("Type I Error", "型一誤差", "H0 為真卻拒絕它（假陽性）；機率為 α。", "顯著水準。", "\"A Type I error means we adopt a worthless signal by mistake.\""),
("Type II Error", "型二誤差", "H0 為假卻未拒絕（假陰性）；機率為 β。", "檢定力。", "\"A Type II error means we miss a truly profitable anomaly.\""),
("Significance Level", "顯著水準", "可接受的型一誤差機率 α，如 5%。", "臨界值。", "\"We test at a 5% significance level.\""),
("Power of a Test", "檢定力", "H0 為假時正確拒絕的機率，即 1−β。", "樣本數規劃。", "\"Larger samples increase the power of a test to detect true alpha.\""),
("p-value", "p值", "在 H0 為真下，得到同樣或更極端結果的機率。", "報告顯著性。", "\"A p-value of 0.02 means we reject H0 at the 5% level.\""),
("Critical Value", "臨界值", "檢定統計量超過（或低於）此值即拒絕 H0。", "決策規則。", "\"The critical value for a two-tailed 5% z-test is about ±1.96.\""),
("One-Tailed Test", "單尾檢定", "只關心單方向偏離的檢定。", "報酬是否大於 0。", "\"Use a one-tailed test if we only care about positive alpha.\""),
("Two-Tailed Test", "雙尾檢定", "關心雙方向偏離的檢定。", "是否異於基準。", "\"A two-tailed test checks whether mean return differs from 8% in either direction.\""),
("t-Test", "t檢定", "用 t 統計量對平均數等進行的檢定。", "小樣本均值。", "\"Run a t-test on the paired differences in strategy returns.\""),
("z-Test", "z檢定", "大樣本或已知變異數時用常態的檢定。", "大樣本。", "\"With n=500, a z-test for the mean is appropriate.\""),
("Chi-Square Test", "卡方檢定", "常用於變異數或類別適合度／獨立性的檢定。", "波動是否改變。", "\"A chi-square test can assess whether variance equals a hypothesized value.\""),
("F-Test", "F檢定", "比較兩變異數或用於迴歸整體顯著性。", "風險比較。", "\"An F-test compares the variances of the two portfolios.\""),
("Parametric Test", "母數檢定", "對分配形態有假設（如常態）的檢定。", "經典檢定。", "\"Parametric tests are powerful when normality roughly holds.\""),
("Nonparametric Test", "無母數檢定", "較少依賴分配假設的檢定，如符號檢定。", "偏態資料。", "\"With heavy skew, consider a nonparametric test.\""),
("Spearman Rank Correlation", "斯皮爾曼等級相關", "以排序計算的相關，屬無母數關聯度量。", "非線性單調。", "\"Spearman rank correlation is robust to extreme outliers in returns.\""),
("Simple Linear Regression", "簡單線性迴歸", "以單一自變數解釋因變數：Y=b0+b1X+ε。", "beta 估計。", "\"Simple linear regression of stock returns on the market estimates beta.\""),
("Multiple Regression", "多元迴歸", "多個自變數解釋因變數的迴歸。", "多因子。", "\"Multiple regression isolates the effect of size after controlling for value.\""),
("Dependent Variable", "應變數", "被解釋的變數 Y。", "模型左邊。", "\"Excess return is the dependent variable in our factor model.\""),
("Independent Variable", "自變數", "用來解釋的變數 X。", "因子暴露。", "\"Market excess return is the independent variable in the CAPM regression.\""),
("Intercept", "截距", "迴歸中 X=0 時 Y 的預期值 b0。", "alpha 相關。", "\"In Jensen's alpha, the intercept measures abnormal return.\""),
("Slope Coefficient", "斜率係數", "X 變一單位時 Y 的預期變化 b1。", "敏感度。", "\"The slope coefficient on duration approximates interest-rate sensitivity.\""),
("Residual", "殘差", "實際 Y 與預測 Y 的差。", "模型診斷。", "\"Large residuals in 2020 suggest the model missed the crisis regime.\""),
("ANOVA", "變異數分析", "分解總變異並檢定迴歸整體是否顯著。", "模型 F 檢定。", "\"ANOVA shows whether the regression explains a significant share of variance.\""),
("R-squared", "決定係數", "應變數變異中被模型解釋的比例。", "擬合優度。", "\"An R-squared of 0.35 means factors explain 35% of return variance.\""),
("Adjusted R-squared", "調整後決定係數", "對自變數個數調整後的 R²，避免過度擬合表象。", "模型比較。", "\"Prefer adjusted R-squared when comparing models with different factor counts.\""),
("Standard Error of Estimate", "估計標準誤", "殘差離散程度，衡量預測精確度。", "預測區間。", "\"A lower standard error of estimate means tighter prediction intervals.\""),
("Homoskedasticity", "同方差", "殘差變異數固定的假設。", "OLS 假設。", "\"Homoskedasticity fails when residual variance grows with firm size.\""),
("Heteroskedasticity", "異方差", "殘差變異數非常數。", "穩健標準誤。", "\"Heteroskedasticity can bias standard errors and t-statistics.\""),
("Autocorrelation", "自我相關", "殘差與自身落後期相關。", "時間序列。", "\"Autocorrelation in residuals violates classical regression assumptions.\""),
("Multicollinearity", "多重共線性", "自變數彼此高度相關，使係數不穩定。", "因子選擇。", "\"Multicollinearity between value factors inflates coefficient standard errors.\""),
("Dummy Variable", "虛擬變數", "取 0/1 以表示類別效應的變數。", "產業、危機期。", "\"Add a crisis dummy variable to capture the 2008 regime shift.\""),
("Log-Lin Model", "對數－線性模型", "應變數取對數、自變數為水準的模型，斜率近似半彈性。", "成長解釋。", "\"In a log-lin model, the slope is an approximate percentage change in Y.\""),
("Lin-Log Model", "線性－對數模型", "自變數取對數的模型。", "報酬遞減。", "\"A lin-log model fits when Y changes with proportional shifts in X.\""),
("Log-Log Model", "雙對數模型", "兩邊取對數，斜率為彈性。", "需求彈性。", "\"The log-log model estimates elasticity of demand directly.\""),
("Time Series", "時間序列", "依時間順序觀測的資料序列。", "報酬、通膨。", "\"Monthly returns form a time series we can test for momentum.\""),
("Trend", "趨勢", "時間序列長期上升或下降的成分。", "宏觀序列。", "\"GDP shows an upward trend over decades.\""),
("Seasonality", "季節性", "在固定週期重複出現的型態。", "零售銷售。", "\"Retail sales show strong seasonality around the holidays.\""),
("Covariance Stationary", "共變異數平穩", "平均、變異數與自我共變不隨時間變，僅依落後期。", "AR 模型前提。", "\"Many forecasting models require a covariance-stationary series.\""),
("Autoregressive Model", "自我迴歸模型", "以自身落後期預測現值的模型，如 AR(1)。", "報酬預測。", "\"An AR(1) autoregressive model uses last month's return to forecast this month.\""),
("Mean Reversion", "均值回歸", "變數傾向回到長期平均水準的性質。", "評價偏離。", "\"If spreads show mean reversion, wide levels may attract buyers.\""),
("Random Walk", "隨機漫步", "今日值＝昨日值＋不可預測衝擊；差分後常較平穩。", "價格可預測性。", "\"If prices follow a random walk, past prices don't forecast future changes.\""),
("Unit Root", "單根", "使序列非平穩的特徵根；常以檢定偵測。", "差分決策。", "\"A unit root in yields suggests we should model changes, not levels.\""),
("Machine Learning", "機器學習", "讓演算法從資料學習模式以預測或分類的方法集合。", "另類資料、訊號。", "\"Machine learning can uncover nonlinear patterns traditional models miss.\""),
("Supervised Learning", "監督式學習", "用已知標籤的資料訓練模型以預測新資料。", "違約預測。", "\"Default prediction is a supervised learning problem with labeled outcomes.\""),
("Unsupervised Learning", "非監督式學習", "在無標籤下尋找結構，如分群。", "客戶分群。", "\"Unsupervised learning clusters clients by behavior without predefined labels.\""),
("Deep Learning", "深度學習", "使用多層神經網路的機器學習方法。", "影像、複雜型態。", "\"Deep learning may help parse satellite images for retail traffic signals.\""),
("Overfitting", "過度配適", "模型擬合噪音導致樣本外表現差。", "複雜模型。", "\"Too many factors cause overfitting and weak live performance.\""),
("Cross-Validation", "交叉驗證", "反覆分割訓練／驗證集以評估樣本外表現。", "模型選擇。", "\"Use cross-validation to tune hyperparameters without peeking at the test set.\""),
("Training Sample", "訓練樣本", "用來估計模型參數的資料集。", "模型建置。", "\"Fit the model on the training sample from 2000 to 2015.\""),
("Validation Sample", "驗證樣本", "用於調參、防止過度配適的樣本。", "超參數。", "\"Choose the penalty strength with the validation sample.\""),
("Test Sample", "測試樣本", "最終評估模型真實樣本外表現的資料。", "上線前評估。", "\"Report performance only on the untouched test sample.\""),
("Bias-Variance Tradeoff", "偏差－變異權衡", "模型過簡偏差大、過複變異大，須平衡。", "複雜度選擇。", "\"The bias-variance tradeoff guides how flexible our signal model should be.\""),
("Penalized Regression", "懲罰迴歸", "如 LASSO／Ridge，對係數加罰以降低過度配適。", "多因子篩選。", "\"LASSO is a penalized regression that can shrink weak factors to zero.\""),
("Classification", "分類", "預測類別標籤的監督式任務。", "漲跌、違約。", "\"Bankruptcy prediction is a classification task, not a regression for price.\""),
("Confusion Matrix", "混淆矩陣", "呈現分類真偽陽性／陰性的表。", "模型評估。", "\"Read the confusion matrix to see false positives in fraud detection.\""),
("Precision and Recall", "精確率與召回率", "精確率＝預測為正中真正比例；召回率＝真正例被找出比例。", "不平衡資料。", "\"In rare-default data, track precision and recall, not only accuracy.\""),
("Big Data", "大數據", "具大量、高速、多樣性等特徵的資料環境。", "另類資料策略。", "\"Big data from credit-card swipes can complement traditional financials.\""),
("Fintech", "金融科技", "技術驅動的金融創新與服務模式。", "產業趨勢。", "\"Fintech lenders use alternative data in credit scoring models.\""),
]